GPU: 0
action_disturbance_enabled: false
action_gain_max: 1.0
action_gain_min: 1.0
alpha_constraint: 0.8
angular_rate_noise_std: 0.0
attitude_noise_std: 0.0
body_rate_action_noise_std: 0.0
calculate_depth: true
continue_training: false
delta_time: 0.03
disturbances_in_test: false
env_copy: 512
epochs: 40000
fixed_lambda: null
height: 64
horizontal_fov_deg: 120
l2_regularization: 1.0e-05
lambda_: 2.329946756362915
lambda_update_interval: 1
learning_rate_lambda: 0.02
learning_rate_policy: 0.0005
max_angular_rates: 3.0
max_motor_delay: 0.1
max_num_obstacles: 4
max_obstacle_radius: 0.7
max_range: 20.0
max_speed: 1.0
min_motor_delay: 0.1
min_num_obstacles: 4
min_obs_gap: 1.0
min_obstacle_radius: 0.7
motor_delay: 0.1
num_obstacles: 4
obs_dim: 2
obs_size: 0.5
obs_type: 1
observation_noise_enabled: false
obstacle_beta2: 8.0
obstacle_resample_interval: 1
poisson_room: true
policy_file: null
position_control: false
position_noise_std: 0.0
random_seed: 10
randomize_motor_delay: false
randomize_motor_delay_in_test: false
randomize_obstacle_count: true
randomize_obstacle_radius: true
randomize_obstacle_radius_in_test: false
randomize_obstacles: true
rendering: false
return_pointcloud: false
room_size: 10.0
sampling_z_max: 1.2
sampling_z_min: 0.8
save_folder: logs/vel_tracking/
segmentation_camera: false
sim_steps: 300
single_motor_max_thrust: 2.14
tbptt_chunk: 50
test_motor_delay: 0.1
test_obstacle_radius: 0.7
test_start_position:
- 2
- 2.5
- 1
test_target_position:
- 8
- 2.5
- 1
throttle_action_noise_std: 0.0
thrust_randomization_max_scale: 1.0
thrust_randomization_min_scale: 1.0
to_randomize_obs_location: false
train: true
turn_on_scheduler: false
velocity_noise_std: 0.0
warp_frame: 1.0
width: 64
policy_global: true
