GPU: 0
body_frame: false
calculate_depth: true
delta_time: 0.02
discount: 0.99
end_goal:
- 3.0
- 0
- 1.0
epochs: 5000
height: 64
horizontal_fov_deg: 120
learning_rate: 0.0005
max_angular_rates: 3.0
max_range: 20.0
motor_delay: 0.1
num_obstacles: 0
obs_dim: 2
obs_size: 1
obs_type: 1
policy_file: 20260304-152946
policy_global: 1.0
position_control: true
rendering: false
residual_dynamics_file: 20260226-123535
residual_dynamics_folder: residual_dynamics
return_pointcloud: false
room_size: 5.0
save_folder: logs/circular_trajectory/
segmentation_camera: false
sim_steps: 300
single_motor_max_thrust: 1.72
to_randomize_obs_location: false
train: true
turn_on_scheduler: false
use_pre_trained: false
use_residual_dynamics: false
warp_frame: 1.0
width: 64
window_location:
- 1.5
- 0
- 1.0
window_orientation: 30
