/* This file was automatically generated by CasADi 3.6.5.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) ACADOS_model_impl_dae_fun_jac_x_xdot_z_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[34] = {30, 1, 0, 30, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29};
static const casadi_int casadi_s4[59] = {13, 13, 0, 0, 0, 0, 1, 2, 3, 8, 14, 20, 25, 31, 37, 43, 0, 1, 2, 3, 4, 7, 8, 9, 3, 4, 5, 6, 8, 9, 3, 4, 5, 6, 7, 9, 3, 4, 6, 7, 8, 6, 7, 8, 9, 11, 12, 6, 7, 8, 9, 10, 12, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s5[29] = {13, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s6[3] = {13, 0, 0};

/* ACADOS_model_impl_dae_fun_jac_x_xdot_z:(i0[13],i1[13],i2[4],i3[],i4[],i5[30])->(o0[13],o1[13x13,43nz],o2[13x13,13nz],o3[13x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[1]? arg[1][0] : 0;
  a1=arg[0]? arg[0][3] : 0;
  a0=(a0-a1);
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[1]? arg[1][1] : 0;
  a1=arg[0]? arg[0][4] : 0;
  a0=(a0-a1);
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[1]? arg[1][2] : 0;
  a1=arg[0]? arg[0][5] : 0;
  a0=(a0-a1);
  if (res[0]!=0) res[0][2]=a0;
  a0=arg[1]? arg[1][3] : 0;
  a1=4.0322580645161290e+00;
  a2=2.;
  a3=arg[0]? arg[0][7] : 0;
  a4=arg[0]? arg[0][9] : 0;
  a5=(a3*a4);
  a6=arg[0]? arg[0][6] : 0;
  a7=arg[0]? arg[0][8] : 0;
  a8=(a6*a7);
  a5=(a5+a8);
  a5=(a2*a5);
  a8=arg[2]? arg[2][0] : 0;
  a5=(a5*a8);
  a5=(a1*a5);
  a0=(a0-a5);
  if (res[0]!=0) res[0][3]=a0;
  a0=arg[1]? arg[1][4] : 0;
  a5=(a7*a4);
  a9=(a6*a3);
  a5=(a5-a9);
  a5=(a2*a5);
  a5=(a5*a8);
  a5=(a1*a5);
  a0=(a0-a5);
  if (res[0]!=0) res[0][4]=a0;
  a0=arg[1]? arg[1][5] : 0;
  a5=1.;
  a9=casadi_sq(a3);
  a10=casadi_sq(a7);
  a9=(a9+a10);
  a9=(a2*a9);
  a9=(a5-a9);
  a9=(a9*a8);
  a9=(a1*a9);
  a10=-9.8100000000000005e+00;
  a9=(a9+a10);
  a0=(a0-a9);
  if (res[0]!=0) res[0][5]=a0;
  a0=arg[1]? arg[1][6] : 0;
  a9=5.0000000000000000e-01;
  a10=arg[0]? arg[0][10] : 0;
  a11=(a10*a3);
  a12=arg[0]? arg[0][11] : 0;
  a13=(a12*a7);
  a11=(a11+a13);
  a13=arg[0]? arg[0][12] : 0;
  a14=(a13*a4);
  a11=(a11+a14);
  a11=(a9*a11);
  a0=(a0+a11);
  if (res[0]!=0) res[0][6]=a0;
  a0=arg[1]? arg[1][7] : 0;
  a11=(a10*a6);
  a14=(a13*a7);
  a11=(a11+a14);
  a14=(a12*a4);
  a11=(a11-a14);
  a11=(a9*a11);
  a0=(a0-a11);
  if (res[0]!=0) res[0][7]=a0;
  a0=arg[1]? arg[1][8] : 0;
  a11=(a12*a6);
  a14=(a13*a3);
  a11=(a11-a14);
  a14=(a10*a4);
  a11=(a11+a14);
  a11=(a9*a11);
  a0=(a0-a11);
  if (res[0]!=0) res[0][8]=a0;
  a0=arg[1]? arg[1][9] : 0;
  a11=(a13*a6);
  a14=(a12*a3);
  a11=(a11+a14);
  a14=(a10*a7);
  a11=(a11-a14);
  a11=(a9*a11);
  a0=(a0-a11);
  if (res[0]!=0) res[0][9]=a0;
  a0=arg[1]? arg[1][10] : 0;
  a11=2.5510204081632655e+03;
  a14=arg[2]? arg[2][1] : 0;
  a15=6.3900000000000003e-04;
  a16=(a15*a12);
  a17=(a16*a13);
  a18=4.0499999999999998e-04;
  a19=(a18*a13);
  a20=(a19*a12);
  a17=(a17-a20);
  a14=(a14-a17);
  a14=(a11*a14);
  a0=(a0-a14);
  if (res[0]!=0) res[0][10]=a0;
  a0=arg[1]? arg[1][11] : 0;
  a14=2.4691358024691358e+03;
  a17=arg[2]? arg[2][2] : 0;
  a20=3.9199999999999999e-04;
  a21=(a20*a13);
  a22=(a21*a10);
  a23=(a15*a10);
  a24=(a23*a13);
  a22=(a22-a24);
  a17=(a17-a22);
  a17=(a14*a17);
  a0=(a0-a17);
  if (res[0]!=0) res[0][11]=a0;
  a0=arg[1]? arg[1][12] : 0;
  a17=1.5649452269170579e+03;
  a22=arg[2]? arg[2][3] : 0;
  a24=(a18*a10);
  a25=(a24*a12);
  a26=(a20*a12);
  a27=(a26*a10);
  a25=(a25-a27);
  a22=(a22-a25);
  a22=(a17*a22);
  a0=(a0-a22);
  if (res[0]!=0) res[0][12]=a0;
  a0=-1.;
  if (res[1]!=0) res[1][0]=a0;
  if (res[1]!=0) res[1][1]=a0;
  if (res[1]!=0) res[1][2]=a0;
  a0=(a2*a7);
  a0=(a8*a0);
  a0=(a1*a0);
  a0=(-a0);
  if (res[1]!=0) res[1][3]=a0;
  a0=(a2*a3);
  a0=(a8*a0);
  a0=(a1*a0);
  if (res[1]!=0) res[1][4]=a0;
  a0=(a9*a10);
  a0=(-a0);
  if (res[1]!=0) res[1][5]=a0;
  a0=(a9*a12);
  a0=(-a0);
  if (res[1]!=0) res[1][6]=a0;
  a0=(a9*a13);
  a0=(-a0);
  if (res[1]!=0) res[1][7]=a0;
  a0=(a2*a4);
  a0=(a8*a0);
  a0=(a1*a0);
  a0=(-a0);
  if (res[1]!=0) res[1][8]=a0;
  a0=(a2*a6);
  a0=(a8*a0);
  a0=(a1*a0);
  if (res[1]!=0) res[1][9]=a0;
  a0=(a3+a3);
  a0=(a2*a0);
  a0=(a8*a0);
  a0=(a1*a0);
  if (res[1]!=0) res[1][10]=a0;
  a0=(a9*a10);
  if (res[1]!=0) res[1][11]=a0;
  a0=(a9*a13);
  if (res[1]!=0) res[1][12]=a0;
  a0=(a9*a12);
  a0=(-a0);
  if (res[1]!=0) res[1][13]=a0;
  a0=(a2*a6);
  a0=(a8*a0);
  a0=(a1*a0);
  a0=(-a0);
  if (res[1]!=0) res[1][14]=a0;
  a0=(a2*a4);
  a0=(a8*a0);
  a0=(a1*a0);
  a0=(-a0);
  if (res[1]!=0) res[1][15]=a0;
  a0=(a7+a7);
  a0=(a2*a0);
  a0=(a8*a0);
  a0=(a1*a0);
  if (res[1]!=0) res[1][16]=a0;
  a0=(a9*a12);
  if (res[1]!=0) res[1][17]=a0;
  a0=(a9*a13);
  a0=(-a0);
  if (res[1]!=0) res[1][18]=a0;
  a0=(a9*a10);
  if (res[1]!=0) res[1][19]=a0;
  a0=(a2*a3);
  a0=(a8*a0);
  a0=(a1*a0);
  a0=(-a0);
  if (res[1]!=0) res[1][20]=a0;
  a2=(a2*a7);
  a8=(a8*a2);
  a1=(a1*a8);
  a1=(-a1);
  if (res[1]!=0) res[1][21]=a1;
  a1=(a9*a13);
  if (res[1]!=0) res[1][22]=a1;
  a1=(a9*a12);
  if (res[1]!=0) res[1][23]=a1;
  a1=(a9*a10);
  a1=(-a1);
  if (res[1]!=0) res[1][24]=a1;
  a1=(a9*a3);
  if (res[1]!=0) res[1][25]=a1;
  a1=(a9*a6);
  a1=(-a1);
  if (res[1]!=0) res[1][26]=a1;
  a1=(a9*a4);
  a1=(-a1);
  if (res[1]!=0) res[1][27]=a1;
  a1=(a9*a7);
  if (res[1]!=0) res[1][28]=a1;
  a1=(a15*a13);
  a21=(a21-a1);
  a21=(a14*a21);
  if (res[1]!=0) res[1][29]=a21;
  a21=(a18*a12);
  a21=(a21-a26);
  a21=(a17*a21);
  if (res[1]!=0) res[1][30]=a21;
  a21=(a9*a7);
  if (res[1]!=0) res[1][31]=a21;
  a21=(a9*a4);
  if (res[1]!=0) res[1][32]=a21;
  a21=(a9*a6);
  a21=(-a21);
  if (res[1]!=0) res[1][33]=a21;
  a21=(a9*a3);
  a21=(-a21);
  if (res[1]!=0) res[1][34]=a21;
  a15=(a15*a13);
  a15=(a15-a19);
  a15=(a11*a15);
  if (res[1]!=0) res[1][35]=a15;
  a15=(a20*a10);
  a24=(a24-a15);
  a17=(a17*a24);
  if (res[1]!=0) res[1][36]=a17;
  a4=(a9*a4);
  if (res[1]!=0) res[1][37]=a4;
  a7=(a9*a7);
  a7=(-a7);
  if (res[1]!=0) res[1][38]=a7;
  a3=(a9*a3);
  if (res[1]!=0) res[1][39]=a3;
  a9=(a9*a6);
  a9=(-a9);
  if (res[1]!=0) res[1][40]=a9;
  a18=(a18*a12);
  a16=(a16-a18);
  a11=(a11*a16);
  if (res[1]!=0) res[1][41]=a11;
  a20=(a20*a10);
  a20=(a20-a23);
  a14=(a14*a20);
  if (res[1]!=0) res[1][42]=a14;
  if (res[2]!=0) res[2][0]=a5;
  if (res[2]!=0) res[2][1]=a5;
  if (res[2]!=0) res[2][2]=a5;
  if (res[2]!=0) res[2][3]=a5;
  if (res[2]!=0) res[2][4]=a5;
  if (res[2]!=0) res[2][5]=a5;
  if (res[2]!=0) res[2][6]=a5;
  if (res[2]!=0) res[2][7]=a5;
  if (res[2]!=0) res[2][8]=a5;
  if (res[2]!=0) res[2][9]=a5;
  if (res[2]!=0) res[2][10]=a5;
  if (res[2]!=0) res[2][11]=a5;
  if (res[2]!=0) res[2][12]=a5;
  return 0;
}

CASADI_SYMBOL_EXPORT int ACADOS_model_impl_dae_fun_jac_x_xdot_z(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int ACADOS_model_impl_dae_fun_jac_x_xdot_z_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int ACADOS_model_impl_dae_fun_jac_x_xdot_z_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ACADOS_model_impl_dae_fun_jac_x_xdot_z_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int ACADOS_model_impl_dae_fun_jac_x_xdot_z_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ACADOS_model_impl_dae_fun_jac_x_xdot_z_release(int mem) {
}

CASADI_SYMBOL_EXPORT void ACADOS_model_impl_dae_fun_jac_x_xdot_z_incref(void) {
}

CASADI_SYMBOL_EXPORT void ACADOS_model_impl_dae_fun_jac_x_xdot_z_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int ACADOS_model_impl_dae_fun_jac_x_xdot_z_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int ACADOS_model_impl_dae_fun_jac_x_xdot_z_n_out(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_real ACADOS_model_impl_dae_fun_jac_x_xdot_z_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ACADOS_model_impl_dae_fun_jac_x_xdot_z_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ACADOS_model_impl_dae_fun_jac_x_xdot_z_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ACADOS_model_impl_dae_fun_jac_x_xdot_z_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s2;
    case 5: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ACADOS_model_impl_dae_fun_jac_x_xdot_z_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s4;
    case 2: return casadi_s5;
    case 3: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int ACADOS_model_impl_dae_fun_jac_x_xdot_z_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int ACADOS_model_impl_dae_fun_jac_x_xdot_z_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 4*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
