/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) ACADOS_model_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s2[21] = {17, 1, 0, 17, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16};

/* ACADOS_model_expl_vde_adj:(i0[13],i1[13],i2[4],i3[17])->(o0[17]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[1]? arg[1][0] : 0;
  if (res[0]!=0) res[0][0]=a0;
  a1=arg[1]? arg[1][1] : 0;
  if (res[0]!=0) res[0][1]=a1;
  a2=arg[1]? arg[1][2] : 0;
  if (res[0]!=0) res[0][2]=a2;
  a3=arg[1]? arg[1][3] : 0;
  a4=1.0000000000000001e-01;
  a0=(a4*a0);
  a0=(a3+a0);
  if (res[0]!=0) res[0][3]=a0;
  a0=arg[1]? arg[1][4] : 0;
  a1=(a4*a1);
  a1=(a0+a1);
  if (res[0]!=0) res[0][4]=a1;
  a1=arg[1]? arg[1][5] : 0;
  a2=(a4*a2);
  a2=(a1+a2);
  if (res[0]!=0) res[0][5]=a2;
  a2=arg[0]? arg[0][12] : 0;
  a5=5.0000000000000000e-01;
  a6=arg[1]? arg[1][9] : 0;
  a7=(a4*a6);
  a7=(a5*a7);
  a8=(a2*a7);
  a9=arg[0]? arg[0][11] : 0;
  a10=arg[1]? arg[1][8] : 0;
  a11=(a4*a10);
  a11=(a5*a11);
  a12=(a9*a11);
  a8=(a8+a12);
  a12=arg[0]? arg[0][10] : 0;
  a13=arg[1]? arg[1][7] : 0;
  a14=(a4*a13);
  a14=(a5*a14);
  a15=(a12*a14);
  a8=(a8+a15);
  a15=arg[1]? arg[1][6] : 0;
  a8=(a8+a15);
  a16=arg[0]? arg[0][7] : 0;
  a17=2.;
  a18=arg[2]? arg[2][0] : 0;
  a19=arg[2]? arg[2][1] : 0;
  a18=(a18+a19);
  a19=arg[2]? arg[2][2] : 0;
  a18=(a18+a19);
  a19=arg[2]? arg[2][3] : 0;
  a18=(a18+a19);
  a19=4.8780487804878048e+00;
  a0=(a4*a0);
  a0=(a19*a0);
  a20=(a18*a0);
  a20=(a17*a20);
  a21=(a16*a20);
  a8=(a8-a21);
  a21=arg[0]? arg[0][8] : 0;
  a3=(a4*a3);
  a3=(a19*a3);
  a22=(a18*a3);
  a22=(a17*a22);
  a23=(a21*a22);
  a8=(a8+a23);
  if (res[0]!=0) res[0][6]=a8;
  a8=(a9*a7);
  a23=(a2*a11);
  a8=(a8-a23);
  a8=(a8+a13);
  a15=(a4*a15);
  a15=(a5*a15);
  a13=(a12*a15);
  a8=(a8-a13);
  a13=(a16+a16);
  a1=(a4*a1);
  a19=(a19*a1);
  a18=(a18*a19);
  a18=(a17*a18);
  a13=(a13*a18);
  a8=(a8-a13);
  a13=arg[0]? arg[0][6] : 0;
  a1=(a13*a20);
  a8=(a8-a1);
  a1=arg[0]? arg[0][9] : 0;
  a23=(a1*a22);
  a8=(a8+a23);
  if (res[0]!=0) res[0][7]=a8;
  a8=(a12*a7);
  a10=(a10-a8);
  a8=(a2*a14);
  a10=(a10+a8);
  a8=(a9*a15);
  a10=(a10-a8);
  a8=(a21+a21);
  a8=(a8*a18);
  a10=(a10-a8);
  a8=(a1*a20);
  a10=(a10+a8);
  a8=(a13*a22);
  a10=(a10+a8);
  if (res[0]!=0) res[0][8]=a10;
  a10=(a12*a11);
  a6=(a6+a10);
  a10=(a9*a14);
  a6=(a6-a10);
  a10=(a2*a15);
  a6=(a6-a10);
  a20=(a21*a20);
  a6=(a6+a20);
  a22=(a16*a22);
  a6=(a6+a22);
  if (res[0]!=0) res[0][9]=a6;
  a6=3.9199999999999999e-04;
  a22=(a6*a9);
  a20=1.5649452269170579e+03;
  a10=arg[1]? arg[1][12] : 0;
  a8=(a4*a10);
  a20=(a20*a8);
  a22=(a22*a20);
  a8=4.0499999999999998e-04;
  a18=(a9*a20);
  a18=(a8*a18);
  a22=(a22-a18);
  a18=6.3900000000000003e-04;
  a23=2.4691358024691358e+03;
  a24=arg[1]? arg[1][11] : 0;
  a25=(a4*a24);
  a23=(a23*a25);
  a25=(a2*a23);
  a25=(a18*a25);
  a22=(a22+a25);
  a25=(a6*a2);
  a25=(a25*a23);
  a22=(a22-a25);
  a25=arg[1]? arg[1][10] : 0;
  a22=(a22+a25);
  a26=(a21*a7);
  a22=(a22-a26);
  a26=(a1*a11);
  a22=(a22+a26);
  a26=(a13*a14);
  a22=(a22+a26);
  a26=(a16*a15);
  a22=(a22-a26);
  if (res[0]!=0) res[0][10]=a22;
  a22=(a12*a20);
  a22=(a6*a22);
  a26=(a8*a12);
  a26=(a26*a20);
  a22=(a22-a26);
  a22=(a22+a24);
  a24=(a8*a2);
  a26=2.5510204081632655e+03;
  a4=(a4*a25);
  a26=(a26*a4);
  a24=(a24*a26);
  a22=(a22+a24);
  a2=(a2*a26);
  a2=(a18*a2);
  a22=(a22-a2);
  a2=(a16*a7);
  a22=(a22+a2);
  a2=(a13*a11);
  a22=(a22+a2);
  a2=(a1*a14);
  a22=(a22-a2);
  a2=(a21*a15);
  a22=(a22-a2);
  if (res[0]!=0) res[0][11]=a22;
  a22=(a18*a12);
  a22=(a22*a23);
  a10=(a10+a22);
  a12=(a12*a23);
  a6=(a6*a12);
  a10=(a10-a6);
  a6=(a9*a26);
  a8=(a8*a6);
  a10=(a10+a8);
  a18=(a18*a9);
  a18=(a18*a26);
  a10=(a10-a18);
  a7=(a13*a7);
  a10=(a10+a7);
  a11=(a16*a11);
  a10=(a10-a11);
  a14=(a21*a14);
  a10=(a10+a14);
  a15=(a1*a15);
  a10=(a10-a15);
  if (res[0]!=0) res[0][12]=a10;
  a10=2.9265000000000002e-07;
  a10=(a10*a20);
  a20=1.6500000000000001e-01;
  a15=(a5*a23);
  a15=(a20*a15);
  a15=(a10-a15);
  a14=1.;
  a11=casadi_sq(a16);
  a7=casadi_sq(a21);
  a11=(a11+a7);
  a11=(a17*a11);
  a14=(a14-a11);
  a14=(a14*a19);
  a19=(a21*a1);
  a11=(a13*a16);
  a19=(a19-a11);
  a19=(a17*a19);
  a19=(a19*a0);
  a14=(a14+a19);
  a16=(a16*a1);
  a13=(a13*a21);
  a16=(a16+a13);
  a17=(a17*a16);
  a17=(a17*a3);
  a14=(a14+a17);
  a15=(a15+a14);
  if (res[0]!=0) res[0][13]=a15;
  a15=(a5*a26);
  a15=(a20*a15);
  a15=(a10+a15);
  a15=(a14-a15);
  if (res[0]!=0) res[0][14]=a15;
  a23=(a5*a23);
  a23=(a20*a23);
  a23=(a10+a23);
  a23=(a23+a14);
  if (res[0]!=0) res[0][15]=a23;
  a5=(a5*a26);
  a20=(a20*a5);
  a20=(a20-a10);
  a20=(a20+a14);
  if (res[0]!=0) res[0][16]=a20;
  return 0;
}

CASADI_SYMBOL_EXPORT int ACADOS_model_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int ACADOS_model_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int ACADOS_model_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ACADOS_model_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int ACADOS_model_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ACADOS_model_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void ACADOS_model_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void ACADOS_model_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int ACADOS_model_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int ACADOS_model_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real ACADOS_model_expl_vde_adj_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ACADOS_model_expl_vde_adj_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ACADOS_model_expl_vde_adj_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ACADOS_model_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ACADOS_model_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int ACADOS_model_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
