/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) ACADOS_model_impl_dae_fun_jac_x_xdot_u_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[14] = {10, 1, 0, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[22] = {18, 1, 0, 18, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17};
static const casadi_int casadi_s4[38] = {10, 10, 0, 0, 0, 0, 1, 2, 3, 8, 14, 20, 25, 0, 1, 2, 3, 4, 7, 8, 9, 3, 4, 5, 6, 8, 9, 3, 4, 5, 6, 7, 9, 3, 4, 6, 7, 8};
static const casadi_int casadi_s5[23] = {10, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9};
static const casadi_int casadi_s6[22] = {10, 4, 0, 3, 7, 11, 15, 3, 4, 5, 6, 7, 8, 9, 6, 7, 8, 9, 6, 7, 8, 9};

/* ACADOS_model_impl_dae_fun_jac_x_xdot_u:(i0[10],i1[10],i2[4],i3[],i4[],i5[18])->(o0[10],o1[10x10,25nz],o2[10x10,10nz],o3[10x4,15nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[1]? arg[1][0] : 0;
  a1=arg[0]? arg[0][3] : 0;
  a0=(a0-a1);
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[1]? arg[1][1] : 0;
  a1=arg[0]? arg[0][4] : 0;
  a0=(a0-a1);
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[1]? arg[1][2] : 0;
  a1=arg[0]? arg[0][5] : 0;
  a0=(a0-a1);
  if (res[0]!=0) res[0][2]=a0;
  a0=arg[1]? arg[1][3] : 0;
  a1=4.0322580645161290e+00;
  a2=2.;
  a3=arg[0]? arg[0][7] : 0;
  a4=arg[0]? arg[0][9] : 0;
  a5=(a3*a4);
  a6=arg[0]? arg[0][6] : 0;
  a7=arg[0]? arg[0][8] : 0;
  a8=(a6*a7);
  a5=(a5+a8);
  a5=(a2*a5);
  a8=arg[2]? arg[2][0] : 0;
  a9=(a5*a8);
  a9=(a1*a9);
  a0=(a0-a9);
  if (res[0]!=0) res[0][3]=a0;
  a0=arg[1]? arg[1][4] : 0;
  a9=(a7*a4);
  a10=(a6*a3);
  a9=(a9-a10);
  a9=(a2*a9);
  a10=(a9*a8);
  a10=(a1*a10);
  a0=(a0-a10);
  if (res[0]!=0) res[0][4]=a0;
  a0=arg[1]? arg[1][5] : 0;
  a10=1.;
  a11=casadi_sq(a3);
  a12=casadi_sq(a7);
  a11=(a11+a12);
  a11=(a2*a11);
  a11=(a10-a11);
  a12=(a11*a8);
  a12=(a1*a12);
  a13=-9.8100000000000005e+00;
  a12=(a12+a13);
  a0=(a0-a12);
  if (res[0]!=0) res[0][5]=a0;
  a0=arg[1]? arg[1][6] : 0;
  a12=5.0000000000000000e-01;
  a13=arg[2]? arg[2][1] : 0;
  a14=(a13*a3);
  a15=arg[2]? arg[2][2] : 0;
  a16=(a15*a7);
  a14=(a14+a16);
  a16=arg[2]? arg[2][3] : 0;
  a17=(a16*a4);
  a14=(a14+a17);
  a14=(a12*a14);
  a0=(a0+a14);
  if (res[0]!=0) res[0][6]=a0;
  a0=arg[1]? arg[1][7] : 0;
  a14=(a13*a6);
  a17=(a16*a7);
  a14=(a14+a17);
  a17=(a15*a4);
  a14=(a14-a17);
  a14=(a12*a14);
  a0=(a0-a14);
  if (res[0]!=0) res[0][7]=a0;
  a0=arg[1]? arg[1][8] : 0;
  a14=(a15*a6);
  a17=(a16*a3);
  a14=(a14-a17);
  a17=(a13*a4);
  a14=(a14+a17);
  a14=(a12*a14);
  a0=(a0-a14);
  if (res[0]!=0) res[0][8]=a0;
  a0=arg[1]? arg[1][9] : 0;
  a14=(a16*a6);
  a17=(a15*a3);
  a14=(a14+a17);
  a17=(a13*a7);
  a14=(a14-a17);
  a14=(a12*a14);
  a0=(a0-a14);
  if (res[0]!=0) res[0][9]=a0;
  a0=-1.;
  if (res[1]!=0) res[1][0]=a0;
  if (res[1]!=0) res[1][1]=a0;
  if (res[1]!=0) res[1][2]=a0;
  a0=(a2*a7);
  a0=(a8*a0);
  a0=(a1*a0);
  a0=(-a0);
  if (res[1]!=0) res[1][3]=a0;
  a0=(a2*a3);
  a0=(a8*a0);
  a0=(a1*a0);
  if (res[1]!=0) res[1][4]=a0;
  a0=(a12*a13);
  a0=(-a0);
  if (res[1]!=0) res[1][5]=a0;
  a0=(a12*a15);
  a0=(-a0);
  if (res[1]!=0) res[1][6]=a0;
  a0=(a12*a16);
  a0=(-a0);
  if (res[1]!=0) res[1][7]=a0;
  a0=(a2*a4);
  a0=(a8*a0);
  a0=(a1*a0);
  a0=(-a0);
  if (res[1]!=0) res[1][8]=a0;
  a0=(a2*a6);
  a0=(a8*a0);
  a0=(a1*a0);
  if (res[1]!=0) res[1][9]=a0;
  a0=(a3+a3);
  a0=(a2*a0);
  a0=(a8*a0);
  a0=(a1*a0);
  if (res[1]!=0) res[1][10]=a0;
  a0=(a12*a13);
  if (res[1]!=0) res[1][11]=a0;
  a0=(a12*a16);
  if (res[1]!=0) res[1][12]=a0;
  a0=(a12*a15);
  a0=(-a0);
  if (res[1]!=0) res[1][13]=a0;
  a0=(a2*a6);
  a0=(a8*a0);
  a0=(a1*a0);
  a0=(-a0);
  if (res[1]!=0) res[1][14]=a0;
  a0=(a2*a4);
  a0=(a8*a0);
  a0=(a1*a0);
  a0=(-a0);
  if (res[1]!=0) res[1][15]=a0;
  a0=(a7+a7);
  a0=(a2*a0);
  a0=(a8*a0);
  a0=(a1*a0);
  if (res[1]!=0) res[1][16]=a0;
  a0=(a12*a15);
  if (res[1]!=0) res[1][17]=a0;
  a0=(a12*a16);
  a0=(-a0);
  if (res[1]!=0) res[1][18]=a0;
  a0=(a12*a13);
  if (res[1]!=0) res[1][19]=a0;
  a0=(a2*a3);
  a0=(a8*a0);
  a0=(a1*a0);
  a0=(-a0);
  if (res[1]!=0) res[1][20]=a0;
  a2=(a2*a7);
  a8=(a8*a2);
  a8=(a1*a8);
  a8=(-a8);
  if (res[1]!=0) res[1][21]=a8;
  a16=(a12*a16);
  if (res[1]!=0) res[1][22]=a16;
  a15=(a12*a15);
  if (res[1]!=0) res[1][23]=a15;
  a13=(a12*a13);
  a13=(-a13);
  if (res[1]!=0) res[1][24]=a13;
  if (res[2]!=0) res[2][0]=a10;
  if (res[2]!=0) res[2][1]=a10;
  if (res[2]!=0) res[2][2]=a10;
  if (res[2]!=0) res[2][3]=a10;
  if (res[2]!=0) res[2][4]=a10;
  if (res[2]!=0) res[2][5]=a10;
  if (res[2]!=0) res[2][6]=a10;
  if (res[2]!=0) res[2][7]=a10;
  if (res[2]!=0) res[2][8]=a10;
  if (res[2]!=0) res[2][9]=a10;
  a5=(a1*a5);
  a5=(-a5);
  if (res[3]!=0) res[3][0]=a5;
  a9=(a1*a9);
  a9=(-a9);
  if (res[3]!=0) res[3][1]=a9;
  a1=(a1*a11);
  a1=(-a1);
  if (res[3]!=0) res[3][2]=a1;
  a1=(a12*a3);
  if (res[3]!=0) res[3][3]=a1;
  a1=(a12*a6);
  a1=(-a1);
  if (res[3]!=0) res[3][4]=a1;
  a1=(a12*a4);
  a1=(-a1);
  if (res[3]!=0) res[3][5]=a1;
  a1=(a12*a7);
  if (res[3]!=0) res[3][6]=a1;
  a1=(a12*a7);
  if (res[3]!=0) res[3][7]=a1;
  a1=(a12*a4);
  if (res[3]!=0) res[3][8]=a1;
  a1=(a12*a6);
  a1=(-a1);
  if (res[3]!=0) res[3][9]=a1;
  a1=(a12*a3);
  a1=(-a1);
  if (res[3]!=0) res[3][10]=a1;
  a4=(a12*a4);
  if (res[3]!=0) res[3][11]=a4;
  a7=(a12*a7);
  a7=(-a7);
  if (res[3]!=0) res[3][12]=a7;
  a3=(a12*a3);
  if (res[3]!=0) res[3][13]=a3;
  a12=(a12*a6);
  a12=(-a12);
  if (res[3]!=0) res[3][14]=a12;
  return 0;
}

CASADI_SYMBOL_EXPORT int ACADOS_model_impl_dae_fun_jac_x_xdot_u(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int ACADOS_model_impl_dae_fun_jac_x_xdot_u_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int ACADOS_model_impl_dae_fun_jac_x_xdot_u_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ACADOS_model_impl_dae_fun_jac_x_xdot_u_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int ACADOS_model_impl_dae_fun_jac_x_xdot_u_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ACADOS_model_impl_dae_fun_jac_x_xdot_u_release(int mem) {
}

CASADI_SYMBOL_EXPORT void ACADOS_model_impl_dae_fun_jac_x_xdot_u_incref(void) {
}

CASADI_SYMBOL_EXPORT void ACADOS_model_impl_dae_fun_jac_x_xdot_u_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int ACADOS_model_impl_dae_fun_jac_x_xdot_u_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int ACADOS_model_impl_dae_fun_jac_x_xdot_u_n_out(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_real ACADOS_model_impl_dae_fun_jac_x_xdot_u_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ACADOS_model_impl_dae_fun_jac_x_xdot_u_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ACADOS_model_impl_dae_fun_jac_x_xdot_u_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ACADOS_model_impl_dae_fun_jac_x_xdot_u_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s2;
    case 5: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ACADOS_model_impl_dae_fun_jac_x_xdot_u_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s4;
    case 2: return casadi_s5;
    case 3: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int ACADOS_model_impl_dae_fun_jac_x_xdot_u_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
