/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) ACADOS_model_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s2[21] = {17, 1, 0, 17, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16};

/* ACADOS_model_expl_vde_adj:(i0[13],i1[13],i2[4],i3[17])->(o0[17]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a3, a4, a5, a6, a7, a8, a9;
  a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  if (res[0]!=0) res[0][2]=a0;
  a0=arg[1]? arg[1][0] : 0;
  if (res[0]!=0) res[0][3]=a0;
  a0=arg[1]? arg[1][1] : 0;
  if (res[0]!=0) res[0][4]=a0;
  a0=arg[1]? arg[1][2] : 0;
  if (res[0]!=0) res[0][5]=a0;
  a0=arg[0]? arg[0][12] : 0;
  a1=5.0000000000000000e-01;
  a2=arg[1]? arg[1][9] : 0;
  a2=(a1*a2);
  a3=(a0*a2);
  a4=arg[0]? arg[0][11] : 0;
  a5=arg[1]? arg[1][8] : 0;
  a5=(a1*a5);
  a6=(a4*a5);
  a3=(a3+a6);
  a6=arg[0]? arg[0][10] : 0;
  a7=arg[1]? arg[1][7] : 0;
  a7=(a1*a7);
  a8=(a6*a7);
  a3=(a3+a8);
  a8=arg[0]? arg[0][7] : 0;
  a9=2.;
  a10=arg[2]? arg[2][0] : 0;
  a11=arg[2]? arg[2][1] : 0;
  a10=(a10+a11);
  a11=arg[2]? arg[2][2] : 0;
  a10=(a10+a11);
  a11=arg[2]? arg[2][3] : 0;
  a10=(a10+a11);
  a11=4.8780487804878048e+00;
  a12=arg[1]? arg[1][4] : 0;
  a12=(a11*a12);
  a13=(a10*a12);
  a13=(a9*a13);
  a14=(a8*a13);
  a3=(a3-a14);
  a14=arg[0]? arg[0][8] : 0;
  a15=arg[1]? arg[1][3] : 0;
  a15=(a11*a15);
  a16=(a10*a15);
  a16=(a9*a16);
  a17=(a14*a16);
  a3=(a3+a17);
  if (res[0]!=0) res[0][6]=a3;
  a3=(a4*a2);
  a17=(a0*a5);
  a3=(a3-a17);
  a17=arg[1]? arg[1][6] : 0;
  a17=(a1*a17);
  a18=(a6*a17);
  a3=(a3-a18);
  a18=(a8+a8);
  a19=arg[1]? arg[1][5] : 0;
  a11=(a11*a19);
  a10=(a10*a11);
  a10=(a9*a10);
  a18=(a18*a10);
  a3=(a3-a18);
  a18=arg[0]? arg[0][6] : 0;
  a19=(a18*a13);
  a3=(a3-a19);
  a19=arg[0]? arg[0][9] : 0;
  a20=(a19*a16);
  a3=(a3+a20);
  if (res[0]!=0) res[0][7]=a3;
  a3=(a0*a7);
  a20=(a6*a2);
  a3=(a3-a20);
  a20=(a4*a17);
  a3=(a3-a20);
  a20=(a14+a14);
  a20=(a20*a10);
  a3=(a3-a20);
  a20=(a19*a13);
  a3=(a3+a20);
  a20=(a18*a16);
  a3=(a3+a20);
  if (res[0]!=0) res[0][8]=a3;
  a3=(a6*a5);
  a20=(a4*a7);
  a3=(a3-a20);
  a20=(a0*a17);
  a3=(a3-a20);
  a13=(a14*a13);
  a3=(a3+a13);
  a16=(a8*a16);
  a3=(a3+a16);
  if (res[0]!=0) res[0][9]=a3;
  a3=3.9199999999999999e-04;
  a16=(a3*a4);
  a13=1.5649452269170579e+03;
  a20=arg[1]? arg[1][12] : 0;
  a13=(a13*a20);
  a16=(a16*a13);
  a20=4.0499999999999998e-04;
  a10=(a4*a13);
  a10=(a20*a10);
  a16=(a16-a10);
  a10=6.3900000000000003e-04;
  a21=2.4691358024691358e+03;
  a22=arg[1]? arg[1][11] : 0;
  a21=(a21*a22);
  a22=(a0*a21);
  a22=(a10*a22);
  a16=(a16+a22);
  a22=(a3*a0);
  a22=(a22*a21);
  a16=(a16-a22);
  a22=(a14*a2);
  a16=(a16-a22);
  a22=(a19*a5);
  a16=(a16+a22);
  a22=(a18*a7);
  a16=(a16+a22);
  a22=(a8*a17);
  a16=(a16-a22);
  if (res[0]!=0) res[0][10]=a16;
  a16=(a6*a13);
  a16=(a3*a16);
  a22=(a20*a6);
  a22=(a22*a13);
  a16=(a16-a22);
  a22=(a20*a0);
  a23=2.5510204081632655e+03;
  a24=arg[1]? arg[1][10] : 0;
  a23=(a23*a24);
  a22=(a22*a23);
  a16=(a16+a22);
  a0=(a0*a23);
  a0=(a10*a0);
  a16=(a16-a0);
  a0=(a8*a2);
  a16=(a16+a0);
  a0=(a18*a5);
  a16=(a16+a0);
  a0=(a19*a7);
  a16=(a16-a0);
  a0=(a14*a17);
  a16=(a16-a0);
  if (res[0]!=0) res[0][11]=a16;
  a16=(a10*a6);
  a16=(a16*a21);
  a6=(a6*a21);
  a3=(a3*a6);
  a16=(a16-a3);
  a3=(a4*a23);
  a20=(a20*a3);
  a16=(a16+a20);
  a10=(a10*a4);
  a10=(a10*a23);
  a16=(a16-a10);
  a2=(a18*a2);
  a16=(a16+a2);
  a5=(a8*a5);
  a16=(a16-a5);
  a7=(a14*a7);
  a16=(a16+a7);
  a17=(a19*a17);
  a16=(a16-a17);
  if (res[0]!=0) res[0][12]=a16;
  a16=2.9265000000000002e-07;
  a16=(a16*a13);
  a13=1.6500000000000001e-01;
  a17=(a1*a21);
  a17=(a13*a17);
  a17=(a16-a17);
  a7=1.;
  a5=casadi_sq(a8);
  a2=casadi_sq(a14);
  a5=(a5+a2);
  a5=(a9*a5);
  a7=(a7-a5);
  a7=(a7*a11);
  a11=(a14*a19);
  a5=(a18*a8);
  a11=(a11-a5);
  a11=(a9*a11);
  a11=(a11*a12);
  a7=(a7+a11);
  a8=(a8*a19);
  a18=(a18*a14);
  a8=(a8+a18);
  a9=(a9*a8);
  a9=(a9*a15);
  a7=(a7+a9);
  a17=(a17+a7);
  if (res[0]!=0) res[0][13]=a17;
  a17=(a1*a23);
  a17=(a13*a17);
  a17=(a16+a17);
  a17=(a7-a17);
  if (res[0]!=0) res[0][14]=a17;
  a21=(a1*a21);
  a21=(a13*a21);
  a21=(a16+a21);
  a21=(a21+a7);
  if (res[0]!=0) res[0][15]=a21;
  a1=(a1*a23);
  a13=(a13*a1);
  a13=(a13-a16);
  a13=(a13+a7);
  if (res[0]!=0) res[0][16]=a13;
  return 0;
}

CASADI_SYMBOL_EXPORT int ACADOS_model_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int ACADOS_model_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int ACADOS_model_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ACADOS_model_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int ACADOS_model_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ACADOS_model_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void ACADOS_model_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void ACADOS_model_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int ACADOS_model_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int ACADOS_model_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real ACADOS_model_expl_vde_adj_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ACADOS_model_expl_vde_adj_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ACADOS_model_expl_vde_adj_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ACADOS_model_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ACADOS_model_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int ACADOS_model_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
