/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) ACADOS_model_impl_dae_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[14] = {10, 1, 0, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[22] = {18, 1, 0, 18, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17};
static const casadi_int casadi_s4[69] = {24, 24, 0, 0, 0, 0, 0, 0, 0, 6, 13, 20, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 30, 34, 38, 42, 7, 8, 20, 21, 22, 23, 6, 7, 9, 20, 21, 22, 23, 6, 8, 9, 20, 21, 22, 23, 7, 8, 20, 21, 22, 23, 6, 7, 8, 9, 6, 7, 8, 9, 6, 7, 8, 9, 6, 7, 8, 9};

/* ACADOS_model_impl_dae_hess:(i0[10],i1[10],i2[4],i3[],i4[10],i5[],i6[18])->(o0[24x24,42nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a3, a4, a5, a6, a7, a8, a9;
  a0=2.;
  a1=arg[2]? arg[2][0] : 0;
  a2=4.0322580645161290e+00;
  a3=arg[4]? arg[4][4] : 0;
  a3=(a2*a3);
  a4=(a1*a3);
  a4=(a0*a4);
  if (res[0]!=0) res[0][0]=a4;
  a5=arg[4]? arg[4][3] : 0;
  a5=(a2*a5);
  a6=(a1*a5);
  a6=(a0*a6);
  a7=(-a6);
  if (res[0]!=0) res[0][1]=a7;
  a8=arg[0]? arg[0][8] : 0;
  a9=(a0*a8);
  a9=(a5*a9);
  a10=arg[0]? arg[0][7] : 0;
  a11=(a0*a10);
  a11=(a3*a11);
  a9=(a9-a11);
  a9=(-a9);
  if (res[0]!=0) res[0][2]=a9;
  a11=5.0000000000000000e-01;
  a12=arg[4]? arg[4][7] : 0;
  a12=(a11*a12);
  a13=(-a12);
  if (res[0]!=0) res[0][3]=a13;
  a14=arg[4]? arg[4][8] : 0;
  a14=(a11*a14);
  a15=(-a14);
  if (res[0]!=0) res[0][4]=a15;
  a16=arg[4]? arg[4][9] : 0;
  a16=(a11*a16);
  a17=(-a16);
  if (res[0]!=0) res[0][5]=a17;
  if (res[0]!=0) res[0][6]=a4;
  a18=arg[4]? arg[4][5] : 0;
  a2=(a2*a18);
  a1=(a1*a2);
  a1=(a0*a1);
  a18=(a0*a1);
  if (res[0]!=0) res[0][7]=a18;
  a6=(-a6);
  if (res[0]!=0) res[0][8]=a6;
  a18=arg[0]? arg[0][9] : 0;
  a19=(a0*a18);
  a19=(a5*a19);
  a20=(a10+a10);
  a20=(a0*a20);
  a20=(a2*a20);
  a21=arg[0]? arg[0][6] : 0;
  a22=(a0*a21);
  a22=(a3*a22);
  a20=(a20+a22);
  a19=(a19-a20);
  a19=(-a19);
  if (res[0]!=0) res[0][9]=a19;
  a20=arg[4]? arg[4][6] : 0;
  a11=(a11*a20);
  if (res[0]!=0) res[0][10]=a11;
  a20=(-a16);
  if (res[0]!=0) res[0][11]=a20;
  if (res[0]!=0) res[0][12]=a14;
  if (res[0]!=0) res[0][13]=a7;
  a1=(a0*a1);
  if (res[0]!=0) res[0][14]=a1;
  a4=(-a4);
  if (res[0]!=0) res[0][15]=a4;
  a18=(a0*a18);
  a18=(a3*a18);
  a1=(a8+a8);
  a1=(a0*a1);
  a2=(a2*a1);
  a18=(a18-a2);
  a21=(a0*a21);
  a21=(a5*a21);
  a18=(a18+a21);
  a18=(-a18);
  if (res[0]!=0) res[0][16]=a18;
  if (res[0]!=0) res[0][17]=a16;
  if (res[0]!=0) res[0][18]=a11;
  a21=(-a12);
  if (res[0]!=0) res[0][19]=a21;
  if (res[0]!=0) res[0][20]=a6;
  if (res[0]!=0) res[0][21]=a4;
  a8=(a0*a8);
  a3=(a3*a8);
  a0=(a0*a10);
  a5=(a5*a0);
  a3=(a3+a5);
  a3=(-a3);
  if (res[0]!=0) res[0][22]=a3;
  a5=(-a14);
  if (res[0]!=0) res[0][23]=a5;
  if (res[0]!=0) res[0][24]=a12;
  if (res[0]!=0) res[0][25]=a11;
  if (res[0]!=0) res[0][26]=a9;
  if (res[0]!=0) res[0][27]=a19;
  if (res[0]!=0) res[0][28]=a18;
  if (res[0]!=0) res[0][29]=a3;
  if (res[0]!=0) res[0][30]=a13;
  if (res[0]!=0) res[0][31]=a11;
  if (res[0]!=0) res[0][32]=a16;
  if (res[0]!=0) res[0][33]=a5;
  if (res[0]!=0) res[0][34]=a15;
  if (res[0]!=0) res[0][35]=a20;
  if (res[0]!=0) res[0][36]=a11;
  if (res[0]!=0) res[0][37]=a12;
  if (res[0]!=0) res[0][38]=a17;
  if (res[0]!=0) res[0][39]=a14;
  if (res[0]!=0) res[0][40]=a21;
  if (res[0]!=0) res[0][41]=a11;
  return 0;
}

CASADI_SYMBOL_EXPORT int ACADOS_model_impl_dae_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int ACADOS_model_impl_dae_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int ACADOS_model_impl_dae_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ACADOS_model_impl_dae_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int ACADOS_model_impl_dae_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ACADOS_model_impl_dae_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void ACADOS_model_impl_dae_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void ACADOS_model_impl_dae_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int ACADOS_model_impl_dae_hess_n_in(void) { return 7;}

CASADI_SYMBOL_EXPORT casadi_int ACADOS_model_impl_dae_hess_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real ACADOS_model_impl_dae_hess_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ACADOS_model_impl_dae_hess_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    case 6: return "i6";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ACADOS_model_impl_dae_hess_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ACADOS_model_impl_dae_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s0;
    case 5: return casadi_s2;
    case 6: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ACADOS_model_impl_dae_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int ACADOS_model_impl_dae_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
