/* This file was automatically generated by CasADi 3.6.5.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) ACADOS_model_cost_ext_cost_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[14] = {10, 1, 0, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[28] = {24, 1, 0, 24, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23};
static const casadi_int casadi_s4[5] = {1, 1, 0, 1, 0};

/* ACADOS_model_cost_ext_cost_fun:(i0[10],i1[4],i2[],i3[24])->(o0) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59, a6, a60, a61, a62, a63, a64, a65, a66, a67, a68, a69, a7, a70, a71, a72, a73, a8, a9;
  a0=30.;
  a1=arg[0]? arg[0][0] : 0;
  a2=arg[3]? arg[3][0] : 0;
  a2=(a1-a2);
  a2=casadi_sq(a2);
  a3=arg[0]? arg[0][1] : 0;
  a4=arg[3]? arg[3][1] : 0;
  a4=(a3-a4);
  a4=casadi_sq(a4);
  a2=(a2+a4);
  a4=arg[0]? arg[0][2] : 0;
  a5=arg[3]? arg[3][2] : 0;
  a5=(a4-a5);
  a5=casadi_sq(a5);
  a2=(a2+a5);
  a0=(a0*a2);
  a2=1.0000000000000000e-02;
  a5=arg[0]? arg[0][3] : 0;
  a6=arg[3]? arg[3][3] : 0;
  a5=(a5-a6);
  a5=casadi_sq(a5);
  a6=arg[0]? arg[0][4] : 0;
  a7=arg[3]? arg[3][4] : 0;
  a6=(a6-a7);
  a6=casadi_sq(a6);
  a5=(a5+a6);
  a6=arg[0]? arg[0][5] : 0;
  a7=arg[3]? arg[3][5] : 0;
  a6=(a6-a7);
  a6=casadi_sq(a6);
  a5=(a5+a6);
  a5=(a2*a5);
  a0=(a0+a5);
  a5=1.;
  a6=2.;
  a7=arg[0]? arg[0][8] : 0;
  a8=casadi_sq(a7);
  a9=arg[0]? arg[0][9] : 0;
  a10=casadi_sq(a9);
  a8=(a8+a10);
  a8=(a6*a8);
  a8=(a5-a8);
  a10=arg[3]? arg[3][8] : 0;
  a11=casadi_sq(a10);
  a12=arg[3]? arg[3][9] : 0;
  a13=casadi_sq(a12);
  a11=(a11+a13);
  a11=(a6*a11);
  a11=(a5-a11);
  a8=(a8-a11);
  a8=casadi_sq(a8);
  a11=arg[0]? arg[0][7] : 0;
  a13=(a11*a7);
  a14=arg[0]? arg[0][6] : 0;
  a15=(a14*a9);
  a13=(a13+a15);
  a13=(a6*a13);
  a15=arg[3]? arg[3][7] : 0;
  a16=(a15*a10);
  a17=arg[3]? arg[3][6] : 0;
  a18=(a17*a12);
  a16=(a16+a18);
  a16=(a6*a16);
  a13=(a13-a16);
  a13=casadi_sq(a13);
  a8=(a8+a13);
  a13=(a11*a9);
  a16=(a14*a7);
  a13=(a13-a16);
  a13=(a6*a13);
  a16=(a15*a12);
  a18=(a17*a10);
  a16=(a16-a18);
  a16=(a6*a16);
  a13=(a13-a16);
  a13=casadi_sq(a13);
  a8=(a8+a13);
  a13=(a11*a7);
  a16=(a14*a9);
  a13=(a13-a16);
  a13=(a6*a13);
  a16=(a15*a10);
  a18=(a17*a12);
  a16=(a16-a18);
  a16=(a6*a16);
  a13=(a13-a16);
  a13=casadi_sq(a13);
  a16=casadi_sq(a11);
  a18=casadi_sq(a9);
  a16=(a16+a18);
  a16=(a6*a16);
  a16=(a5-a16);
  a18=casadi_sq(a15);
  a19=casadi_sq(a12);
  a18=(a18+a19);
  a18=(a6*a18);
  a18=(a5-a18);
  a16=(a16-a18);
  a16=casadi_sq(a16);
  a13=(a13+a16);
  a16=(a7*a9);
  a18=(a14*a11);
  a16=(a16+a18);
  a16=(a6*a16);
  a18=(a10*a12);
  a19=(a17*a15);
  a18=(a18+a19);
  a18=(a6*a18);
  a16=(a16-a18);
  a16=casadi_sq(a16);
  a13=(a13+a16);
  a8=(a8+a13);
  a13=(a11*a9);
  a16=(a14*a7);
  a13=(a13+a16);
  a13=(a6*a13);
  a16=(a15*a12);
  a18=(a17*a10);
  a16=(a16+a18);
  a16=(a6*a16);
  a13=(a13-a16);
  a13=casadi_sq(a13);
  a16=(a7*a9);
  a18=(a14*a11);
  a16=(a16-a18);
  a16=(a6*a16);
  a12=(a10*a12);
  a17=(a17*a15);
  a12=(a12-a17);
  a12=(a6*a12);
  a16=(a16-a12);
  a16=casadi_sq(a16);
  a13=(a13+a16);
  a16=casadi_sq(a11);
  a12=casadi_sq(a7);
  a16=(a16+a12);
  a16=(a6*a16);
  a16=(a5-a16);
  a15=casadi_sq(a15);
  a10=casadi_sq(a10);
  a15=(a15+a10);
  a15=(a6*a15);
  a15=(a5-a15);
  a16=(a16-a15);
  a16=casadi_sq(a16);
  a13=(a13+a16);
  a8=(a8+a13);
  a2=(a2*a8);
  a0=(a0+a2);
  a2=100.;
  a8=-10.;
  a13=arg[3]? arg[3][23] : 0;
  a16=arg[3]? arg[3][22] : 0;
  a13=(a13-a16);
  a13=casadi_sq(a13);
  a8=(a8*a13);
  a8=exp(a8);
  a2=(a2*a8);
  a8=5.;
  a13=arg[3]? arg[3][10] : 0;
  a1=(a1-a13);
  a1=casadi_sq(a1);
  a13=arg[3]? arg[3][11] : 0;
  a3=(a3-a13);
  a3=casadi_sq(a3);
  a1=(a1+a3);
  a3=arg[3]? arg[3][12] : 0;
  a4=(a4-a3);
  a4=casadi_sq(a4);
  a1=(a1+a4);
  a1=(a8*a1);
  a4=10.;
  a3=arg[3]? arg[3][13] : 0;
  a13=casadi_sq(a3);
  a16=arg[3]? arg[3][14] : 0;
  a15=casadi_sq(a16);
  a13=(a13+a15);
  a15=arg[3]? arg[3][15] : 0;
  a10=casadi_sq(a15);
  a13=(a13+a10);
  a10=casadi_sq(a13);
  a12=arg[3]? arg[3][16] : 0;
  a17=(a12*a3);
  a18=arg[3]? arg[3][17] : 0;
  a19=(a18*a16);
  a17=(a17+a19);
  a19=arg[3]? arg[3][18] : 0;
  a20=(a19*a15);
  a17=(a17+a20);
  a20=casadi_sq(a17);
  a10=(a10+a20);
  a20=arg[3]? arg[3][19] : 0;
  a21=(a20*a3);
  a22=arg[3]? arg[3][20] : 0;
  a23=(a22*a16);
  a21=(a21+a23);
  a23=arg[3]? arg[3][21] : 0;
  a24=(a23*a15);
  a21=(a21+a24);
  a24=casadi_sq(a21);
  a10=(a10+a24);
  a10=sqrt(a10);
  a24=(a13/a10);
  a25=(a3*a12);
  a26=(a16*a18);
  a25=(a25+a26);
  a26=(a15*a19);
  a25=(a25+a26);
  a26=(a25*a24);
  a27=casadi_sq(a12);
  a28=casadi_sq(a18);
  a27=(a27+a28);
  a28=casadi_sq(a19);
  a27=(a27+a28);
  a17=(a17/a10);
  a28=(a27*a17);
  a26=(a26+a28);
  a28=(a20*a12);
  a29=(a22*a18);
  a28=(a28+a29);
  a29=(a23*a19);
  a28=(a28+a29);
  a21=(a21/a10);
  a29=(a28*a21);
  a26=(a26+a29);
  a29=(a26*a17);
  a13=(a13+a29);
  a29=(a3*a20);
  a30=(a16*a22);
  a29=(a29+a30);
  a30=(a15*a23);
  a29=(a29+a30);
  a30=(a29*a24);
  a31=(a12*a20);
  a32=(a18*a22);
  a31=(a31+a32);
  a32=(a19*a23);
  a31=(a31+a32);
  a32=(a31*a17);
  a30=(a30+a32);
  a32=casadi_sq(a20);
  a33=casadi_sq(a22);
  a32=(a32+a33);
  a33=casadi_sq(a23);
  a32=(a32+a33);
  a33=(a32*a21);
  a30=(a30+a33);
  a33=(a30*a21);
  a13=(a13+a33);
  a33=casadi_sq(a13);
  a34=(a26*a24);
  a25=(a25-a34);
  a34=casadi_sq(a25);
  a35=(a26*a17);
  a27=(a27-a35);
  a35=casadi_sq(a27);
  a34=(a34+a35);
  a35=(a26*a21);
  a28=(a28-a35);
  a35=casadi_sq(a28);
  a34=(a34+a35);
  a34=sqrt(a34);
  a35=(a34*a17);
  a36=(a30*a24);
  a29=(a29-a36);
  a25=(a25/a34);
  a36=(a29*a25);
  a37=(a30*a17);
  a31=(a31-a37);
  a37=(a27/a34);
  a38=(a31*a37);
  a36=(a36+a38);
  a38=(a30*a21);
  a32=(a32-a38);
  a28=(a28/a34);
  a38=(a32*a28);
  a36=(a36+a38);
  a38=(a36*a21);
  a35=(a35+a38);
  a38=casadi_sq(a35);
  a33=(a33+a38);
  a38=(a36*a25);
  a29=(a29-a38);
  a38=casadi_sq(a29);
  a39=(a36*a37);
  a31=(a31-a39);
  a39=casadi_sq(a31);
  a38=(a38+a39);
  a39=(a36*a28);
  a32=(a32-a39);
  a39=casadi_sq(a32);
  a38=(a38+a39);
  a38=sqrt(a38);
  a39=(a38*a21);
  a40=casadi_sq(a39);
  a33=(a33+a40);
  a33=sqrt(a33);
  a40=(a13/a33);
  a41=(a24*a40);
  a35=(a35/a33);
  a42=(a25*a35);
  a41=(a41+a42);
  a29=(a29/a38);
  a39=(a39/a33);
  a42=(a29*a39);
  a41=(a41+a42);
  a42=(a10*a25);
  a43=(a26*a37);
  a42=(a42+a43);
  a43=(a30*a28);
  a42=(a42+a43);
  a43=(a42*a40);
  a44=(a36*a28);
  a27=(a27+a44);
  a44=(a27*a35);
  a43=(a43+a44);
  a44=(a38*a28);
  a45=(a44*a39);
  a43=(a43+a45);
  a45=(a43*a35);
  a13=(a13+a45);
  a10=(a10*a29);
  a31=(a31/a38);
  a26=(a26*a31);
  a10=(a10+a26);
  a38=(a32/a38);
  a30=(a30*a38);
  a10=(a10+a30);
  a30=(a10*a40);
  a34=(a34*a31);
  a36=(a36*a38);
  a34=(a34+a36);
  a36=(a34*a35);
  a30=(a30+a36);
  a36=(a32*a39);
  a30=(a30+a36);
  a36=(a30*a39);
  a13=(a13+a36);
  a36=casadi_sq(a13);
  a26=(a43*a40);
  a42=(a42-a26);
  a26=casadi_sq(a42);
  a45=(a43*a35);
  a27=(a27-a45);
  a45=casadi_sq(a27);
  a26=(a26+a45);
  a45=(a43*a39);
  a44=(a44-a45);
  a45=casadi_sq(a44);
  a26=(a26+a45);
  a26=sqrt(a26);
  a45=(a26*a35);
  a46=(a30*a40);
  a10=(a10-a46);
  a42=(a42/a26);
  a46=(a10*a42);
  a47=(a30*a35);
  a34=(a34-a47);
  a47=(a27/a26);
  a48=(a34*a47);
  a46=(a46+a48);
  a48=(a30*a39);
  a32=(a32-a48);
  a44=(a44/a26);
  a48=(a32*a44);
  a46=(a46+a48);
  a48=(a46*a39);
  a45=(a45+a48);
  a48=casadi_sq(a45);
  a36=(a36+a48);
  a48=(a46*a42);
  a10=(a10-a48);
  a48=casadi_sq(a10);
  a49=(a46*a47);
  a34=(a34-a49);
  a49=casadi_sq(a34);
  a48=(a48+a49);
  a49=(a46*a44);
  a32=(a32-a49);
  a49=casadi_sq(a32);
  a48=(a48+a49);
  a48=sqrt(a48);
  a49=(a48*a39);
  a50=casadi_sq(a49);
  a36=(a36+a50);
  a36=sqrt(a36);
  a50=(a13/a36);
  a51=(a41*a50);
  a52=(a24*a42);
  a53=(a25*a47);
  a52=(a52+a53);
  a53=(a29*a44);
  a52=(a52+a53);
  a45=(a45/a36);
  a53=(a52*a45);
  a51=(a51+a53);
  a10=(a10/a48);
  a24=(a24*a10);
  a34=(a34/a48);
  a25=(a25*a34);
  a24=(a24+a25);
  a25=(a32/a48);
  a29=(a29*a25);
  a24=(a24+a29);
  a49=(a49/a36);
  a29=(a24*a49);
  a51=(a51+a29);
  a29=(a33*a42);
  a53=(a43*a47);
  a29=(a29+a53);
  a53=(a30*a44);
  a29=(a29+a53);
  a53=(a29*a50);
  a54=(a46*a44);
  a27=(a27+a54);
  a54=(a27*a45);
  a53=(a53+a54);
  a48=(a48*a44);
  a54=(a48*a49);
  a53=(a53+a54);
  a54=(a53*a45);
  a13=(a13+a54);
  a33=(a33*a10);
  a43=(a43*a34);
  a33=(a33+a43);
  a30=(a30*a25);
  a33=(a33+a30);
  a30=(a33*a50);
  a26=(a26*a34);
  a46=(a46*a25);
  a26=(a26+a46);
  a46=(a26*a45);
  a30=(a30+a46);
  a46=(a32*a49);
  a30=(a30+a46);
  a46=(a30*a49);
  a13=(a13+a46);
  a46=casadi_sq(a13);
  a43=(a53*a50);
  a29=(a29-a43);
  a43=casadi_sq(a29);
  a54=(a53*a45);
  a27=(a27-a54);
  a54=casadi_sq(a27);
  a43=(a43+a54);
  a54=(a53*a49);
  a48=(a48-a54);
  a54=casadi_sq(a48);
  a43=(a43+a54);
  a43=sqrt(a43);
  a54=(a43*a45);
  a55=(a30*a50);
  a33=(a33-a55);
  a29=(a29/a43);
  a55=(a33*a29);
  a56=(a30*a45);
  a26=(a26-a56);
  a56=(a27/a43);
  a57=(a26*a56);
  a55=(a55+a57);
  a57=(a30*a49);
  a32=(a32-a57);
  a48=(a48/a43);
  a57=(a32*a48);
  a55=(a55+a57);
  a57=(a55*a49);
  a54=(a54+a57);
  a57=casadi_sq(a54);
  a46=(a46+a57);
  a57=(a55*a29);
  a33=(a33-a57);
  a57=casadi_sq(a33);
  a58=(a55*a56);
  a26=(a26-a58);
  a58=casadi_sq(a26);
  a57=(a57+a58);
  a58=(a55*a48);
  a32=(a32-a58);
  a58=casadi_sq(a32);
  a57=(a57+a58);
  a57=sqrt(a57);
  a58=(a57*a49);
  a59=casadi_sq(a58);
  a46=(a46+a59);
  a46=sqrt(a46);
  a59=(a13/a46);
  a60=(a51*a59);
  a61=(a41*a29);
  a62=(a52*a56);
  a61=(a61+a62);
  a62=(a24*a48);
  a61=(a61+a62);
  a54=(a54/a46);
  a62=(a61*a54);
  a60=(a60+a62);
  a33=(a33/a57);
  a41=(a41*a33);
  a26=(a26/a57);
  a52=(a52*a26);
  a41=(a41+a52);
  a52=(a32/a57);
  a24=(a24*a52);
  a41=(a41+a24);
  a58=(a58/a46);
  a24=(a41*a58);
  a60=(a60+a24);
  a24=(a36*a29);
  a62=(a53*a56);
  a24=(a24+a62);
  a62=(a30*a48);
  a24=(a24+a62);
  a62=(a24*a59);
  a63=(a55*a48);
  a27=(a27+a63);
  a63=(a27*a54);
  a62=(a62+a63);
  a57=(a57*a48);
  a63=(a57*a58);
  a62=(a62+a63);
  a63=(a62*a54);
  a13=(a13+a63);
  a36=(a36*a33);
  a53=(a53*a26);
  a36=(a36+a53);
  a30=(a30*a52);
  a36=(a36+a30);
  a30=(a36*a59);
  a43=(a43*a26);
  a55=(a55*a52);
  a43=(a43+a55);
  a55=(a43*a54);
  a30=(a30+a55);
  a55=(a32*a58);
  a30=(a30+a55);
  a55=(a30*a58);
  a13=(a13+a55);
  a55=casadi_sq(a13);
  a53=(a62*a59);
  a24=(a24-a53);
  a53=casadi_sq(a24);
  a63=(a62*a54);
  a27=(a27-a63);
  a63=casadi_sq(a27);
  a53=(a53+a63);
  a63=(a62*a58);
  a57=(a57-a63);
  a63=casadi_sq(a57);
  a53=(a53+a63);
  a53=sqrt(a53);
  a63=(a53*a54);
  a64=(a30*a59);
  a36=(a36-a64);
  a24=(a24/a53);
  a64=(a36*a24);
  a65=(a30*a54);
  a43=(a43-a65);
  a65=(a27/a53);
  a66=(a43*a65);
  a64=(a64+a66);
  a66=(a30*a58);
  a32=(a32-a66);
  a57=(a57/a53);
  a66=(a32*a57);
  a64=(a64+a66);
  a66=(a64*a58);
  a63=(a63+a66);
  a66=casadi_sq(a63);
  a55=(a55+a66);
  a66=(a64*a24);
  a36=(a36-a66);
  a66=casadi_sq(a36);
  a67=(a64*a65);
  a43=(a43-a67);
  a67=casadi_sq(a43);
  a66=(a66+a67);
  a67=(a64*a57);
  a32=(a32-a67);
  a67=casadi_sq(a32);
  a66=(a66+a67);
  a66=sqrt(a66);
  a67=(a66*a58);
  a68=casadi_sq(a67);
  a55=(a55+a68);
  a55=sqrt(a55);
  a68=(a13/a55);
  a69=(a60*a68);
  a70=(a51*a24);
  a71=(a61*a65);
  a70=(a70+a71);
  a71=(a41*a57);
  a70=(a70+a71);
  a63=(a63/a55);
  a71=(a70*a63);
  a69=(a69+a71);
  a36=(a36/a66);
  a51=(a51*a36);
  a43=(a43/a66);
  a61=(a61*a43);
  a51=(a51+a61);
  a61=(a32/a66);
  a41=(a41*a61);
  a51=(a51+a41);
  a67=(a67/a55);
  a55=(a51*a67);
  a69=(a69+a55);
  a55=(a3*a69);
  a41=(a17*a40);
  a71=(a37*a35);
  a41=(a41+a71);
  a71=(a31*a39);
  a41=(a41+a71);
  a71=(a41*a50);
  a72=(a17*a42);
  a73=(a37*a47);
  a72=(a72+a73);
  a73=(a31*a44);
  a72=(a72+a73);
  a73=(a72*a45);
  a71=(a71+a73);
  a17=(a17*a10);
  a37=(a37*a34);
  a17=(a17+a37);
  a31=(a31*a25);
  a17=(a17+a31);
  a31=(a17*a49);
  a71=(a71+a31);
  a31=(a71*a59);
  a37=(a41*a29);
  a73=(a72*a56);
  a37=(a37+a73);
  a73=(a17*a48);
  a37=(a37+a73);
  a73=(a37*a54);
  a31=(a31+a73);
  a41=(a41*a33);
  a72=(a72*a26);
  a41=(a41+a72);
  a17=(a17*a52);
  a41=(a41+a17);
  a17=(a41*a58);
  a31=(a31+a17);
  a17=(a31*a68);
  a72=(a71*a24);
  a73=(a37*a65);
  a72=(a72+a73);
  a73=(a41*a57);
  a72=(a72+a73);
  a73=(a72*a63);
  a17=(a17+a73);
  a71=(a71*a36);
  a37=(a37*a43);
  a71=(a71+a37);
  a41=(a41*a61);
  a71=(a71+a41);
  a41=(a71*a67);
  a17=(a17+a41);
  a41=(a12*a17);
  a55=(a55+a41);
  a40=(a21*a40);
  a35=(a28*a35);
  a40=(a40+a35);
  a39=(a38*a39);
  a40=(a40+a39);
  a50=(a40*a50);
  a42=(a21*a42);
  a47=(a28*a47);
  a42=(a42+a47);
  a44=(a38*a44);
  a42=(a42+a44);
  a45=(a42*a45);
  a50=(a50+a45);
  a21=(a21*a10);
  a28=(a28*a34);
  a21=(a21+a28);
  a38=(a38*a25);
  a21=(a21+a38);
  a49=(a21*a49);
  a50=(a50+a49);
  a59=(a50*a59);
  a29=(a40*a29);
  a56=(a42*a56);
  a29=(a29+a56);
  a48=(a21*a48);
  a29=(a29+a48);
  a54=(a29*a54);
  a59=(a59+a54);
  a40=(a40*a33);
  a42=(a42*a26);
  a40=(a40+a42);
  a21=(a21*a52);
  a40=(a40+a21);
  a58=(a40*a58);
  a59=(a59+a58);
  a58=(a59*a68);
  a21=(a50*a24);
  a52=(a29*a65);
  a21=(a21+a52);
  a52=(a40*a57);
  a21=(a21+a52);
  a52=(a21*a63);
  a58=(a58+a52);
  a50=(a50*a36);
  a29=(a29*a43);
  a50=(a50+a29);
  a40=(a40*a61);
  a50=(a50+a40);
  a40=(a50*a67);
  a58=(a58+a40);
  a40=(a20*a58);
  a55=(a55+a40);
  a24=(a46*a24);
  a65=(a62*a65);
  a24=(a24+a65);
  a65=(a30*a57);
  a24=(a24+a65);
  a65=(a24*a68);
  a40=(a64*a57);
  a27=(a27+a40);
  a40=(a27*a63);
  a65=(a65+a40);
  a66=(a66*a57);
  a57=(a66*a67);
  a65=(a65+a57);
  a57=(a65*a63);
  a13=(a13+a57);
  a46=(a46*a36);
  a62=(a62*a43);
  a46=(a46+a62);
  a30=(a30*a61);
  a46=(a46+a30);
  a30=(a46*a68);
  a53=(a53*a43);
  a64=(a64*a61);
  a53=(a53+a64);
  a64=(a53*a63);
  a30=(a30+a64);
  a64=(a32*a67);
  a30=(a30+a64);
  a64=(a30*a67);
  a13=(a13+a64);
  a13=sqrt(a13);
  a55=(a55/a13);
  a64=(a55*a69);
  a61=(a65*a68);
  a24=(a24-a61);
  a61=casadi_sq(a24);
  a43=(a65*a63);
  a27=(a27-a43);
  a43=casadi_sq(a27);
  a61=(a61+a43);
  a65=(a65*a67);
  a66=(a66-a65);
  a65=casadi_sq(a66);
  a61=(a61+a65);
  a61=sqrt(a61);
  a24=(a24/a61);
  a65=(a60*a24);
  a43=(a27/a61);
  a62=(a70*a43);
  a65=(a65+a62);
  a66=(a66/a61);
  a61=(a51*a66);
  a65=(a65+a61);
  a61=(a3*a65);
  a62=(a31*a24);
  a36=(a72*a43);
  a62=(a62+a36);
  a36=(a71*a66);
  a62=(a62+a36);
  a36=(a12*a62);
  a61=(a61+a36);
  a36=(a59*a24);
  a57=(a21*a43);
  a36=(a36+a57);
  a57=(a50*a66);
  a36=(a36+a57);
  a57=(a20*a36);
  a61=(a61+a57);
  a68=(a30*a68);
  a46=(a46-a68);
  a68=(a46*a24);
  a63=(a30*a63);
  a53=(a53-a63);
  a63=(a53*a43);
  a68=(a68+a63);
  a30=(a30*a67);
  a32=(a32-a30);
  a30=(a32*a66);
  a68=(a68+a30);
  a30=(a68*a66);
  a27=(a27+a30);
  a27=sqrt(a27);
  a61=(a61/a27);
  a30=(a61*a65);
  a64=(a64+a30);
  a24=(a68*a24);
  a46=(a46-a24);
  a24=casadi_sq(a46);
  a43=(a68*a43);
  a53=(a53-a43);
  a43=casadi_sq(a53);
  a24=(a24+a43);
  a68=(a68*a66);
  a32=(a32-a68);
  a68=casadi_sq(a32);
  a24=(a24+a68);
  a24=sqrt(a24);
  a46=(a46/a24);
  a60=(a60*a46);
  a53=(a53/a24);
  a70=(a70*a53);
  a60=(a60+a70);
  a24=(a32/a24);
  a51=(a51*a24);
  a60=(a60+a51);
  a3=(a3*a60);
  a31=(a31*a46);
  a72=(a72*a53);
  a31=(a31+a72);
  a71=(a71*a24);
  a31=(a31+a71);
  a12=(a12*a31);
  a3=(a3+a12);
  a59=(a59*a46);
  a21=(a21*a53);
  a59=(a59+a21);
  a50=(a50*a24);
  a59=(a59+a50);
  a20=(a20*a59);
  a3=(a3+a20);
  a32=sqrt(a32);
  a3=(a3/a32);
  a20=(a55*a69);
  a50=(a61*a65);
  a20=(a20+a50);
  a50=(a3*a60);
  a20=(a20+a50);
  a50=(a16*a69);
  a24=(a18*a17);
  a50=(a50+a24);
  a24=(a22*a58);
  a50=(a50+a24);
  a50=(a50/a13);
  a24=(a50*a17);
  a21=(a16*a65);
  a53=(a18*a62);
  a21=(a21+a53);
  a53=(a22*a36);
  a21=(a21+a53);
  a21=(a21/a27);
  a53=(a21*a62);
  a24=(a24+a53);
  a16=(a16*a60);
  a18=(a18*a31);
  a16=(a16+a18);
  a22=(a22*a59);
  a16=(a16+a22);
  a16=(a16/a32);
  a22=(a16*a31);
  a24=(a24+a22);
  a22=(a15*a69);
  a18=(a19*a17);
  a22=(a22+a18);
  a18=(a23*a58);
  a22=(a22+a18);
  a22=(a22/a13);
  a13=(a22*a58);
  a18=(a15*a65);
  a53=(a19*a62);
  a18=(a18+a53);
  a53=(a23*a36);
  a18=(a18+a53);
  a18=(a18/a27);
  a27=(a18*a36);
  a13=(a13+a27);
  a15=(a15*a60);
  a19=(a19*a31);
  a15=(a15+a19);
  a23=(a23*a59);
  a15=(a15+a23);
  a15=(a15/a32);
  a32=(a15*a59);
  a13=(a13+a32);
  a32=(a24*a13);
  a23=(a50*a58);
  a19=(a21*a36);
  a23=(a23+a19);
  a19=(a16*a59);
  a23=(a23+a19);
  a19=(a22*a17);
  a27=(a18*a62);
  a19=(a19+a27);
  a27=(a15*a31);
  a19=(a19+a27);
  a27=(a23*a19);
  a32=(a32-a27);
  a20=(a20*a32);
  a32=(a55*a17);
  a27=(a61*a62);
  a32=(a32+a27);
  a27=(a3*a31);
  a32=(a32+a27);
  a27=(a50*a69);
  a53=(a21*a65);
  a27=(a27+a53);
  a53=(a16*a60);
  a27=(a27+a53);
  a13=(a27*a13);
  a53=(a22*a69);
  a46=(a18*a65);
  a53=(a53+a46);
  a46=(a15*a60);
  a53=(a53+a46);
  a23=(a23*a53);
  a13=(a13-a23);
  a32=(a32*a13);
  a20=(a20-a32);
  a32=(a55*a58);
  a13=(a61*a36);
  a32=(a32+a13);
  a13=(a3*a59);
  a32=(a32+a13);
  a27=(a27*a19);
  a24=(a24*a53);
  a27=(a27-a24);
  a32=(a32*a27);
  a20=(a20+a32);
  a3=(a3*a20);
  a32=(a3*a60);
  a64=(a64+a32);
  a32=casadi_sq(a7);
  a27=casadi_sq(a9);
  a32=(a32+a27);
  a32=(a6*a32);
  a32=(a5-a32);
  a64=(a64-a32);
  a64=casadi_sq(a64);
  a32=(a50*a69);
  a27=(a21*a65);
  a32=(a32+a27);
  a16=(a16*a20);
  a27=(a16*a60);
  a32=(a32+a27);
  a27=(a11*a7);
  a24=(a14*a9);
  a27=(a27-a24);
  a27=(a6*a27);
  a32=(a32-a27);
  a32=casadi_sq(a32);
  a64=(a64+a32);
  a69=(a22*a69);
  a65=(a18*a65);
  a69=(a69+a65);
  a15=(a15*a20);
  a60=(a15*a60);
  a69=(a69+a60);
  a60=(a11*a9);
  a20=(a14*a7);
  a60=(a60+a20);
  a60=(a6*a60);
  a69=(a69-a60);
  a69=casadi_sq(a69);
  a64=(a64+a69);
  a69=(a55*a17);
  a60=(a61*a62);
  a69=(a69+a60);
  a60=(a3*a31);
  a69=(a69+a60);
  a60=(a11*a7);
  a20=(a14*a9);
  a60=(a60+a20);
  a60=(a6*a60);
  a69=(a69-a60);
  a69=casadi_sq(a69);
  a64=(a64+a69);
  a69=(a50*a17);
  a60=(a21*a62);
  a69=(a69+a60);
  a60=(a16*a31);
  a69=(a69+a60);
  a60=casadi_sq(a11);
  a20=casadi_sq(a9);
  a60=(a60+a20);
  a60=(a6*a60);
  a60=(a5-a60);
  a69=(a69-a60);
  a69=casadi_sq(a69);
  a64=(a64+a69);
  a17=(a22*a17);
  a62=(a18*a62);
  a17=(a17+a62);
  a31=(a15*a31);
  a17=(a17+a31);
  a31=(a7*a9);
  a62=(a14*a11);
  a31=(a31-a62);
  a31=(a6*a31);
  a17=(a17-a31);
  a17=casadi_sq(a17);
  a64=(a64+a17);
  a55=(a55*a58);
  a61=(a61*a36);
  a55=(a55+a61);
  a3=(a3*a59);
  a55=(a55+a3);
  a3=(a11*a9);
  a61=(a14*a7);
  a3=(a3-a61);
  a3=(a6*a3);
  a55=(a55-a3);
  a55=casadi_sq(a55);
  a64=(a64+a55);
  a50=(a50*a58);
  a21=(a21*a36);
  a50=(a50+a21);
  a16=(a16*a59);
  a50=(a50+a16);
  a9=(a7*a9);
  a14=(a14*a11);
  a9=(a9+a14);
  a9=(a6*a9);
  a50=(a50-a9);
  a50=casadi_sq(a50);
  a64=(a64+a50);
  a22=(a22*a58);
  a18=(a18*a36);
  a22=(a22+a18);
  a15=(a15*a59);
  a22=(a22+a15);
  a11=casadi_sq(a11);
  a7=casadi_sq(a7);
  a11=(a11+a7);
  a6=(a6*a11);
  a5=(a5-a6);
  a22=(a22-a5);
  a22=casadi_sq(a22);
  a64=(a64+a22);
  a4=(a4*a64);
  a1=(a1+a4);
  a2=(a2*a1);
  a0=(a0+a2);
  a2=arg[1]? arg[1][0] : 0;
  a2=casadi_sq(a2);
  a1=15.;
  a4=arg[1]? arg[1][1] : 0;
  a4=casadi_sq(a4);
  a64=arg[1]? arg[1][2] : 0;
  a64=casadi_sq(a64);
  a4=(a4+a64);
  a1=(a1*a4);
  a2=(a2+a1);
  a1=arg[1]? arg[1][3] : 0;
  a1=casadi_sq(a1);
  a8=(a8*a1);
  a2=(a2+a8);
  a0=(a0+a2);
  if (res[0]!=0) res[0][0]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int ACADOS_model_cost_ext_cost_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int ACADOS_model_cost_ext_cost_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int ACADOS_model_cost_ext_cost_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ACADOS_model_cost_ext_cost_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int ACADOS_model_cost_ext_cost_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ACADOS_model_cost_ext_cost_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void ACADOS_model_cost_ext_cost_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void ACADOS_model_cost_ext_cost_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int ACADOS_model_cost_ext_cost_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int ACADOS_model_cost_ext_cost_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real ACADOS_model_cost_ext_cost_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ACADOS_model_cost_ext_cost_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ACADOS_model_cost_ext_cost_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ACADOS_model_cost_ext_cost_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ACADOS_model_cost_ext_cost_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int ACADOS_model_cost_ext_cost_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int ACADOS_model_cost_ext_cost_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
