/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c10 CASADI_PREFIX(c10)
#define casadi_c11 CASADI_PREFIX(c11)
#define casadi_c12 CASADI_PREFIX(c12)
#define casadi_c13 CASADI_PREFIX(c13)
#define casadi_c14 CASADI_PREFIX(c14)
#define casadi_c15 CASADI_PREFIX(c15)
#define casadi_c16 CASADI_PREFIX(c16)
#define casadi_c17 CASADI_PREFIX(c17)
#define casadi_c18 CASADI_PREFIX(c18)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_c3 CASADI_PREFIX(c3)
#define casadi_c4 CASADI_PREFIX(c4)
#define casadi_c5 CASADI_PREFIX(c5)
#define casadi_c6 CASADI_PREFIX(c6)
#define casadi_c7 CASADI_PREFIX(c7)
#define casadi_c8 CASADI_PREFIX(c8)
#define casadi_c9 CASADI_PREFIX(c9)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_clear_casadi_int CASADI_PREFIX(clear_casadi_int)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_de_boor CASADI_PREFIX(de_boor)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f10 CASADI_PREFIX(f10)
#define casadi_f11 CASADI_PREFIX(f11)
#define casadi_f12 CASADI_PREFIX(f12)
#define casadi_f13 CASADI_PREFIX(f13)
#define casadi_f14 CASADI_PREFIX(f14)
#define casadi_f15 CASADI_PREFIX(f15)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_f4 CASADI_PREFIX(f4)
#define casadi_f5 CASADI_PREFIX(f5)
#define casadi_f6 CASADI_PREFIX(f6)
#define casadi_f7 CASADI_PREFIX(f7)
#define casadi_f8 CASADI_PREFIX(f8)
#define casadi_f9 CASADI_PREFIX(f9)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_fill_casadi_int CASADI_PREFIX(fill_casadi_int)
#define casadi_low CASADI_PREFIX(low)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_nd_boor_eval CASADI_PREFIX(nd_boor_eval)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_de_boor(casadi_real x, const casadi_real* knots, casadi_int n_knots, casadi_int degree, casadi_real* boor) {
  casadi_int d, i;
  for (d=1;d<degree+1;++d) {
    for (i=0;i<n_knots-d-1;++i) {
      casadi_real b, bottom;
      b = 0;
      bottom = knots[i + d] - knots[i];
      if (bottom) b = (x - knots[i]) * boor[i] / bottom;
      bottom = knots[i + d + 1] - knots[i + 1];
      if (bottom) b += (knots[i + d + 1] - x) * boor[i + 1] / bottom;
      boor[i] = b;
    }
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_fill_casadi_int(casadi_int* x, casadi_int n, casadi_int alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_clear_casadi_int(casadi_int* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_int casadi_low(casadi_real x, const casadi_real* grid, casadi_int ng, casadi_int lookup_mode) {
  switch (lookup_mode) {
    case 1:
      {
        casadi_real g0, dg;
        casadi_int ret;
        g0 = grid[0];
        dg = grid[ng-1]-g0;
        ret = (casadi_int) ((x-g0)*(ng-1)/dg);
        if (ret<0) ret=0;
        if (ret>ng-2) ret=ng-2;
        return ret;
      }
    case 2:
      {
        casadi_int start, stop, pivot;
        if (ng<2 || x<grid[1]) return 0;
        if (x>grid[ng-1]) return ng-2;
        start = 0;
        stop  = ng-1;
        while (1) {
          pivot = (stop+start)/2;
          if (x < grid[pivot]) {
            if (pivot==stop) return pivot;
            stop = pivot;
          } else {
            if (pivot==start) return pivot;
            start = pivot;
          }
        }
      }
    default:
      {
        casadi_int i;
        for (i=0; i<ng-2; ++i) {
          if (x < grid[i+1]) break;
        }
        return i;
      }
  }
}

void casadi_nd_boor_eval(casadi_real* ret, casadi_int n_dims, const casadi_real* all_knots, const casadi_int* offset, const casadi_int* all_degree, const casadi_int* strides, const casadi_real* c, casadi_int m, const casadi_real* all_x, const casadi_int* lookup_mode, casadi_int* iw, casadi_real* w) {
  casadi_int n_iter, k, i, pivot;
  casadi_int *boor_offset, *starts, *index, *coeff_offset;
  casadi_real *cumprod, *all_boor;
  boor_offset = iw; iw+=n_dims+1;
  starts = iw; iw+=n_dims;
  index = iw; iw+=n_dims;
  coeff_offset = iw;
  cumprod = w; w+= n_dims+1;
  all_boor = w;
  boor_offset[0] = 0;
  cumprod[n_dims] = 1;
  coeff_offset[n_dims] = 0;
  n_iter = 1;
  for (k=0;k<n_dims;++k) {
    casadi_real *boor;
    const casadi_real* knots;
    casadi_real x;
    casadi_int degree, n_knots, n_b, L, start;
    boor = all_boor+boor_offset[k];
    degree = all_degree[k];
    knots = all_knots + offset[k];
    n_knots = offset[k+1]-offset[k];
    n_b = n_knots-degree-1;
    x = all_x[k];
    L = casadi_low(x, knots+degree, n_knots-2*degree, lookup_mode[k]);
    start = L;
    if (start>n_b-degree-1) start = n_b-degree-1;
    starts[k] = start;
    casadi_clear(boor, 2*degree+1);
    if (x>=knots[0] && x<=knots[n_knots-1]) {
      if (x==knots[1]) {
        casadi_fill(boor, degree+1, 1.0);
      } else if (x==knots[n_knots-1]) {
        boor[degree] = 1;
      } else if (knots[L+degree]==x) {
        boor[degree-1] = 1;
      } else {
        boor[degree] = 1;
      }
    }
    casadi_de_boor(x, knots+start, 2*degree+2, degree, boor);
    boor+= degree+1;
    n_iter*= degree+1;
    boor_offset[k+1] = boor_offset[k] + degree+1;
  }
  casadi_clear_casadi_int(index, n_dims);
  for (pivot=n_dims-1;pivot>=0;--pivot) {
    cumprod[pivot] = (*(all_boor+boor_offset[pivot]))*cumprod[pivot+1];
    coeff_offset[pivot] = starts[pivot]*strides[pivot]+coeff_offset[pivot+1];
  }
  for (k=0;k<n_iter;++k) {
    casadi_int pivot = 0;
    for (i=0;i<m;++i) ret[i] += c[coeff_offset[0]+i]*cumprod[0];
    index[0]++;
    {
      while (index[pivot]==boor_offset[pivot+1]-boor_offset[pivot]) {
        index[pivot] = 0;
        if (pivot==n_dims-1) break;
        index[++pivot]++;
      }
      while (pivot>0) {
        cumprod[pivot] = (*(all_boor+boor_offset[pivot]+index[pivot]))*cumprod[pivot+1];
        coeff_offset[pivot] = (starts[pivot]+index[pivot])*strides[pivot]+coeff_offset[pivot+1];
        pivot--;
      }
    }
    cumprod[0] = (*(all_boor+index[0]))*cumprod[1];
    coeff_offset[0] = (starts[0]+index[0])*m+coeff_offset[1];
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

static const casadi_int casadi_s0[1] = {0};
static const casadi_int casadi_s1[1] = {1};
static const casadi_int casadi_s2[1] = {4};
static const casadi_int casadi_s3[2] = {0, 28};
static const casadi_int casadi_s4[1] = {3};
static const casadi_int casadi_s5[2] = {0, 26};
static const casadi_int casadi_s6[1] = {2};
static const casadi_int casadi_s7[2] = {0, 24};
static const casadi_int casadi_s8[2] = {0, 22};
static const casadi_int casadi_s9[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s10[9] = {3, 3, 0, 1, 2, 3, 0, 1, 2};
static const casadi_int casadi_s11[24] = {20, 1, 0, 20, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19};
static const casadi_int casadi_s12[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s13[3] = {0, 0, 0};

static const casadi_real casadi_c0[23] = {-1.0000000000000693e+00, -9.9999999999994493e-01, -1.0000000000000089e+00, -9.9999999999996181e-01, -1.0000000000000600e+00, -1.0000000000000084e+00, -9.9999999999995737e-01, -9.9999999999998757e-01, -9.9999999999999756e-01, -1.0000000000000115e+00, -1.0000000000000355e+00, -1.0000000000000142e+00, -9.9999999999994182e-01, -9.9999999999993916e-01, -1.0000000000000631e+00, -1.0000000000000417e+00, -9.9999999999996181e-01, -9.9999999999999378e-01, -1.0000000000000364e+00, -9.9999999999998046e-01, -9.9999999999995737e-01, -9.9999999999997868e-01, -1.0000000000001066e+00};
static const casadi_real casadi_c1[28] = {0., 0., 0., 0., 0., 9.0000000000000002e-01, 1.2000000000000002e+00, 1.5000000000000000e+00, 1.8000000000000000e+00, 2.1000000000000001e+00, 2.4000000000000004e+00, 2.7000000000000002e+00, 3., 3.3000000000000003e+00, 3.6000000000000001e+00, 3.9000000000000004e+00, 4.2000000000000002e+00, 4.5000000000000000e+00, 4.8000000000000007e+00, 5.1000000000000005e+00, 5.4000000000000004e+00, 5.7000000000000002e+00, 6., 6.9000000000000004e+00, 6.9000000000000004e+00, 6.9000000000000004e+00, 6.9000000000000004e+00, 6.9000000000000004e+00};
static const casadi_real casadi_c2[23] = {-1.1231495259353579e+00, -7.3432580057186558e-01, -1.3226498686694645e+00, -6.6465136930673685e-01, -1.3414607596134120e+00, 1.3368983546923676e+00, -2.0507188278619606e+00, 8.5163236407008380e-01, -2.1289528932214452e-01, 1.3093326634696210e+00, -8.3282792907989123e-02, 4.3304198491865575e-01, 4.0781876315389098e-01, 1.6719611055063697e+00, -1.5628359262988980e+00, -7.5202870656999554e-01, -1.1788899997738200e+00, -7.5319239399568083e-01, -1.4946754739194130e+00, 7.1048127642423875e-01, -3.6066869880817265e-01, 1.9320566175352738e-01, -7.4125666525649336e-02};
static const casadi_real casadi_c3[23] = {-2.6645352591003757e-15, -6.2172489379008766e-15, -8.8817841970012523e-16, -6.6613381477509392e-15, 2.2204460492503131e-15, 1.3322676295501878e-14, 1.8651746813702630e-14, 9.7699626167013776e-15, -1.8651746813702630e-14, -2.6201263381153694e-14, 2.2204460492503131e-15, 2.5757174171303632e-14, -1.4654943925052066e-14, -2.2204460492503131e-14, 2.3536728122053319e-14, 3.7303493627405260e-14, -3.5527136788005009e-15, -3.6415315207705135e-14, -8.8817841970012523e-16, 1.5099033134902129e-14, 1.8651746813702630e-14, -1.9539925233402755e-14, -1.5987211554602254e-14};
static const casadi_real casadi_c4[22] = {5.5333515547317802e-13, -2.1316282072803006e-13, 1.2523315717771766e-13, -2.1804780203638074e-13, 1.7186252421197423e-13, 1.7008616737257398e-13, -1.0080825063596421e-13, -3.3306690738754696e-14, -4.6629367034256575e-14, -7.9936057773011271e-14, 7.1054273576010019e-14, 2.4158453015843406e-13, 8.8817841970012523e-15, -4.1300296516055823e-13, 7.1054273576010019e-14, 2.6645352591003757e-13, -1.0658141036401503e-13, -1.4210854715202004e-13, 1.2434497875801753e-13, 6.1728400169158704e-14, -7.1054273576010019e-14, -5.6843418860808015e-13};
static const casadi_real casadi_c5[26] = {0., 0., 0., 0., 9.0000000000000002e-01, 1.2000000000000002e+00, 1.5000000000000000e+00, 1.8000000000000000e+00, 2.1000000000000001e+00, 2.4000000000000004e+00, 2.7000000000000002e+00, 3., 3.3000000000000003e+00, 3.6000000000000001e+00, 3.9000000000000004e+00, 4.2000000000000002e+00, 4.5000000000000000e+00, 4.8000000000000007e+00, 5.1000000000000005e+00, 5.4000000000000004e+00, 5.7000000000000002e+00, 6., 6.9000000000000004e+00, 6.9000000000000004e+00, 6.9000000000000004e+00, 6.9000000000000004e+00};
static const casadi_real casadi_c6[22] = {1.7281054460599656e+00, -1.9610802269919962e+00, 1.7546626649672736e+00, -1.5040208673481674e+00, 8.9278637143525970e+00, -1.1292057275181094e+01, 9.6745039731068143e+00, -3.5484255113074283e+00, 5.0740931759725516e+00, -4.6420515212587006e+00, 1.7210825927554827e+00, -8.4077405882549305e-02, 4.2138078078415964e+00, -1.0782656772684220e+01, 2.7026907324296752e+00, -1.4228709773460819e+00, 1.4189920192604641e+00, -2.4716102664124424e+00, 4.9003483340970044e+00, -2.8563999339530968e+00, 1.8462478685389998e+00, -1.1881392367963406e+00};
static const casadi_real casadi_c7[22] = {-1.5789838572446671e-14, 1.7763568394002505e-14, -1.5395092608135503e-14, 1.9737298215558338e-14, 3.7007434154171876e-14, 1.7763568394002511e-14, -2.9605947323337510e-14, -9.4739031434680029e-14, -2.5165055224836877e-14, 9.4739031434680042e-14, 7.8455760406844391e-14, -1.3470706032118565e-13, -2.5165055224836884e-14, 1.5247062871518808e-13, 4.5889218351173141e-14, -1.3618735768735254e-13, -1.0954200509634877e-13, 1.1842378929335009e-13, 3.5527136788005009e-14, 9.4739031434680067e-15, -1.2730557349035127e-13, 1.5789838572446665e-14};
static const casadi_real casadi_c8[21] = {1.1184468988816393e-13, -8.2896652505345017e-14, 7.0264781647387688e-14, 5.7567119795378457e-14, -6.4146219200564543e-14, -1.5789838572446670e-13, -2.1711028037114171e-13, 2.3191325403281056e-13, 3.9968028886505646e-13, -5.4277570092785509e-14, -7.1054273576009998e-13, 3.6514001698782924e-13, 5.9211894646674992e-13, -3.5527136788004969e-13, -6.0692192012841874e-13, 8.8817841970012523e-14, 7.5988598129899673e-13, -2.7632217501781712e-13, -5.2106467289074005e-14, -3.4194869158454816e-13, 4.7698470687599290e-13};
static const casadi_real casadi_c9[24] = {0., 0., 0., 9.0000000000000002e-01, 1.2000000000000002e+00, 1.5000000000000000e+00, 1.8000000000000000e+00, 2.1000000000000001e+00, 2.4000000000000004e+00, 2.7000000000000002e+00, 3., 3.3000000000000003e+00, 3.6000000000000001e+00, 3.9000000000000004e+00, 4.2000000000000002e+00, 4.5000000000000000e+00, 4.8000000000000007e+00, 5.1000000000000005e+00, 5.4000000000000004e+00, 5.7000000000000002e+00, 6., 6.9000000000000004e+00, 6.9000000000000004e+00, 6.9000000000000004e+00};
static const casadi_real casadi_c10[21] = {-1.2297285576839872e+01, 9.2893572298981741e+00, -6.5173670646308821e+00, 3.4772948605669214e+01, -6.7399736631778978e+01, 6.9888537494292990e+01, -4.4076431614714139e+01, 2.8741728957599932e+01, -3.2387148990770839e+01, 2.1210447046713945e+01, -6.0171999954601052e+00, 1.4326284045747153e+01, -4.9988215268419388e+01, 4.4951158350379629e+01, -1.3751872365919183e+01, 9.4728766553551509e+00, -1.2968674285576363e+01, 2.4573195335031507e+01, -1.5513496536100202e+01, 1.1756619506230241e+01, -1.0114623684451132e+01};
static const casadi_real casadi_c11[21] = {-2.5549932540040272e-12, 8.4598994476436928e-13, -6.8656191842819680e-13, 1.2997010874945167e-12, -5.9211894646674679e-15, -9.0298139336179365e-13, 2.2500519965736504e-13, -4.4408920985006262e-14, -1.1102230246251565e-13, 5.0330110449673770e-13, 5.6843418860807995e-13, -7.7567581987144274e-13, -1.4062824978585316e-12, 1.6135241291218936e-12, 6.5133084111342490e-13, -1.2434497875801749e-12, -1.1842378929335012e-13, 8.8817841970012584e-13, -1.2523315717771766e-13, -3.3195668436292181e-13, -1.6579330501068999e-12};
static const casadi_real casadi_c12[20] = {-4.3275853865224213e-13, 2.5526905692122116e-13, -4.2325539506697460e-14, -4.0571112998647671e-13, -3.1250722174634046e-13, -1.9737298215558324e-13, 1.4967451146798407e-12, 5.5922344944081993e-13, -1.5131928631928063e-12, -2.1875505522243814e-12, 3.5856091758264302e-12, 7.5659643159640227e-13, -3.1579677144893338e-12, -8.3883517416122950e-13, 2.3191325403281021e-12, 2.2368937977632822e-12, -3.4540271877227147e-12, 7.4738569242914407e-13, -4.8307037382579026e-13, 1.8198519965789794e-12};
static const casadi_real casadi_c13[22] = {0., 0., 9.0000000000000002e-01, 1.2000000000000002e+00, 1.5000000000000000e+00, 1.8000000000000000e+00, 2.1000000000000001e+00, 2.4000000000000004e+00, 2.7000000000000002e+00, 3., 3.3000000000000003e+00, 3.6000000000000001e+00, 3.9000000000000004e+00, 4.2000000000000002e+00, 4.5000000000000000e+00, 4.8000000000000007e+00, 5.1000000000000005e+00, 5.4000000000000004e+00, 5.7000000000000002e+00, 6., 6.9000000000000004e+00, 6.9000000000000004e+00};
static const casadi_real casadi_c14[20] = {4.7970317348306772e+01, -2.6344540490881759e+01, 1.3763438556766698e+02, -3.4057561745816071e+02, 4.5762758042023984e+02, -3.7988323036335692e+02, 2.4272720190771355e+02, -2.0376292649456934e+02, 1.7865865345828260e+02, -9.0758823473913495e+01, 6.7811613470690858e+01, -2.1438166438055512e+02, 3.1646457872933024e+02, -1.9567676905432918e+02, 7.7415830070914382e+01, -7.4805169803105088e+01, 1.2513956540202631e+02, -1.3362230623710576e+02, 4.5450193403884072e+01, -4.8602762645958592e+01};
static const casadi_real casadi_c15[20] = {7.5577404417075486e-12, -2.5542531053209432e-12, 6.6208766864090454e-12, -4.3520742565306144e-12, -2.9902006796570869e-12, 3.7599553100638608e-12, -8.9804706880790428e-13, -2.2204460492503143e-13, 2.0477446898641777e-12, 2.1711028037114103e-13, -4.4803666949317419e-12, -2.1020222599569629e-12, 1.0066022089934758e-11, -3.2073109600282266e-12, -6.3159354289786604e-12, 3.7500866609560847e-12, 3.3553406966449220e-12, -3.3780385895928138e-12, -3.4453921197534021e-13, -2.9466141460977279e-12};
static const casadi_real casadi_c16[3] = {0., 0., -9.8066499999999994e+00};
static const casadi_real casadi_c17[3] = {7.1684587813620077e+04, 7.1684587813620077e+04, 4.6019328117809477e+04};
static const casadi_real casadi_c18[9] = {1.3950000000000000e-05, 0., 0., 0., 1.3950000000000000e-05, 0., 0., 0., 2.1730000000000000e-05};

/* jac_x_ref:(x,out_f[1x1,0nz])->(jac) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c1,casadi_s3,casadi_s2,casadi_s1,casadi_c0,1,(&w0),casadi_s0, iw, w);
  /* #2: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

/* jac_y_ref:(x,out_f[1x1,0nz])->(jac) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c1,casadi_s3,casadi_s2,casadi_s1,casadi_c2,1,(&w0),casadi_s0, iw, w);
  /* #2: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

/* jac_z_ref:(x,out_f[1x1,0nz])->(jac) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c1,casadi_s3,casadi_s2,casadi_s1,casadi_c3,1,(&w0),casadi_s0, iw, w);
  /* #2: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

/* fwd1_jac_x_ref:(x,out_f[1x1,0nz],out_jac[1x1,0nz],fwd_x,fwd_out_f[1x1,0nz])->(fwd_jac) */
static int casadi_f4(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c5,casadi_s5,casadi_s4,casadi_s1,casadi_c4,1,(&w0),casadi_s0, iw, w);
  /* #2: @0 = input[3][0] */
  w0 = arg[3] ? arg[3][0] : 0;
  /* #3: @1 = (@1*@0) */
  w1 *= w0;
  /* #4: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

/* fwd1_jac_y_ref:(x,out_f[1x1,0nz],out_jac[1x1,0nz],fwd_x,fwd_out_f[1x1,0nz])->(fwd_jac) */
static int casadi_f5(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c5,casadi_s5,casadi_s4,casadi_s1,casadi_c6,1,(&w0),casadi_s0, iw, w);
  /* #2: @0 = input[3][0] */
  w0 = arg[3] ? arg[3][0] : 0;
  /* #3: @1 = (@1*@0) */
  w1 *= w0;
  /* #4: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

/* fwd1_jac_z_ref:(x,out_f[1x1,0nz],out_jac[1x1,0nz],fwd_x,fwd_out_f[1x1,0nz])->(fwd_jac) */
static int casadi_f6(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c5,casadi_s5,casadi_s4,casadi_s1,casadi_c7,1,(&w0),casadi_s0, iw, w);
  /* #2: @0 = input[3][0] */
  w0 = arg[3] ? arg[3][0] : 0;
  /* #3: @1 = (@1*@0) */
  w1 *= w0;
  /* #4: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

/* adj1_fwd1_jac_z_ref:(x,out_f[1x1,0nz],out_jac[1x1,0nz],fwd_x,fwd_out_f[1x1,0nz],out_fwd_jac[1x1,0nz],adj_fwd_jac)->(adj_x,adj_out_f[1x1,0nz],adj_out_jac[1x1,0nz],adj_fwd_x,adj_fwd_out_f[1x1,0nz]) */
static int casadi_f7(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, w2, w3;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c9,casadi_s7,casadi_s6,casadi_s1,casadi_c8,1,(&w0),casadi_s0, iw, w);
  /* #2: @2 = input[3][0] */
  w2 = arg[3] ? arg[3][0] : 0;
  /* #3: @3 = input[6][0] */
  w3 = arg[6] ? arg[6][0] : 0;
  /* #4: @2 = (@2*@3) */
  w2 *= w3;
  /* #5: @1 = (@1*@2) */
  w1 *= w2;
  /* #6: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  /* #7: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c5,casadi_s5,casadi_s4,casadi_s1,casadi_c7,1,(&w0),casadi_s0, iw, w);
  /* #8: @1 = (@1*@3) */
  w1 *= w3;
  /* #9: output[3][0] = @1 */
  if (res[3]) res[3][0] = w1;
  return 0;
}

/* adj1_fwd1_jac_y_ref:(x,out_f[1x1,0nz],out_jac[1x1,0nz],fwd_x,fwd_out_f[1x1,0nz],out_fwd_jac[1x1,0nz],adj_fwd_jac)->(adj_x,adj_out_f[1x1,0nz],adj_out_jac[1x1,0nz],adj_fwd_x,adj_fwd_out_f[1x1,0nz]) */
static int casadi_f8(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, w2, w3;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c9,casadi_s7,casadi_s6,casadi_s1,casadi_c10,1,(&w0),casadi_s0, iw, w);
  /* #2: @2 = input[3][0] */
  w2 = arg[3] ? arg[3][0] : 0;
  /* #3: @3 = input[6][0] */
  w3 = arg[6] ? arg[6][0] : 0;
  /* #4: @2 = (@2*@3) */
  w2 *= w3;
  /* #5: @1 = (@1*@2) */
  w1 *= w2;
  /* #6: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  /* #7: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c5,casadi_s5,casadi_s4,casadi_s1,casadi_c6,1,(&w0),casadi_s0, iw, w);
  /* #8: @1 = (@1*@3) */
  w1 *= w3;
  /* #9: output[3][0] = @1 */
  if (res[3]) res[3][0] = w1;
  return 0;
}

/* adj1_fwd1_jac_x_ref:(x,out_f[1x1,0nz],out_jac[1x1,0nz],fwd_x,fwd_out_f[1x1,0nz],out_fwd_jac[1x1,0nz],adj_fwd_jac)->(adj_x,adj_out_f[1x1,0nz],adj_out_jac[1x1,0nz],adj_fwd_x,adj_fwd_out_f[1x1,0nz]) */
static int casadi_f9(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, w2, w3;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c9,casadi_s7,casadi_s6,casadi_s1,casadi_c11,1,(&w0),casadi_s0, iw, w);
  /* #2: @2 = input[3][0] */
  w2 = arg[3] ? arg[3][0] : 0;
  /* #3: @3 = input[6][0] */
  w3 = arg[6] ? arg[6][0] : 0;
  /* #4: @2 = (@2*@3) */
  w2 *= w3;
  /* #5: @1 = (@1*@2) */
  w1 *= w2;
  /* #6: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  /* #7: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c5,casadi_s5,casadi_s4,casadi_s1,casadi_c4,1,(&w0),casadi_s0, iw, w);
  /* #8: @1 = (@1*@3) */
  w1 *= w3;
  /* #9: output[3][0] = @1 */
  if (res[3]) res[3][0] = w1;
  return 0;
}

/* fwd1_fwd1_jac_x_ref:(x,out_f[1x1,0nz],out_jac[1x1,0nz],fwd_x,fwd_out_f[1x1,0nz],out_fwd_jac[1x1,0nz],fwd_x,fwd_out_f[1x1,0nz],fwd_out_jac[1x1,0nz],fwd_fwd_x,fwd_fwd_out_f[1x1,0nz])->(fwd_fwd_jac) */
static int casadi_f10(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, w2, w3;
  /* #0: @0 = input[3][0] */
  w0 = arg[3] ? arg[3][0] : 0;
  /* #1: @1 = input[0][0] */
  w1 = arg[0] ? arg[0][0] : 0;
  /* #2: @2 = BSpline(@1) */
  casadi_clear((&w2), 1);
  CASADI_PREFIX(nd_boor_eval)((&w2),1,casadi_c9,casadi_s7,casadi_s6,casadi_s1,casadi_c11,1,(&w1),casadi_s0, iw, w);
  /* #3: @3 = input[6][0] */
  w3 = arg[6] ? arg[6][0] : 0;
  /* #4: @2 = (@2*@3) */
  w2 *= w3;
  /* #5: @0 = (@0*@2) */
  w0 *= w2;
  /* #6: @2 = BSpline(@1) */
  casadi_clear((&w2), 1);
  CASADI_PREFIX(nd_boor_eval)((&w2),1,casadi_c5,casadi_s5,casadi_s4,casadi_s1,casadi_c4,1,(&w1),casadi_s0, iw, w);
  /* #7: @1 = input[9][0] */
  w1 = arg[9] ? arg[9][0] : 0;
  /* #8: @2 = (@2*@1) */
  w2 *= w1;
  /* #9: @0 = (@0+@2) */
  w0 += w2;
  /* #10: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  return 0;
}

/* fwd1_fwd1_jac_y_ref:(x,out_f[1x1,0nz],out_jac[1x1,0nz],fwd_x,fwd_out_f[1x1,0nz],out_fwd_jac[1x1,0nz],fwd_x,fwd_out_f[1x1,0nz],fwd_out_jac[1x1,0nz],fwd_fwd_x,fwd_fwd_out_f[1x1,0nz])->(fwd_fwd_jac) */
static int casadi_f11(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, w2, w3;
  /* #0: @0 = input[3][0] */
  w0 = arg[3] ? arg[3][0] : 0;
  /* #1: @1 = input[0][0] */
  w1 = arg[0] ? arg[0][0] : 0;
  /* #2: @2 = BSpline(@1) */
  casadi_clear((&w2), 1);
  CASADI_PREFIX(nd_boor_eval)((&w2),1,casadi_c9,casadi_s7,casadi_s6,casadi_s1,casadi_c10,1,(&w1),casadi_s0, iw, w);
  /* #3: @3 = input[6][0] */
  w3 = arg[6] ? arg[6][0] : 0;
  /* #4: @2 = (@2*@3) */
  w2 *= w3;
  /* #5: @0 = (@0*@2) */
  w0 *= w2;
  /* #6: @2 = BSpline(@1) */
  casadi_clear((&w2), 1);
  CASADI_PREFIX(nd_boor_eval)((&w2),1,casadi_c5,casadi_s5,casadi_s4,casadi_s1,casadi_c6,1,(&w1),casadi_s0, iw, w);
  /* #7: @1 = input[9][0] */
  w1 = arg[9] ? arg[9][0] : 0;
  /* #8: @2 = (@2*@1) */
  w2 *= w1;
  /* #9: @0 = (@0+@2) */
  w0 += w2;
  /* #10: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  return 0;
}

/* fwd1_fwd1_jac_z_ref:(x,out_f[1x1,0nz],out_jac[1x1,0nz],fwd_x,fwd_out_f[1x1,0nz],out_fwd_jac[1x1,0nz],fwd_x,fwd_out_f[1x1,0nz],fwd_out_jac[1x1,0nz],fwd_fwd_x,fwd_fwd_out_f[1x1,0nz])->(fwd_fwd_jac) */
static int casadi_f12(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, w2, w3;
  /* #0: @0 = input[3][0] */
  w0 = arg[3] ? arg[3][0] : 0;
  /* #1: @1 = input[0][0] */
  w1 = arg[0] ? arg[0][0] : 0;
  /* #2: @2 = BSpline(@1) */
  casadi_clear((&w2), 1);
  CASADI_PREFIX(nd_boor_eval)((&w2),1,casadi_c9,casadi_s7,casadi_s6,casadi_s1,casadi_c8,1,(&w1),casadi_s0, iw, w);
  /* #3: @3 = input[6][0] */
  w3 = arg[6] ? arg[6][0] : 0;
  /* #4: @2 = (@2*@3) */
  w2 *= w3;
  /* #5: @0 = (@0*@2) */
  w0 *= w2;
  /* #6: @2 = BSpline(@1) */
  casadi_clear((&w2), 1);
  CASADI_PREFIX(nd_boor_eval)((&w2),1,casadi_c5,casadi_s5,casadi_s4,casadi_s1,casadi_c7,1,(&w1),casadi_s0, iw, w);
  /* #7: @1 = input[9][0] */
  w1 = arg[9] ? arg[9][0] : 0;
  /* #8: @2 = (@2*@1) */
  w2 *= w1;
  /* #9: @0 = (@0+@2) */
  w0 += w2;
  /* #10: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  return 0;
}

/* fwd1_adj1_fwd1_jac_z_ref:(x,out_f[1x1,0nz],out_jac[1x1,0nz],fwd_x,fwd_out_f[1x1,0nz],out_fwd_jac[1x1,0nz],adj_fwd_jac,out_adj_x[1x1,0nz],out_adj_out_f[1x1,0nz],out_adj_out_jac[1x1,0nz],out_adj_fwd_x[1x1,0nz],out_adj_fwd_out_f[1x1,0nz],fwd_x,fwd_out_f[1x1,0nz],fwd_out_jac[1x1,0nz],fwd_fwd_x,fwd_fwd_out_f[1x1,0nz],fwd_out_fwd_jac[1x1,0nz],fwd_adj_fwd_jac)->(fwd_adj_x,fwd_adj_out_f[1x1,0nz],fwd_adj_out_jac[1x1,0nz],fwd_adj_fwd_x,fwd_adj_fwd_out_f[1x1,0nz]) */
static int casadi_f13(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, w2, w3, w4, w5, w6, w7;
  /* #0: @0 = input[3][0] */
  w0 = arg[3] ? arg[3][0] : 0;
  /* #1: @1 = input[6][0] */
  w1 = arg[6] ? arg[6][0] : 0;
  /* #2: @2 = (@0*@1) */
  w2  = (w0*w1);
  /* #3: @3 = input[0][0] */
  w3 = arg[0] ? arg[0][0] : 0;
  /* #4: @4 = BSpline(@3) */
  casadi_clear((&w4), 1);
  CASADI_PREFIX(nd_boor_eval)((&w4),1,casadi_c13,casadi_s8,casadi_s1,casadi_s1,casadi_c12,1,(&w3),casadi_s0, iw, w);
  /* #5: @5 = input[12][0] */
  w5 = arg[12] ? arg[12][0] : 0;
  /* #6: @4 = (@4*@5) */
  w4 *= w5;
  /* #7: @2 = (@2*@4) */
  w2 *= w4;
  /* #8: @4 = BSpline(@3) */
  casadi_clear((&w4), 1);
  CASADI_PREFIX(nd_boor_eval)((&w4),1,casadi_c9,casadi_s7,casadi_s6,casadi_s1,casadi_c8,1,(&w3),casadi_s0, iw, w);
  /* #9: @6 = input[15][0] */
  w6 = arg[15] ? arg[15][0] : 0;
  /* #10: @6 = (@1*@6) */
  w6  = (w1*w6);
  /* #11: @7 = input[18][0] */
  w7 = arg[18] ? arg[18][0] : 0;
  /* #12: @0 = (@0*@7) */
  w0 *= w7;
  /* #13: @6 = (@6+@0) */
  w6 += w0;
  /* #14: @6 = (@4*@6) */
  w6  = (w4*w6);
  /* #15: @2 = (@2+@6) */
  w2 += w6;
  /* #16: output[0][0] = @2 */
  if (res[0]) res[0][0] = w2;
  /* #17: @4 = (@4*@5) */
  w4 *= w5;
  /* #18: @1 = (@1*@4) */
  w1 *= w4;
  /* #19: @4 = BSpline(@3) */
  casadi_clear((&w4), 1);
  CASADI_PREFIX(nd_boor_eval)((&w4),1,casadi_c5,casadi_s5,casadi_s4,casadi_s1,casadi_c7,1,(&w3),casadi_s0, iw, w);
  /* #20: @4 = (@4*@7) */
  w4 *= w7;
  /* #21: @1 = (@1+@4) */
  w1 += w4;
  /* #22: output[3][0] = @1 */
  if (res[3]) res[3][0] = w1;
  return 0;
}

/* fwd1_adj1_fwd1_jac_y_ref:(x,out_f[1x1,0nz],out_jac[1x1,0nz],fwd_x,fwd_out_f[1x1,0nz],out_fwd_jac[1x1,0nz],adj_fwd_jac,out_adj_x[1x1,0nz],out_adj_out_f[1x1,0nz],out_adj_out_jac[1x1,0nz],out_adj_fwd_x[1x1,0nz],out_adj_fwd_out_f[1x1,0nz],fwd_x,fwd_out_f[1x1,0nz],fwd_out_jac[1x1,0nz],fwd_fwd_x,fwd_fwd_out_f[1x1,0nz],fwd_out_fwd_jac[1x1,0nz],fwd_adj_fwd_jac)->(fwd_adj_x,fwd_adj_out_f[1x1,0nz],fwd_adj_out_jac[1x1,0nz],fwd_adj_fwd_x,fwd_adj_fwd_out_f[1x1,0nz]) */
static int casadi_f14(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, w2, w3, w4, w5, w6, w7;
  /* #0: @0 = input[3][0] */
  w0 = arg[3] ? arg[3][0] : 0;
  /* #1: @1 = input[6][0] */
  w1 = arg[6] ? arg[6][0] : 0;
  /* #2: @2 = (@0*@1) */
  w2  = (w0*w1);
  /* #3: @3 = input[0][0] */
  w3 = arg[0] ? arg[0][0] : 0;
  /* #4: @4 = BSpline(@3) */
  casadi_clear((&w4), 1);
  CASADI_PREFIX(nd_boor_eval)((&w4),1,casadi_c13,casadi_s8,casadi_s1,casadi_s1,casadi_c14,1,(&w3),casadi_s0, iw, w);
  /* #5: @5 = input[12][0] */
  w5 = arg[12] ? arg[12][0] : 0;
  /* #6: @4 = (@4*@5) */
  w4 *= w5;
  /* #7: @2 = (@2*@4) */
  w2 *= w4;
  /* #8: @4 = BSpline(@3) */
  casadi_clear((&w4), 1);
  CASADI_PREFIX(nd_boor_eval)((&w4),1,casadi_c9,casadi_s7,casadi_s6,casadi_s1,casadi_c10,1,(&w3),casadi_s0, iw, w);
  /* #9: @6 = input[15][0] */
  w6 = arg[15] ? arg[15][0] : 0;
  /* #10: @6 = (@1*@6) */
  w6  = (w1*w6);
  /* #11: @7 = input[18][0] */
  w7 = arg[18] ? arg[18][0] : 0;
  /* #12: @0 = (@0*@7) */
  w0 *= w7;
  /* #13: @6 = (@6+@0) */
  w6 += w0;
  /* #14: @6 = (@4*@6) */
  w6  = (w4*w6);
  /* #15: @2 = (@2+@6) */
  w2 += w6;
  /* #16: output[0][0] = @2 */
  if (res[0]) res[0][0] = w2;
  /* #17: @4 = (@4*@5) */
  w4 *= w5;
  /* #18: @1 = (@1*@4) */
  w1 *= w4;
  /* #19: @4 = BSpline(@3) */
  casadi_clear((&w4), 1);
  CASADI_PREFIX(nd_boor_eval)((&w4),1,casadi_c5,casadi_s5,casadi_s4,casadi_s1,casadi_c6,1,(&w3),casadi_s0, iw, w);
  /* #20: @4 = (@4*@7) */
  w4 *= w7;
  /* #21: @1 = (@1+@4) */
  w1 += w4;
  /* #22: output[3][0] = @1 */
  if (res[3]) res[3][0] = w1;
  return 0;
}

/* fwd1_adj1_fwd1_jac_x_ref:(x,out_f[1x1,0nz],out_jac[1x1,0nz],fwd_x,fwd_out_f[1x1,0nz],out_fwd_jac[1x1,0nz],adj_fwd_jac,out_adj_x[1x1,0nz],out_adj_out_f[1x1,0nz],out_adj_out_jac[1x1,0nz],out_adj_fwd_x[1x1,0nz],out_adj_fwd_out_f[1x1,0nz],fwd_x,fwd_out_f[1x1,0nz],fwd_out_jac[1x1,0nz],fwd_fwd_x,fwd_fwd_out_f[1x1,0nz],fwd_out_fwd_jac[1x1,0nz],fwd_adj_fwd_jac)->(fwd_adj_x,fwd_adj_out_f[1x1,0nz],fwd_adj_out_jac[1x1,0nz],fwd_adj_fwd_x,fwd_adj_fwd_out_f[1x1,0nz]) */
static int casadi_f15(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, w2, w3, w4, w5, w6, w7;
  /* #0: @0 = input[3][0] */
  w0 = arg[3] ? arg[3][0] : 0;
  /* #1: @1 = input[6][0] */
  w1 = arg[6] ? arg[6][0] : 0;
  /* #2: @2 = (@0*@1) */
  w2  = (w0*w1);
  /* #3: @3 = input[0][0] */
  w3 = arg[0] ? arg[0][0] : 0;
  /* #4: @4 = BSpline(@3) */
  casadi_clear((&w4), 1);
  CASADI_PREFIX(nd_boor_eval)((&w4),1,casadi_c13,casadi_s8,casadi_s1,casadi_s1,casadi_c15,1,(&w3),casadi_s0, iw, w);
  /* #5: @5 = input[12][0] */
  w5 = arg[12] ? arg[12][0] : 0;
  /* #6: @4 = (@4*@5) */
  w4 *= w5;
  /* #7: @2 = (@2*@4) */
  w2 *= w4;
  /* #8: @4 = BSpline(@3) */
  casadi_clear((&w4), 1);
  CASADI_PREFIX(nd_boor_eval)((&w4),1,casadi_c9,casadi_s7,casadi_s6,casadi_s1,casadi_c11,1,(&w3),casadi_s0, iw, w);
  /* #9: @6 = input[15][0] */
  w6 = arg[15] ? arg[15][0] : 0;
  /* #10: @6 = (@1*@6) */
  w6  = (w1*w6);
  /* #11: @7 = input[18][0] */
  w7 = arg[18] ? arg[18][0] : 0;
  /* #12: @0 = (@0*@7) */
  w0 *= w7;
  /* #13: @6 = (@6+@0) */
  w6 += w0;
  /* #14: @6 = (@4*@6) */
  w6  = (w4*w6);
  /* #15: @2 = (@2+@6) */
  w2 += w6;
  /* #16: output[0][0] = @2 */
  if (res[0]) res[0][0] = w2;
  /* #17: @4 = (@4*@5) */
  w4 *= w5;
  /* #18: @1 = (@1*@4) */
  w1 *= w4;
  /* #19: @4 = BSpline(@3) */
  casadi_clear((&w4), 1);
  CASADI_PREFIX(nd_boor_eval)((&w4),1,casadi_c5,casadi_s5,casadi_s4,casadi_s1,casadi_c4,1,(&w3),casadi_s0, iw, w);
  /* #20: @4 = (@4*@7) */
  w4 *= w7;
  /* #21: @1 = (@1+@4) */
  w1 += w4;
  /* #22: output[3][0] = @1 */
  if (res[3]) res[3][0] = w1;
  return 0;
}

/* quadrotor_expl_ode_fun:(i0[20],i1[4],i2[])->(o0[20]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real **res1=res+1, *rr, *ss, *tt;
  const casadi_real **arg1=arg+3, *cr, *cs;
  casadi_real w0, w1, w3, w5, w7, *w8=w+22, *w9=w+25, w10, w11, w12, *w13=w+31, w17, w19, w21, w23, *w24=w+38, *w25=w+41, w27, w31, w33, w34, w38, w40, w44, w45, w46, w47, w48, w49, w50, *w51=w+57, *w52=w+60, w53, w54, w55, w56, *w57=w+67, *w58=w+70, w59, w60, w61, w62, *w63=w+77, *w64=w+80, *w65=w+83, *w66=w+86, *w67=w+95, w72, w76, w77, w78;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: @1 = input[0][0] */
  w1 = arg[0] ? arg[0][0] : 0;
  /* #2: @2 = 00 */
  /* #3: @3 = jac_x_ref(@1, @2) */
  arg1[0]=(&w1);
  arg1[1]=0;
  res1[0]=(&w3);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #4: @4 = 00 */
  /* #5: @5 = jac_y_ref(@1, @4) */
  arg1[0]=(&w1);
  arg1[1]=0;
  res1[0]=(&w5);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #6: @6 = 00 */
  /* #7: @7 = jac_z_ref(@1, @6) */
  arg1[0]=(&w1);
  arg1[1]=0;
  res1[0]=(&w7);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #8: @8 = vertcat(@3, @5, @7) */
  rr=w8;
  *rr++ = w3;
  *rr++ = w5;
  *rr++ = w7;
  /* #9: @9 = @8' */
  casadi_copy(w8, 3, w9);
  /* #10: @10 = input[0][13] */
  w10 = arg[0] ? arg[0][13] : 0;
  /* #11: @11 = input[0][14] */
  w11 = arg[0] ? arg[0][14] : 0;
  /* #12: @12 = input[0][15] */
  w12 = arg[0] ? arg[0][15] : 0;
  /* #13: @13 = vertcat(@10, @11, @12) */
  rr=w13;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  /* #14: @0 = mac(@9,@13,@0) */
  for (i=0, rr=(&w0); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w9+j, tt=w13+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #15: @10 = 1 */
  w10 = 1.;
  /* #16: @14 = 00 */
  /* #17: @11 = 1 */
  w11 = 1.;
  /* #18: @15 = 00 */
  /* #19: @12 = fwd1_jac_x_ref(@1, @2, @14, @11, @15) */
  arg1[0]=(&w1);
  arg1[1]=0;
  arg1[2]=0;
  arg1[3]=(&w11);
  arg1[4]=0;
  res1[0]=(&w12);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #20: @16 = 00 */
  /* #21: @17 = 1 */
  w17 = 1.;
  /* #22: @18 = 00 */
  /* #23: @19 = fwd1_jac_y_ref(@1, @4, @16, @17, @18) */
  arg1[0]=(&w1);
  arg1[1]=0;
  arg1[2]=0;
  arg1[3]=(&w17);
  arg1[4]=0;
  res1[0]=(&w19);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #24: @20 = 00 */
  /* #25: @21 = 1 */
  w21 = 1.;
  /* #26: @22 = 00 */
  /* #27: @23 = fwd1_jac_z_ref(@1, @6, @20, @21, @22) */
  arg1[0]=(&w1);
  arg1[1]=0;
  arg1[2]=0;
  arg1[3]=(&w21);
  arg1[4]=0;
  res1[0]=(&w23);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #28: @9 = vertcat(@12, @19, @23) */
  rr=w9;
  *rr++ = w12;
  *rr++ = w19;
  *rr++ = w23;
  /* #29: @12 = ||@9||_F */
  w12 = sqrt(casadi_dot(3, w9, w9));
  /* #30: @19 = input[0][1] */
  w19 = arg[0] ? arg[0][1] : 0;
  /* #31: @23 = (@12*@19) */
  w23  = (w12*w19);
  /* #32: @10 = (@10-@23) */
  w10 -= w23;
  /* #33: @0 = (@0/@10) */
  w0 /= w10;
  /* #34: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #35: @10 = 0 */
  w10 = 0.;
  /* #36: @24 = (@9/@12) */
  for (i=0, rr=w24, cr=w9; i<3; ++i) (*rr++)  = ((*cr++)/w12);
  /* #37: @25 = @24' */
  casadi_copy(w24, 3, w25);
  /* #38: @10 = mac(@25,@13,@10) */
  for (i=0, rr=(&w10); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w25+j, tt=w13+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #39: @26 = 00 */
  /* #40: @23 = 1 */
  w23 = 1.;
  /* #41: {@27, @28, @29, NULL, @30} = adj1_fwd1_jac_z_ref(@1, @6, @20, @21, @22, @26, @23) */
  arg1[0]=(&w1);
  arg1[1]=0;
  arg1[2]=0;
  arg1[3]=(&w21);
  arg1[4]=0;
  arg1[5]=0;
  arg1[6]=(&w23);
  res1[0]=(&w27);
  res1[1]=0;
  res1[2]=0;
  res1[3]=0;
  res1[4]=0;
  if (casadi_f7(arg1, res1, iw, w, 0)) return 1;
  /* #42: @31 = (@5*@27) */
  w31  = (w5*w27);
  /* #43: @32 = 00 */
  /* #44: @33 = 1 */
  w33 = 1.;
  /* #45: {@34, @35, @36, NULL, @37} = adj1_fwd1_jac_y_ref(@1, @4, @16, @17, @18, @32, @33) */
  arg1[0]=(&w1);
  arg1[1]=0;
  arg1[2]=0;
  arg1[3]=(&w17);
  arg1[4]=0;
  arg1[5]=0;
  arg1[6]=(&w33);
  res1[0]=(&w34);
  res1[1]=0;
  res1[2]=0;
  res1[3]=0;
  res1[4]=0;
  if (casadi_f8(arg1, res1, iw, w, 0)) return 1;
  /* #46: @38 = (@7*@34) */
  w38  = (w7*w34);
  /* #47: @31 = (@31-@38) */
  w31 -= w38;
  /* #48: @39 = 00 */
  /* #49: @38 = 1 */
  w38 = 1.;
  /* #50: {@40, @41, @42, NULL, @43} = adj1_fwd1_jac_x_ref(@1, @2, @14, @11, @15, @39, @38) */
  arg1[0]=(&w1);
  arg1[1]=0;
  arg1[2]=0;
  arg1[3]=(&w11);
  arg1[4]=0;
  arg1[5]=0;
  arg1[6]=(&w38);
  res1[0]=(&w40);
  res1[1]=0;
  res1[2]=0;
  res1[3]=0;
  res1[4]=0;
  if (casadi_f9(arg1, res1, iw, w, 0)) return 1;
  /* #51: @44 = (@7*@40) */
  w44  = (w7*w40);
  /* #52: @45 = (@3*@27) */
  w45  = (w3*w27);
  /* #53: @44 = (@44-@45) */
  w44 -= w45;
  /* #54: @45 = (@3*@34) */
  w45  = (w3*w34);
  /* #55: @46 = (@5*@40) */
  w46  = (w5*w40);
  /* #56: @45 = (@45-@46) */
  w45 -= w46;
  /* #57: @25 = vertcat(@31, @44, @45) */
  rr=w25;
  *rr++ = w31;
  *rr++ = w44;
  *rr++ = w45;
  /* #58: @25 = (@25/@12) */
  for (i=0, rr=w25; i<3; ++i) (*rr++) /= w12;
  /* #59: @31 = dot(@24, @25) */
  w31 = casadi_dot(3, w24, w25);
  /* #60: @44 = (@31*@0) */
  w44  = (w31*w0);
  /* #61: @45 = input[0][2] */
  w45 = arg[0] ? arg[0][2] : 0;
  /* #62: @44 = (@44*@45) */
  w44 *= w45;
  /* #63: @10 = (@10+@44) */
  w10 += w44;
  /* #64: output[0][1] = @10 */
  if (res[0]) res[0][1] = w10;
  /* #65: @44 = 0 */
  w44 = 0.;
  /* #66: @46 = @24[2] */
  for (rr=(&w46), ss=w24+2; ss!=w24+3; ss+=1) *rr++ = *ss;
  /* #67: @47 = (@5*@46) */
  w47  = (w5*w46);
  /* #68: @48 = @24[1] */
  for (rr=(&w48), ss=w24+1; ss!=w24+2; ss+=1) *rr++ = *ss;
  /* #69: @49 = (@7*@48) */
  w49  = (w7*w48);
  /* #70: @47 = (@47-@49) */
  w47 -= w49;
  /* #71: @49 = @24[0] */
  for (rr=(&w49), ss=w24+0; ss!=w24+1; ss+=1) *rr++ = *ss;
  /* #72: @50 = (@7*@49) */
  w50  = (w7*w49);
  /* #73: @46 = (@3*@46) */
  w46  = (w3*w46);
  /* #74: @50 = (@50-@46) */
  w50 -= w46;
  /* #75: @48 = (@3*@48) */
  w48  = (w3*w48);
  /* #76: @49 = (@5*@49) */
  w49  = (w5*w49);
  /* #77: @48 = (@48-@49) */
  w48 -= w49;
  /* #78: @51 = vertcat(@47, @50, @48) */
  rr=w51;
  *rr++ = w47;
  *rr++ = w50;
  *rr++ = w48;
  /* #79: @52 = @51' */
  casadi_copy(w51, 3, w52);
  /* #80: @44 = mac(@52,@13,@44) */
  for (i=0, rr=(&w44); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w52+j, tt=w13+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #81: @47 = (@31*@0) */
  w47  = (w31*w0);
  /* #82: @47 = (@47*@19) */
  w47 *= w19;
  /* #83: @44 = (@44-@47) */
  w44 -= w47;
  /* #84: output[0][2] = @44 */
  if (res[0]) res[0][2] = w44;
  /* #85: @47 = input[0][4] */
  w47 = arg[0] ? arg[0][4] : 0;
  /* #86: @50 = input[0][10] */
  w50 = arg[0] ? arg[0][10] : 0;
  /* #87: @48 = (@47*@50) */
  w48  = (w47*w50);
  /* #88: @48 = (-@48) */
  w48 = (- w48 );
  /* #89: @49 = input[0][5] */
  w49 = arg[0] ? arg[0][5] : 0;
  /* #90: @46 = input[0][11] */
  w46 = arg[0] ? arg[0][11] : 0;
  /* #91: @53 = (@49*@46) */
  w53  = (w49*w46);
  /* #92: @48 = (@48-@53) */
  w48 -= w53;
  /* #93: @53 = input[0][6] */
  w53 = arg[0] ? arg[0][6] : 0;
  /* #94: @54 = input[0][12] */
  w54 = arg[0] ? arg[0][12] : 0;
  /* #95: @55 = (@53*@54) */
  w55  = (w53*w54);
  /* #96: @48 = (@48-@55) */
  w48 -= w55;
  /* #97: @55 = 2 */
  w55 = 2.;
  /* #98: @48 = (@48/@55) */
  w48 /= w55;
  /* #99: output[0][3] = @48 */
  if (res[0]) res[0][3] = w48;
  /* #100: @48 = input[0][3] */
  w48 = arg[0] ? arg[0][3] : 0;
  /* #101: @55 = (@48*@50) */
  w55  = (w48*w50);
  /* #102: @56 = (@53*@46) */
  w56  = (w53*w46);
  /* #103: @55 = (@55-@56) */
  w55 -= w56;
  /* #104: @56 = (@49*@54) */
  w56  = (w49*w54);
  /* #105: @55 = (@55+@56) */
  w55 += w56;
  /* #106: @56 = 2 */
  w56 = 2.;
  /* #107: @55 = (@55/@56) */
  w55 /= w56;
  /* #108: output[0][4] = @55 */
  if (res[0]) res[0][4] = w55;
  /* #109: @55 = (@53*@50) */
  w55  = (w53*w50);
  /* #110: @56 = (@48*@46) */
  w56  = (w48*w46);
  /* #111: @55 = (@55+@56) */
  w55 += w56;
  /* #112: @56 = (@47*@54) */
  w56  = (w47*w54);
  /* #113: @55 = (@55-@56) */
  w55 -= w56;
  /* #114: @56 = 2 */
  w56 = 2.;
  /* #115: @55 = (@55/@56) */
  w55 /= w56;
  /* #116: output[0][5] = @55 */
  if (res[0]) res[0][5] = w55;
  /* #117: @55 = (@47*@46) */
  w55  = (w47*w46);
  /* #118: @56 = (@49*@50) */
  w56  = (w49*w50);
  /* #119: @55 = (@55-@56) */
  w55 -= w56;
  /* #120: @56 = (@48*@54) */
  w56  = (w48*w54);
  /* #121: @55 = (@55+@56) */
  w55 += w56;
  /* #122: @56 = 2 */
  w56 = 2.;
  /* #123: @55 = (@55/@56) */
  w55 /= w56;
  /* #124: output[0][6] = @55 */
  if (res[0]) res[0][6] = w55;
  /* #125: @55 = 0 */
  w55 = 0.;
  /* #126: @52 = @8' */
  casadi_copy(w8, 3, w52);
  /* #127: @57 = [-0, -0, -9.80665] */
  casadi_copy(casadi_c16, 3, w57);
  /* #128: @58 = zeros(3x1) */
  casadi_clear(w58, 3);
  /* #129: @56 = 32.2581 */
  w56 = 3.2258064516129032e+01;
  /* #130: @59 = sq(@48) */
  w59 = casadi_sq( w48 );
  /* #131: @60 = sq(@47) */
  w60 = casadi_sq( w47 );
  /* #132: @59 = (@59+@60) */
  w59 += w60;
  /* #133: @59 = (2.*@59) */
  w59 = (2.* w59 );
  /* #134: @60 = 1 */
  w60 = 1.;
  /* #135: @59 = (@59-@60) */
  w59 -= w60;
  /* #136: @60 = -2 */
  w60 = -2.;
  /* #137: @61 = (@48*@53) */
  w61  = (w48*w53);
  /* #138: @62 = (@47*@49) */
  w62  = (w47*w49);
  /* #139: @61 = (@61-@62) */
  w61 -= w62;
  /* #140: @60 = (@60*@61) */
  w60 *= w61;
  /* #141: @61 = (@48*@49) */
  w61  = (w48*w49);
  /* #142: @62 = (@47*@53) */
  w62  = (w47*w53);
  /* #143: @61 = (@61+@62) */
  w61 += w62;
  /* #144: @61 = (2.*@61) */
  w61 = (2.* w61 );
  /* #145: @63 = horzcat(@59, @60, @61) */
  rr=w63;
  *rr++ = w59;
  *rr++ = w60;
  *rr++ = w61;
  /* #146: @63 = @63' */
  /* #147: @59 = (@48*@53) */
  w59  = (w48*w53);
  /* #148: @60 = (@47*@49) */
  w60  = (w47*w49);
  /* #149: @59 = (@59+@60) */
  w59 += w60;
  /* #150: @59 = (2.*@59) */
  w59 = (2.* w59 );
  /* #151: @60 = sq(@48) */
  w60 = casadi_sq( w48 );
  /* #152: @61 = sq(@49) */
  w61 = casadi_sq( w49 );
  /* #153: @60 = (@60+@61) */
  w60 += w61;
  /* #154: @60 = (2.*@60) */
  w60 = (2.* w60 );
  /* #155: @61 = 1 */
  w61 = 1.;
  /* #156: @60 = (@60-@61) */
  w60 -= w61;
  /* #157: @61 = (@48*@47) */
  w61  = (w48*w47);
  /* #158: @62 = (@49*@53) */
  w62  = (w49*w53);
  /* #159: @61 = (@61-@62) */
  w61 -= w62;
  /* #160: @61 = (2.*@61) */
  w61 = (2.* w61 );
  /* #161: @64 = horzcat(@59, @60, @61) */
  rr=w64;
  *rr++ = w59;
  *rr++ = w60;
  *rr++ = w61;
  /* #162: @64 = @64' */
  /* #163: @59 = (@48*@49) */
  w59  = (w48*w49);
  /* #164: @60 = (@47*@53) */
  w60  = (w47*w53);
  /* #165: @59 = (@59-@60) */
  w59 -= w60;
  /* #166: @59 = (2.*@59) */
  w59 = (2.* w59 );
  /* #167: @47 = (@48*@47) */
  w47  = (w48*w47);
  /* #168: @49 = (@49*@53) */
  w49 *= w53;
  /* #169: @47 = (@47+@49) */
  w47 += w49;
  /* #170: @47 = (2.*@47) */
  w47 = (2.* w47 );
  /* #171: @48 = sq(@48) */
  w48 = casadi_sq( w48 );
  /* #172: @53 = sq(@53) */
  w53 = casadi_sq( w53 );
  /* #173: @48 = (@48+@53) */
  w48 += w53;
  /* #174: @48 = (2.*@48) */
  w48 = (2.* w48 );
  /* #175: @53 = 1 */
  w53 = 1.;
  /* #176: @48 = (@48-@53) */
  w48 -= w53;
  /* #177: @65 = horzcat(@59, @47, @48) */
  rr=w65;
  *rr++ = w59;
  *rr++ = w47;
  *rr++ = w48;
  /* #178: @65 = @65' */
  /* #179: @66 = horzcat(@63, @64, @65) */
  rr=w66;
  for (i=0, cs=w63; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w64; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w65; i<3; ++i) *rr++ = *cs++;
  /* #180: @67 = @66' */
  for (i=0, rr=w67, cs=w66; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #181: @67 = (@56*@67) */
  for (i=0, rr=w67, cs=w67; i<9; ++i) (*rr++)  = (w56*(*cs++));
  /* #182: @56 = 0.000325 */
  w56 = 3.2499999999999999e-04;
  /* #183: @59 = 0 */
  w59 = 0.;
  /* #184: @47 = 0 */
  w47 = 0.;
  /* #185: @48 = input[0][16] */
  w48 = arg[0] ? arg[0][16] : 0;
  /* #186: @53 = sq(@48) */
  w53 = casadi_sq( w48 );
  /* #187: @49 = input[0][17] */
  w49 = arg[0] ? arg[0][17] : 0;
  /* #188: @60 = sq(@49) */
  w60 = casadi_sq( w49 );
  /* #189: @53 = (@53+@60) */
  w53 += w60;
  /* #190: @60 = input[0][18] */
  w60 = arg[0] ? arg[0][18] : 0;
  /* #191: @61 = sq(@60) */
  w61 = casadi_sq( w60 );
  /* #192: @53 = (@53+@61) */
  w53 += w61;
  /* #193: @61 = input[0][19] */
  w61 = arg[0] ? arg[0][19] : 0;
  /* #194: @62 = sq(@61) */
  w62 = casadi_sq( w61 );
  /* #195: @53 = (@53+@62) */
  w53 += w62;
  /* #196: @63 = vertcat(@59, @47, @53) */
  rr=w63;
  *rr++ = w59;
  *rr++ = w47;
  *rr++ = w53;
  /* #197: @63 = (@56*@63) */
  for (i=0, rr=w63, cs=w63; i<3; ++i) (*rr++)  = (w56*(*cs++));
  /* #198: @58 = mac(@67,@63,@58) */
  for (i=0, rr=w58; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w67+j, tt=w63+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #199: @57 = (@57+@58) */
  for (i=0, rr=w57, cs=w58; i<3; ++i) (*rr++) += (*cs++);
  /* #200: @55 = mac(@52,@57,@55) */
  for (i=0, rr=(&w55); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w52+j, tt=w57+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #201: @56 = 0 */
  w56 = 0.;
  /* #202: @52 = (@9*@0) */
  for (i=0, rr=w52, cr=w9; i<3; ++i) (*rr++)  = ((*cr++)*w0);
  /* #203: @52 = @52' */
  /* #204: @56 = mac(@52,@13,@56) */
  for (i=0, rr=(&w56); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w52+j, tt=w13+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #205: @55 = (@55+@56) */
  w55 += w56;
  /* #206: @56 = 1 */
  w56 = 1.;
  /* #207: @59 = (@12*@19) */
  w59  = (w12*w19);
  /* #208: @56 = (@56-@59) */
  w56 -= w59;
  /* #209: @55 = (@55/@56) */
  w55 /= w56;
  /* #210: @56 = 0 */
  w56 = 0.;
  /* #211: @8 = @8' */
  /* #212: @56 = mac(@8,@13,@56) */
  for (i=0, rr=(&w56); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w8+j, tt=w13+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #213: @68 = 00 */
  /* #214: @59 = 1 */
  w59 = 1.;
  /* #215: @69 = 00 */
  /* #216: @70 = 00 */
  /* #217: @47 = 0 */
  w47 = 0.;
  /* #218: @71 = 00 */
  /* #219: @53 = fwd1_fwd1_jac_x_ref(@1, @2, @14, @11, @15, @68, @59, @69, @70, @47, @71) */
  arg1[0]=(&w1);
  arg1[1]=0;
  arg1[2]=0;
  arg1[3]=(&w11);
  arg1[4]=0;
  arg1[5]=0;
  arg1[6]=(&w59);
  arg1[7]=0;
  arg1[8]=0;
  arg1[9]=(&w47);
  arg1[10]=0;
  res1[0]=(&w53);
  if (casadi_f10(arg1, res1, iw, w, 0)) return 1;
  /* #220: @68 = 00 */
  /* #221: @69 = 00 */
  /* #222: @70 = 00 */
  /* #223: @47 = 0 */
  w47 = 0.;
  /* #224: @71 = 00 */
  /* #225: @62 = fwd1_fwd1_jac_y_ref(@1, @4, @16, @17, @18, @68, @59, @69, @70, @47, @71) */
  arg1[0]=(&w1);
  arg1[1]=0;
  arg1[2]=0;
  arg1[3]=(&w17);
  arg1[4]=0;
  arg1[5]=0;
  arg1[6]=(&w59);
  arg1[7]=0;
  arg1[8]=0;
  arg1[9]=(&w47);
  arg1[10]=0;
  res1[0]=(&w62);
  if (casadi_f11(arg1, res1, iw, w, 0)) return 1;
  /* #226: @68 = 00 */
  /* #227: @69 = 00 */
  /* #228: @70 = 00 */
  /* #229: @47 = 0 */
  w47 = 0.;
  /* #230: @71 = 00 */
  /* #231: @72 = fwd1_fwd1_jac_z_ref(@1, @6, @20, @21, @22, @68, @59, @69, @70, @47, @71) */
  arg1[0]=(&w1);
  arg1[1]=0;
  arg1[2]=0;
  arg1[3]=(&w21);
  arg1[4]=0;
  arg1[5]=0;
  arg1[6]=(&w59);
  arg1[7]=0;
  arg1[8]=0;
  arg1[9]=(&w47);
  arg1[10]=0;
  res1[0]=(&w72);
  if (casadi_f12(arg1, res1, iw, w, 0)) return 1;
  /* #232: @8 = vertcat(@53, @62, @72) */
  rr=w8;
  *rr++ = w53;
  *rr++ = w62;
  *rr++ = w72;
  /* #233: @53 = dot(@9, @8) */
  w53 = casadi_dot(3, w9, w8);
  /* #234: @53 = (@53/@12) */
  w53 /= w12;
  /* #235: @53 = (@53*@0) */
  w53 *= w0;
  /* #236: @53 = (@19*@53) */
  w53  = (w19*w53);
  /* #237: @62 = (@10*@12) */
  w62  = (w10*w12);
  /* #238: @53 = (@53+@62) */
  w53 += w62;
  /* #239: @62 = 1 */
  w62 = 1.;
  /* #240: @72 = (@12*@19) */
  w72  = (w12*w19);
  /* #241: @62 = (@62-@72) */
  w62 -= w72;
  /* #242: @62 = sq(@62) */
  w62 = casadi_sq( w62 );
  /* #243: @53 = (@53/@62) */
  w53 /= w62;
  /* #244: @56 = (@56*@53) */
  w56 *= w53;
  /* #245: @55 = (@55+@56) */
  w55 += w56;
  /* #246: output[0][7] = @55 */
  if (res[0]) res[0][7] = w55;
  /* #247: @56 = 0 */
  w56 = 0.;
  /* #248: @8 = @24' */
  casadi_copy(w24, 3, w8);
  /* #249: @56 = mac(@8,@57,@56) */
  for (i=0, rr=(&w56); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w8+j, tt=w57+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #250: @53 = 0 */
  w53 = 0.;
  /* #251: @62 = sq(@12) */
  w62 = casadi_sq( w12 );
  /* #252: @8 = vertcat(@40, @34, @27) */
  rr=w8;
  *rr++ = w40;
  *rr++ = w34;
  *rr++ = w27;
  /* #253: @52 = (@62*@8) */
  for (i=0, rr=w52, cs=w8; i<3; ++i) (*rr++)  = (w62*(*cs++));
  /* #254: @58 = zeros(3x1) */
  casadi_clear(w58, 3);
  /* #255: @67 = zeros(3x3) */
  casadi_clear(w67, 9);
  /* #256: @8 = @8' */
  /* #257: @67 = mac(@9,@8,@67) */
  for (i=0, rr=w67; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w9+j, tt=w8+i*1; k<1; ++k) *rr += ss[k*3]**tt++;
  /* #258: @58 = mac(@67,@9,@58) */
  for (i=0, rr=w58; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w67+j, tt=w9+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #259: @52 = (@52-@58) */
  for (i=0, rr=w52, cs=w58; i<3; ++i) (*rr++) -= (*cs++);
  /* #260: @62 = 3 */
  w62 = 3.;
  /* #261: @62 = pow(@12,@62) */
  w62  = pow(w12,w62);
  /* #262: @52 = (@52/@62) */
  for (i=0, rr=w52; i<3; ++i) (*rr++) /= w62;
  /* #263: @52 = (@52*@0) */
  for (i=0, rr=w52; i<3; ++i) (*rr++) *= w0;
  /* #264: @52 = @52' */
  /* #265: @53 = mac(@52,@13,@53) */
  for (i=0, rr=(&w53); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w52+j, tt=w13+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #266: @56 = (@56+@53) */
  w56 += w53;
  /* #267: @68 = 00 */
  /* #268: @53 = 1 */
  w53 = 1.;
  /* #269: @69 = 00 */
  /* #270: @62 = fwd1_jac_y_ref(@1, @4, @68, @53, @69) */
  arg1[0]=(&w1);
  arg1[1]=0;
  arg1[2]=0;
  arg1[3]=(&w53);
  arg1[4]=0;
  res1[0]=(&w62);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #271: @72 = (@27*@62) */
  w72  = (w27*w62);
  /* #272: @68 = 00 */
  /* #273: @70 = 00 */
  /* #274: @71 = 00 */
  /* #275: @73 = 00 */
  /* #276: @59 = 0 */
  w59 = 0.;
  /* #277: @74 = 00 */
  /* #278: @75 = 00 */
  /* #279: @47 = 0 */
  w47 = 0.;
  /* #280: {@76, NULL, NULL, NULL, NULL} = fwd1_adj1_fwd1_jac_z_ref(@1, @6, @20, @21, @22, @26, @23, @68, @28, @29, @70, @30, @53, @71, @73, @59, @74, @75, @47) */
  arg1[0]=(&w1);
  arg1[1]=0;
  arg1[2]=0;
  arg1[3]=(&w21);
  arg1[4]=0;
  arg1[5]=0;
  arg1[6]=(&w23);
  arg1[7]=0;
  arg1[8]=0;
  arg1[9]=0;
  arg1[10]=0;
  arg1[11]=0;
  arg1[12]=(&w53);
  arg1[13]=0;
  arg1[14]=0;
  arg1[15]=(&w59);
  arg1[16]=0;
  arg1[17]=0;
  arg1[18]=(&w47);
  res1[0]=(&w76);
  res1[1]=0;
  res1[2]=0;
  res1[3]=0;
  res1[4]=0;
  if (casadi_f13(arg1, res1, iw, w, 0)) return 1;
  /* #281: @23 = (@5*@76) */
  w23  = (w5*w76);
  /* #282: @72 = (@72+@23) */
  w72 += w23;
  /* #283: @26 = 00 */
  /* #284: @23 = fwd1_jac_z_ref(@1, @6, @26, @53, @71) */
  arg1[0]=(&w1);
  arg1[1]=0;
  arg1[2]=0;
  arg1[3]=(&w53);
  arg1[4]=0;
  res1[0]=(&w23);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #285: @59 = (@34*@23) */
  w59  = (w34*w23);
  /* #286: @26 = 00 */
  /* #287: @68 = 00 */
  /* #288: @28 = 00 */
  /* #289: @47 = 0 */
  w47 = 0.;
  /* #290: @29 = 00 */
  /* #291: @70 = 00 */
  /* #292: @77 = 0 */
  w77 = 0.;
  /* #293: {@78, NULL, NULL, NULL, NULL} = fwd1_adj1_fwd1_jac_y_ref(@1, @4, @16, @17, @18, @32, @33, @26, @35, @36, @68, @37, @53, @69, @28, @47, @29, @70, @77) */
  arg1[0]=(&w1);
  arg1[1]=0;
  arg1[2]=0;
  arg1[3]=(&w17);
  arg1[4]=0;
  arg1[5]=0;
  arg1[6]=(&w33);
  arg1[7]=0;
  arg1[8]=0;
  arg1[9]=0;
  arg1[10]=0;
  arg1[11]=0;
  arg1[12]=(&w53);
  arg1[13]=0;
  arg1[14]=0;
  arg1[15]=(&w47);
  arg1[16]=0;
  arg1[17]=0;
  arg1[18]=(&w77);
  res1[0]=(&w78);
  res1[1]=0;
  res1[2]=0;
  res1[3]=0;
  res1[4]=0;
  if (casadi_f14(arg1, res1, iw, w, 0)) return 1;
  /* #294: @33 = (@7*@78) */
  w33  = (w7*w78);
  /* #295: @59 = (@59+@33) */
  w59 += w33;
  /* #296: @72 = (@72-@59) */
  w72 -= w59;
  /* #297: @23 = (@40*@23) */
  w23  = (w40*w23);
  /* #298: @32 = 00 */
  /* #299: @26 = 00 */
  /* #300: @35 = 00 */
  /* #301: @36 = 00 */
  /* #302: @59 = 0 */
  w59 = 0.;
  /* #303: @68 = 00 */
  /* #304: @37 = 00 */
  /* #305: @33 = 0 */
  w33 = 0.;
  /* #306: {@47, NULL, NULL, NULL, NULL} = fwd1_adj1_fwd1_jac_x_ref(@1, @2, @14, @11, @15, @39, @38, @32, @41, @42, @26, @43, @53, @35, @36, @59, @68, @37, @33) */
  arg1[0]=(&w1);
  arg1[1]=0;
  arg1[2]=0;
  arg1[3]=(&w11);
  arg1[4]=0;
  arg1[5]=0;
  arg1[6]=(&w38);
  arg1[7]=0;
  arg1[8]=0;
  arg1[9]=0;
  arg1[10]=0;
  arg1[11]=0;
  arg1[12]=(&w53);
  arg1[13]=0;
  arg1[14]=0;
  arg1[15]=(&w59);
  arg1[16]=0;
  arg1[17]=0;
  arg1[18]=(&w33);
  res1[0]=(&w47);
  res1[1]=0;
  res1[2]=0;
  res1[3]=0;
  res1[4]=0;
  if (casadi_f15(arg1, res1, iw, w, 0)) return 1;
  /* #307: @7 = (@7*@47) */
  w7 *= w47;
  /* #308: @23 = (@23+@7) */
  w23 += w7;
  /* #309: @39 = 00 */
  /* #310: @7 = fwd1_jac_x_ref(@1, @2, @39, @53, @35) */
  arg1[0]=(&w1);
  arg1[1]=0;
  arg1[2]=0;
  arg1[3]=(&w53);
  arg1[4]=0;
  res1[0]=(&w7);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #311: @27 = (@27*@7) */
  w27 *= w7;
  /* #312: @76 = (@3*@76) */
  w76  = (w3*w76);
  /* #313: @27 = (@27+@76) */
  w27 += w76;
  /* #314: @23 = (@23-@27) */
  w23 -= w27;
  /* #315: @34 = (@34*@7) */
  w34 *= w7;
  /* #316: @3 = (@3*@78) */
  w3 *= w78;
  /* #317: @34 = (@34+@3) */
  w34 += w3;
  /* #318: @40 = (@40*@62) */
  w40 *= w62;
  /* #319: @5 = (@5*@47) */
  w5 *= w47;
  /* #320: @40 = (@40+@5) */
  w40 += w5;
  /* #321: @34 = (@34-@40) */
  w34 -= w40;
  /* #322: @52 = vertcat(@72, @23, @34) */
  rr=w52;
  *rr++ = w72;
  *rr++ = w23;
  *rr++ = w34;
  /* #323: @52 = (@52/@12) */
  for (i=0, rr=w52; i<3; ++i) (*rr++) /= w12;
  /* #324: @58 = (@25/@12) */
  for (i=0, rr=w58, cr=w25; i<3; ++i) (*rr++)  = ((*cr++)/w12);
  /* #325: @39 = 00 */
  /* #326: @72 = 0 */
  w72 = 0.;
  /* #327: @23 = fwd1_fwd1_jac_x_ref(@1, @2, @14, @11, @15, @39, @53, @35, @36, @72, @68) */
  arg1[0]=(&w1);
  arg1[1]=0;
  arg1[2]=0;
  arg1[3]=(&w11);
  arg1[4]=0;
  arg1[5]=0;
  arg1[6]=(&w53);
  arg1[7]=0;
  arg1[8]=0;
  arg1[9]=(&w72);
  arg1[10]=0;
  res1[0]=(&w23);
  if (casadi_f10(arg1, res1, iw, w, 0)) return 1;
  /* #328: @2 = 00 */
  /* #329: @11 = 0 */
  w11 = 0.;
  /* #330: @72 = fwd1_fwd1_jac_y_ref(@1, @4, @16, @17, @18, @2, @53, @69, @28, @11, @29) */
  arg1[0]=(&w1);
  arg1[1]=0;
  arg1[2]=0;
  arg1[3]=(&w17);
  arg1[4]=0;
  arg1[5]=0;
  arg1[6]=(&w53);
  arg1[7]=0;
  arg1[8]=0;
  arg1[9]=(&w11);
  arg1[10]=0;
  res1[0]=(&w72);
  if (casadi_f11(arg1, res1, iw, w, 0)) return 1;
  /* #331: @4 = 00 */
  /* #332: @17 = 0 */
  w17 = 0.;
  /* #333: @11 = fwd1_fwd1_jac_z_ref(@1, @6, @20, @21, @22, @4, @53, @71, @73, @17, @74) */
  arg1[0]=(&w1);
  arg1[1]=0;
  arg1[2]=0;
  arg1[3]=(&w21);
  arg1[4]=0;
  arg1[5]=0;
  arg1[6]=(&w53);
  arg1[7]=0;
  arg1[8]=0;
  arg1[9]=(&w17);
  arg1[10]=0;
  res1[0]=(&w11);
  if (casadi_f12(arg1, res1, iw, w, 0)) return 1;
  /* #334: @8 = vertcat(@23, @72, @11) */
  rr=w8;
  *rr++ = w23;
  *rr++ = w72;
  *rr++ = w11;
  /* #335: @23 = dot(@9, @8) */
  w23 = casadi_dot(3, w9, w8);
  /* #336: @23 = (@23/@12) */
  w23 /= w12;
  /* #337: @58 = (@58*@23) */
  for (i=0, rr=w58; i<3; ++i) (*rr++) *= w23;
  /* #338: @52 = (@52-@58) */
  for (i=0, rr=w52, cs=w58; i<3; ++i) (*rr++) -= (*cs++);
  /* #339: @72 = dot(@24, @52) */
  w72 = casadi_dot(3, w24, w52);
  /* #340: @8 = (@8/@12) */
  for (i=0, rr=w8; i<3; ++i) (*rr++) /= w12;
  /* #341: @24 = (@24/@12) */
  for (i=0, rr=w24; i<3; ++i) (*rr++) /= w12;
  /* #342: @24 = (@24*@23) */
  for (i=0, rr=w24; i<3; ++i) (*rr++) *= w23;
  /* #343: @8 = (@8-@24) */
  for (i=0, rr=w8, cs=w24; i<3; ++i) (*rr++) -= (*cs++);
  /* #344: @23 = dot(@8, @25) */
  w23 = casadi_dot(3, w8, w25);
  /* #345: @72 = (@72+@23) */
  w72 += w23;
  /* #346: @72 = (@72*@0) */
  w72 *= w0;
  /* #347: @23 = (@72*@0) */
  w23  = (w72*w0);
  /* #348: @23 = (@23*@45) */
  w23 *= w45;
  /* #349: @56 = (@56+@23) */
  w56 += w23;
  /* #350: @23 = (@31*@55) */
  w23  = (w31*w55);
  /* #351: @23 = (@23*@45) */
  w23 *= w45;
  /* #352: @56 = (@56+@23) */
  w56 += w23;
  /* #353: @23 = (@31*@0) */
  w23  = (w31*w0);
  /* #354: @23 = (@23*@44) */
  w23 *= w44;
  /* #355: @56 = (@56+@23) */
  w56 += w23;
  /* #356: output[0][8] = @56 */
  if (res[0]) res[0][8] = w56;
  /* #357: @56 = 0 */
  w56 = 0.;
  /* #358: @51 = @51' */
  /* #359: @56 = mac(@51,@57,@56) */
  for (i=0, rr=(&w56); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w51+j, tt=w57+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #360: @23 = 0 */
  w23 = 0.;
  /* #361: @25 = (@25*@0) */
  for (i=0, rr=w25; i<3; ++i) (*rr++) *= w0;
  /* #362: @25 = @25' */
  /* #363: @23 = mac(@25,@13,@23) */
  for (i=0, rr=(&w23); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w25+j, tt=w13+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #364: @56 = (@56+@23) */
  w56 += w23;
  /* #365: @72 = (@72*@0) */
  w72 *= w0;
  /* #366: @72 = (@72*@19) */
  w72 *= w19;
  /* #367: @56 = (@56-@72) */
  w56 -= w72;
  /* #368: @55 = (@31*@55) */
  w55  = (w31*w55);
  /* #369: @55 = (@55*@19) */
  w55 *= w19;
  /* #370: @56 = (@56-@55) */
  w56 -= w55;
  /* #371: @31 = (@31*@0) */
  w31 *= w0;
  /* #372: @31 = (@31*@10) */
  w31 *= w10;
  /* #373: @56 = (@56-@31) */
  w56 -= w31;
  /* #374: output[0][9] = @56 */
  if (res[0]) res[0][9] = w56;
  /* #375: @25 = zeros(3x1) */
  casadi_clear(w25, 3);
  /* #376: @13 = 
  [[71684.6, 00, 00], 
   [00, 71684.6, 00], 
   [00, 00, 46019.3]] */
  casadi_copy(casadi_c17, 3, w13);
  /* #377: @56 = 1.495e-05 */
  w56 = 1.4949999999999999e-05;
  /* #378: @31 = sq(@48) */
  w31 = casadi_sq( w48 );
  /* #379: @10 = sq(@49) */
  w10 = casadi_sq( w49 );
  /* #380: @31 = (@31+@10) */
  w31 += w10;
  /* #381: @10 = sq(@60) */
  w10 = casadi_sq( w60 );
  /* #382: @31 = (@31-@10) */
  w31 -= w10;
  /* #383: @10 = sq(@61) */
  w10 = casadi_sq( w61 );
  /* #384: @31 = (@31-@10) */
  w31 -= w10;
  /* #385: @56 = (@56*@31) */
  w56 *= w31;
  /* #386: @31 = 1.495e-05 */
  w31 = 1.4949999999999999e-05;
  /* #387: @10 = sq(@48) */
  w10 = casadi_sq( w48 );
  /* #388: @0 = sq(@49) */
  w0 = casadi_sq( w49 );
  /* #389: @10 = (@10-@0) */
  w10 -= w0;
  /* #390: @0 = sq(@60) */
  w0 = casadi_sq( w60 );
  /* #391: @10 = (@10-@0) */
  w10 -= w0;
  /* #392: @0 = sq(@61) */
  w0 = casadi_sq( w61 );
  /* #393: @10 = (@10+@0) */
  w10 += w0;
  /* #394: @31 = (@31*@10) */
  w31 *= w10;
  /* #395: @10 = 7.9379e-06 */
  w10 = 7.9379000000000007e-06;
  /* #396: @48 = sq(@48) */
  w48 = casadi_sq( w48 );
  /* #397: @49 = sq(@49) */
  w49 = casadi_sq( w49 );
  /* #398: @48 = (@48-@49) */
  w48 -= w49;
  /* #399: @60 = sq(@60) */
  w60 = casadi_sq( w60 );
  /* #400: @48 = (@48+@60) */
  w48 += w60;
  /* #401: @61 = sq(@61) */
  w61 = casadi_sq( w61 );
  /* #402: @48 = (@48-@61) */
  w48 -= w61;
  /* #403: @10 = (@10*@48) */
  w10 *= w48;
  /* #404: @51 = vertcat(@56, @31, @10) */
  rr=w51;
  *rr++ = w56;
  *rr++ = w31;
  *rr++ = w10;
  /* #405: @8 = zeros(3x1) */
  casadi_clear(w8, 3);
  /* #406: @67 = 
  [[1.395e-05, 0, 0], 
   [0, 1.395e-05, 0], 
   [0, 0, 2.173e-05]] */
  casadi_copy(casadi_c18, 9, w67);
  /* #407: @24 = vertcat(@50, @46, @54) */
  rr=w24;
  *rr++ = w50;
  *rr++ = w46;
  *rr++ = w54;
  /* #408: @8 = mac(@67,@24,@8) */
  for (i=0, rr=w8; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w67+j, tt=w24+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #409: @56 = @8[2] */
  for (rr=(&w56), ss=w8+2; ss!=w8+3; ss+=1) *rr++ = *ss;
  /* #410: @31 = (@46*@56) */
  w31  = (w46*w56);
  /* #411: @10 = @8[1] */
  for (rr=(&w10), ss=w8+1; ss!=w8+2; ss+=1) *rr++ = *ss;
  /* #412: @48 = (@54*@10) */
  w48  = (w54*w10);
  /* #413: @31 = (@31-@48) */
  w31 -= w48;
  /* #414: @48 = @8[0] */
  for (rr=(&w48), ss=w8+0; ss!=w8+1; ss+=1) *rr++ = *ss;
  /* #415: @54 = (@54*@48) */
  w54 *= w48;
  /* #416: @56 = (@50*@56) */
  w56  = (w50*w56);
  /* #417: @54 = (@54-@56) */
  w54 -= w56;
  /* #418: @50 = (@50*@10) */
  w50 *= w10;
  /* #419: @46 = (@46*@48) */
  w46 *= w48;
  /* #420: @50 = (@50-@46) */
  w50 -= w46;
  /* #421: @8 = vertcat(@31, @54, @50) */
  rr=w8;
  *rr++ = w31;
  *rr++ = w54;
  *rr++ = w50;
  /* #422: @51 = (@51-@8) */
  for (i=0, rr=w51, cs=w8; i<3; ++i) (*rr++) -= (*cs++);
  /* #423: @25 = mac(@13,@51,@25) */
  casadi_mtimes(w13, casadi_s10, w51, casadi_s9, w25, casadi_s9, w, 0);
  /* #424: @31 = @25[0] */
  for (rr=(&w31), ss=w25+0; ss!=w25+1; ss+=1) *rr++ = *ss;
  /* #425: output[0][10] = @31 */
  if (res[0]) res[0][10] = w31;
  /* #426: @31 = @25[1] */
  for (rr=(&w31), ss=w25+1; ss!=w25+2; ss+=1) *rr++ = *ss;
  /* #427: output[0][11] = @31 */
  if (res[0]) res[0][11] = w31;
  /* #428: @31 = @25[2] */
  for (rr=(&w31), ss=w25+2; ss!=w25+3; ss+=1) *rr++ = *ss;
  /* #429: output[0][12] = @31 */
  if (res[0]) res[0][12] = w31;
  /* #430: @31 = @57[0] */
  for (rr=(&w31), ss=w57+0; ss!=w57+1; ss+=1) *rr++ = *ss;
  /* #431: output[0][13] = @31 */
  if (res[0]) res[0][13] = w31;
  /* #432: @31 = @57[1] */
  for (rr=(&w31), ss=w57+1; ss!=w57+2; ss+=1) *rr++ = *ss;
  /* #433: output[0][14] = @31 */
  if (res[0]) res[0][14] = w31;
  /* #434: @31 = @57[2] */
  for (rr=(&w31), ss=w57+2; ss!=w57+3; ss+=1) *rr++ = *ss;
  /* #435: output[0][15] = @31 */
  if (res[0]) res[0][15] = w31;
  /* #436: @31 = input[1][0] */
  w31 = arg[1] ? arg[1][0] : 0;
  /* #437: output[0][16] = @31 */
  if (res[0]) res[0][16] = w31;
  /* #438: @31 = input[1][1] */
  w31 = arg[1] ? arg[1][1] : 0;
  /* #439: output[0][17] = @31 */
  if (res[0]) res[0][17] = w31;
  /* #440: @31 = input[1][2] */
  w31 = arg[1] ? arg[1][2] : 0;
  /* #441: output[0][18] = @31 */
  if (res[0]) res[0][18] = w31;
  /* #442: @31 = input[1][3] */
  w31 = arg[1] ? arg[1][3] : 0;
  /* #443: output[0][19] = @31 */
  if (res[0]) res[0][19] = w31;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_expl_ode_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_expl_ode_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_expl_ode_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s11;
    case 1: return casadi_s12;
    case 2: return casadi_s13;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s11;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 24;
  if (sz_res) *sz_res = 7;
  if (sz_iw) *sz_iw = 6;
  if (sz_w) *sz_w = 108;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
