/* This file was automatically generated by CasADi 3.6.5.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c10 CASADI_PREFIX(c10)
#define casadi_c11 CASADI_PREFIX(c11)
#define casadi_c12 CASADI_PREFIX(c12)
#define casadi_c13 CASADI_PREFIX(c13)
#define casadi_c14 CASADI_PREFIX(c14)
#define casadi_c15 CASADI_PREFIX(c15)
#define casadi_c16 CASADI_PREFIX(c16)
#define casadi_c17 CASADI_PREFIX(c17)
#define casadi_c18 CASADI_PREFIX(c18)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_c3 CASADI_PREFIX(c3)
#define casadi_c4 CASADI_PREFIX(c4)
#define casadi_c5 CASADI_PREFIX(c5)
#define casadi_c6 CASADI_PREFIX(c6)
#define casadi_c7 CASADI_PREFIX(c7)
#define casadi_c8 CASADI_PREFIX(c8)
#define casadi_c9 CASADI_PREFIX(c9)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_clear_casadi_int CASADI_PREFIX(clear_casadi_int)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_de_boor CASADI_PREFIX(de_boor)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f10 CASADI_PREFIX(f10)
#define casadi_f11 CASADI_PREFIX(f11)
#define casadi_f12 CASADI_PREFIX(f12)
#define casadi_f13 CASADI_PREFIX(f13)
#define casadi_f14 CASADI_PREFIX(f14)
#define casadi_f15 CASADI_PREFIX(f15)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_f4 CASADI_PREFIX(f4)
#define casadi_f5 CASADI_PREFIX(f5)
#define casadi_f6 CASADI_PREFIX(f6)
#define casadi_f7 CASADI_PREFIX(f7)
#define casadi_f8 CASADI_PREFIX(f8)
#define casadi_f9 CASADI_PREFIX(f9)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_fill_casadi_int CASADI_PREFIX(fill_casadi_int)
#define casadi_low CASADI_PREFIX(low)
#define casadi_nd_boor_eval CASADI_PREFIX(nd_boor_eval)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_de_boor(casadi_real x, const casadi_real* knots, casadi_int n_knots, casadi_int degree, casadi_real* boor) {
  casadi_int d, i;
  for (d=1;d<degree+1;++d) {
    for (i=0;i<n_knots-d-1;++i) {
      casadi_real b, bottom;
      b = 0;
      bottom = knots[i + d] - knots[i];
      if (bottom) b = (x - knots[i]) * boor[i] / bottom;
      bottom = knots[i + d + 1] - knots[i + 1];
      if (bottom) b += (knots[i + d + 1] - x) * boor[i + 1] / bottom;
      boor[i] = b;
    }
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_fill_casadi_int(casadi_int* x, casadi_int n, casadi_int alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_clear_casadi_int(casadi_int* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_int casadi_low(casadi_real x, const casadi_real* grid, casadi_int ng, casadi_int lookup_mode) {
  switch (lookup_mode) {
    case 1:
      {
        casadi_real g0, dg;
        casadi_int ret;
        g0 = grid[0];
        dg = grid[ng-1]-g0;
        ret = (casadi_int) ((x-g0)*(ng-1)/dg);
        if (ret<0) ret=0;
        if (ret>ng-2) ret=ng-2;
        return ret;
      }
    case 2:
      {
        casadi_int start, stop, pivot;
        if (ng<2 || x<grid[1]) return 0;
        if (x>grid[ng-1]) return ng-2;
        start = 0;
        stop  = ng-1;
        while (1) {
          pivot = (stop+start)/2;
          if (x < grid[pivot]) {
            if (pivot==stop) return pivot;
            stop = pivot;
          } else {
            if (pivot==start) return pivot;
            start = pivot;
          }
        }
      }
    default:
      {
        casadi_int i;
        for (i=0; i<ng-2; ++i) {
          if (x < grid[i+1]) break;
        }
        return i;
      }
  }
}

void casadi_nd_boor_eval(casadi_real* ret, casadi_int n_dims, const casadi_real* all_knots, const casadi_int* offset, const casadi_int* all_degree, const casadi_int* strides, const casadi_real* c, casadi_int m, const casadi_real* all_x, const casadi_int* lookup_mode, casadi_int* iw, casadi_real* w) {
  casadi_int n_iter, k, i, pivot;
  casadi_int *boor_offset, *starts, *index, *coeff_offset;
  casadi_real *cumprod, *all_boor;
  boor_offset = iw; iw+=n_dims+1;
  starts = iw; iw+=n_dims;
  index = iw; iw+=n_dims;
  coeff_offset = iw;
  cumprod = w; w+= n_dims+1;
  all_boor = w;
  boor_offset[0] = 0;
  cumprod[n_dims] = 1;
  coeff_offset[n_dims] = 0;
  n_iter = 1;
  for (k=0;k<n_dims;++k) {
    casadi_real *boor;
    const casadi_real* knots;
    casadi_real x;
    casadi_int degree, n_knots, n_b, L, start;
    boor = all_boor+boor_offset[k];
    degree = all_degree[k];
    knots = all_knots + offset[k];
    n_knots = offset[k+1]-offset[k];
    n_b = n_knots-degree-1;
    x = all_x[k];
    L = casadi_low(x, knots+degree, n_knots-2*degree, lookup_mode[k]);
    start = L;
    if (start>n_b-degree-1) start = n_b-degree-1;
    starts[k] = start;
    casadi_clear(boor, 2*degree+1);
    if (x>=knots[0] && x<=knots[n_knots-1]) {
      if (x==knots[1]) {
        casadi_fill(boor, degree+1, 1.0);
      } else if (x==knots[n_knots-1]) {
        boor[degree] = 1;
      } else if (knots[L+degree]==x) {
        boor[degree-1] = 1;
      } else {
        boor[degree] = 1;
      }
    }
    casadi_de_boor(x, knots+start, 2*degree+2, degree, boor);
    boor+= degree+1;
    n_iter*= degree+1;
    boor_offset[k+1] = boor_offset[k] + degree+1;
  }
  casadi_clear_casadi_int(index, n_dims);
  for (pivot=n_dims-1;pivot>=0;--pivot) {
    cumprod[pivot] = (*(all_boor+boor_offset[pivot]))*cumprod[pivot+1];
    coeff_offset[pivot] = starts[pivot]*strides[pivot]+coeff_offset[pivot+1];
  }
  for (k=0;k<n_iter;++k) {
    casadi_int pivot = 0;
    for (i=0;i<m;++i) ret[i] += c[coeff_offset[0]+i]*cumprod[0];
    index[0]++;
    {
      while (index[pivot]==boor_offset[pivot+1]-boor_offset[pivot]) {
        index[pivot] = 0;
        if (pivot==n_dims-1) break;
        index[++pivot]++;
      }
      while (pivot>0) {
        cumprod[pivot] = (*(all_boor+boor_offset[pivot]+index[pivot]))*cumprod[pivot+1];
        coeff_offset[pivot] = (starts[pivot]+index[pivot])*strides[pivot]+coeff_offset[pivot+1];
        pivot--;
      }
    }
    cumprod[0] = (*(all_boor+index[0]))*cumprod[1];
    coeff_offset[0] = (starts[0]+index[0])*m+coeff_offset[1];
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[2] = {0, 33};
static const casadi_int casadi_s1[1] = {4};
static const casadi_int casadi_s2[1] = {1};
static const casadi_int casadi_s3[1] = {0};
static const casadi_int casadi_s4[2] = {0, 31};
static const casadi_int casadi_s5[1] = {3};
static const casadi_int casadi_s6[2] = {0, 29};
static const casadi_int casadi_s7[1] = {2};
static const casadi_int casadi_s8[2] = {0, 27};
static const casadi_int casadi_s9[24] = {20, 1, 0, 20, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19};
static const casadi_int casadi_s10[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s11[3] = {0, 0, 0};

static const casadi_real casadi_c0[33] = {0., 0., 0., 0., 0., 6., 8., 10., 12., 14., 16., 18., 20., 22., 24., 26., 28., 30., 32., 34., 36., 38., 40., 42., 44., 46., 48., 50., 56., 56., 56., 56., 56.};
static const casadi_real casadi_c1[28] = {-9.9999999999998979e-02, -1.0000000000000953e-01, -9.9999999999987210e-02, -1.0000000000000497e-01, -1.0000000000000059e-01, -1.0000000000000397e-01, -9.9999999999993955e-02, -9.9999999999998174e-02, -1.0000000000000726e-01, -9.9999999999997216e-02, -9.9999999999997286e-02, -9.9999999999998423e-02, -1.0000000000000697e-01, -1.0000000000000125e-01, -9.9999999999993094e-02, -9.9999999999998646e-02, -1.0000000000000386e-01, -1.0000000000000131e-01, -9.9999999999998757e-02, -9.9999999999998757e-02, -1.0000000000000386e-01, -9.9999999999995426e-02, -9.9999999999999645e-02, -1.0000000000000286e-01, -9.9999999999998757e-02, -9.9999999999999867e-02, -9.9999999999998312e-02, -1.0000000000000187e-01};
static const casadi_real casadi_c2[28] = {-9.0880503150606029e-02, -9.9717481349238968e-02, -1.6477737307952822e-01, 5.6906229032410716e-02, -2.0613928393059089e-02, 2.5223711295584761e-02, -4.8347899755757151e-02, 9.7176409802997687e-02, 2.9172163710049603e-02, 5.9702378895329034e-02, 4.4136588735981808e-02, 5.6439019508211230e-02, 3.8136621223080203e-02, 7.6218874627274724e-02, -1.0258836981940744e-02, 1.8829286482201540e-01, -2.3835860609649373e-01, -3.9494432840894267e-02, -1.2683239215855152e-01, -8.6694342691972959e-02, -1.0979534758473219e-01, -8.6357716163386056e-02, -1.2732113700951941e-01, -4.8667791073966016e-02, 5.9814263112749844e-02, -6.2672559500441705e-02, 5.3251906392025594e-02, -2.4929017035884682e-02};
static const casadi_real casadi_c3[28] = {1.3322676295501878e-15, -9.9920072216264089e-16, 1.1102230246251565e-16, -1.9984014443252818e-15, -9.9920072216264089e-16, 2.6645352591003757e-15, 4.2188474935755949e-15, -3.3306690738754696e-16, -2.8865798640254070e-15, -2.1094237467877974e-15, 1.9984014443252818e-15, 8.8817841970012523e-16, -2.2204460492503131e-15, -1.4432899320127035e-15, 2.5535129566378600e-15, 2.4424906541753444e-15, -1.1102230246251565e-15, -3.3306690738754696e-15, -2.3314683517128287e-15, 6.6613381477509392e-16, 1.8873791418627661e-15, 4.4408920985006262e-16, -2.9976021664879227e-15, 1.7208456881689926e-15, 2.7755575615628914e-15, 1.7763568394002505e-15, -8.8817841970012523e-16, -6.9944050551384862e-15};
static const casadi_real casadi_c4[31] = {0., 0., 0., 0., 6., 8., 10., 12., 14., 16., 18., 20., 22., 24., 26., 28., 30., 32., 34., 36., 38., 40., 42., 44., 46., 48., 50., 56., 56., 56., 56.};
static const casadi_real casadi_c5[27] = {-7.0221606307541151e-15, 1.1157741397482823e-14, -7.1054273576010019e-15, 1.4641066137244252e-15, -1.6930901125533637e-15, 5.0098813986210189e-15, -2.1094237467877974e-15, -4.5449755070592346e-15, 5.0237591864288333e-15, -3.4694469519536142e-17, -5.6898930012039273e-16, -4.2743586448068527e-15, 2.8588242884097781e-15, 4.0800696154974503e-15, -2.7755575615628914e-15, -2.6090241078691179e-15, 1.2767564783189300e-15, 1.2767564783189300e-15, 0., -2.5535129566378600e-15, 4.2188474935755949e-15, -2.1094237467877974e-15, -1.6098233857064770e-15, 1.3669620990697240e-15, -4.4408920985006262e-16, 7.7715611723760958e-16, -2.3592239273284576e-15};
static const casadi_real casadi_c6[27] = {-5.8913187990886212e-03, -3.2529945865144627e-02, 8.8673440844775575e-02, -2.5840052475156597e-02, 2.2918819844321925e-02, -3.6785805525670956e-02, 7.2762154779377419e-02, -3.4002123046474042e-02, 1.5265107592639715e-02, -7.7828950796736129e-03, 6.1512153861147112e-03, -9.1511991425655137e-03, 1.9041126702097261e-02, -4.3238855804607734e-02, 9.9275850901978074e-02, -2.1332573545925457e-01, 9.9432086627799732e-02, -4.3668979658828627e-02, 2.0069024733289281e-02, -1.1550502446379618e-02, 1.1718815710673069e-02, -2.0481710423066679e-02, 3.9326672967776699e-02, 3.6160684728905282e-02, -4.8994729045276623e-02, 5.7962232946233649e-02, -5.2120615618606848e-02};
static const casadi_real casadi_c7[27] = {-1.5543122344752192e-15, 5.5511151231257827e-16, -8.4376949871511903e-16, 3.3306690738754696e-16, 1.8318679906315083e-15, 7.7715611723760958e-16, -2.2759572004815709e-15, -1.2767564783189300e-15, 3.8857805861880479e-16, 2.0539125955565396e-15, -5.5511151231257827e-16, -1.5543122344752192e-15, 3.8857805861880479e-16, 1.9984014443252818e-15, -5.5511151231257827e-17, -1.7763568394002505e-15, -1.1102230246251565e-15, 4.9960036108132044e-16, 1.4988010832439613e-15, 6.1062266354383610e-16, -7.2164496600635175e-16, -1.7208456881689926e-15, 2.3592239273284576e-15, 3.5157062446463284e-16, -3.9968028886505632e-16, -1.3322676295501878e-15, -4.0708177569589071e-15};
static const casadi_real casadi_c8[29] = {0., 0., 0., 6., 8., 10., 12., 14., 16., 18., 20., 22., 24., 26., 28., 30., 32., 34., 36., 38., 40., 42., 44., 46., 48., 50., 56., 56., 56.};
static const casadi_real casadi_c9[26] = {1.0547118733938987e-15, -5.2458037913538643e-16, 3.5305092183079985e-16, 7.4940054162198066e-16, -5.2735593669694936e-16, -1.5265566588595902e-15, 4.9960036108132044e-16, 8.3266726846886741e-16, 8.3266726846886741e-16, -1.3045120539345589e-15, -4.9960036108132044e-16, 9.7144514654701197e-16, 8.0491169285323849e-16, -1.0269562977782698e-15, -8.6042284408449632e-16, 3.3306690738754696e-16, 8.0491169285323849e-16, 4.9960036108132044e-16, -4.4408920985006262e-16, -6.6613381477509392e-16, -4.9960036108132044e-16, 2.0400348077487251e-15, -1.0038266514319125e-15, -2.2537527399890681e-16, -3.4972025275692435e-16, -1.3692750637043596e-15};
static const casadi_real casadi_c10[26] = {-1.3319313533028003e-02, 4.5451270016220076e-02, -3.4354047995979659e-02, 2.4379436159739261e-02, -2.9852312684996440e-02, 5.4773980152524188e-02, -5.3382138912925731e-02, 2.4633615319556879e-02, -1.1524001336156664e-02, 6.9670552328941621e-03, -7.6512072643401124e-03, 1.4096162922331387e-02, -3.1139991253352498e-02, 7.1257353353292904e-02, -1.5630079318061632e-01, 1.5637891104352714e-01, -7.1550533143314179e-02, 3.1869002196058954e-02, -1.5809763589834450e-02, 1.1634659078526344e-02, -1.6100263066869874e-02, 2.9904191695421689e-02, -1.5829941194357086e-03, -2.5546624132254576e-02, 4.0108860746816355e-02, -5.5041424282420245e-02};
static const casadi_real casadi_c11[26] = {9.0899510141184692e-15, -6.8486882831564344e-15, 2.5708601913976285e-15, -1.5785983631388945e-15, 3.3514857555871913e-15, -3.5596525727044082e-15, -1.2177758801357186e-15, 4.7843673467440340e-15, -2.5292268279741847e-15, -2.6714741530042829e-16, -1.8526846723432300e-15, 3.5665914666083154e-15, 6.1062266354383610e-16, -3.4278135885301708e-15, 8.3266726846886741e-17, 1.9428902930940239e-15, 0., -6.3837823915946501e-16, -1.2767564783189300e-15, 3.3861802251067274e-15, -3.1641356201816961e-15, 2.4980018054066022e-16, 1.4883927423881005e-15, -5.4331539267593606e-16, 4.5796699765787707e-16, -1.5681900222830336e-15};
static const casadi_real casadi_c12[27] = {0., 0., 6., 8., 10., 12., 14., 16., 18., 20., 22., 24., 26., 28., 30., 32., 34., 36., 38., 40., 42., 44., 46., 48., 50., 56., 56.};
static const casadi_real casadi_c13[25] = {-5.2643075084309501e-16, 2.1940782524154657e-16, 1.9817480989559041e-16, -6.3837823915946501e-16, -4.9960036108132044e-16, 1.0130785099704553e-15, 1.6653345369377348e-16, 0., -1.0685896612017132e-15, 4.0245584642661925e-16, 7.3552275381416621e-16, -8.3266726846886741e-17, -9.1593399531575415e-16, 8.3266726846886741e-17, 5.9674487573602164e-16, 2.3592239273284576e-16, -1.5265566588595902e-16, -4.7184478546569153e-16, -1.1102230246251565e-16, 8.3266726846886741e-17, 1.2698175844150228e-15, -1.5219307295903188e-15, 3.8922568871650285e-16, -3.1086244689504386e-17, -3.3985160364914512e-16};
static const casadi_real casadi_c14[25] = {1.9590194516416026e-02, -1.9951329503049932e-02, 2.9366742077859460e-02, -2.7115874422367851e-02, 4.2313146418760314e-02, -5.4078059532724959e-02, 3.9007877116241305e-02, -1.8078808327856771e-02, 9.2455282845254130e-03, -7.3091312486171373e-03, 1.0873685093335750e-02, -2.2618077087841942e-02, 5.1198672303322701e-02, -1.1377907326695461e-01, 1.5633985211207174e-01, -1.1396472209342065e-01, 5.1709767669686567e-02, -2.3839382892946702e-02, 1.3722211334180397e-02, -1.3867461072698109e-02, 2.3002227381145782e-02, -1.5743592907428699e-02, -1.1981815006409434e-02, 1.6413871219767732e-02, -3.1716761676412200e-02};
static const casadi_real casadi_c15[25] = {-5.3128797657583009e-15, 2.3548871186385156e-15, -2.0747292772682613e-15, 2.4650420593630429e-15, -3.4555691641457997e-15, 1.1709383462843448e-15, 3.0010716134398763e-15, -3.6567970873591094e-15, 1.1310397063368782e-15, -7.9276862852140084e-16, 2.7096380694757727e-15, -1.4779844015322396e-15, -2.0192181260370035e-15, 1.7555401576885288e-15, 9.2981178312356860e-16, -9.7144514654701197e-16, -3.1918911957973251e-16, -3.1918911957973251e-16, 2.3314683517128287e-15, -3.2751579226442118e-15, 1.7069679003611782e-15, 6.1929628092372013e-16, -1.0158540675320183e-15, 2.5032059758345328e-16, -6.7538567331363686e-16};
static const casadi_real casadi_c16[3] = {0., 0., -9.8066499999999994e+00};
static const casadi_real casadi_c17[3] = {7.1684587813620077e+04, 7.1684587813620077e+04, 4.6019328117809477e+04};
static const casadi_real casadi_c18[9] = {1.3950000000000000e-05, 0., 0., 0., 1.3950000000000000e-05, 0., 0., 0., 2.1730000000000000e-05};

/* jac_x_ref:(x,out_f[1x1,0nz])->(jac_f_x) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c0,casadi_s0,casadi_s1,casadi_s2,casadi_c1,1,(&w0),casadi_s3, iw, w);
  /* #2: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

/* jac_y_ref:(x,out_f[1x1,0nz])->(jac_f_x) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c0,casadi_s0,casadi_s1,casadi_s2,casadi_c2,1,(&w0),casadi_s3, iw, w);
  /* #2: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

/* jac_z_ref:(x,out_f[1x1,0nz])->(jac_f_x) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c0,casadi_s0,casadi_s1,casadi_s2,casadi_c3,1,(&w0),casadi_s3, iw, w);
  /* #2: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

/* fwd1_jac_x_ref:(x,out_f[1x1,0nz],out_jac_f_x[1x1,0nz],fwd_x,fwd_out_f[1x1,0nz])->(fwd_jac_f_x) */
static int casadi_f4(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c4,casadi_s4,casadi_s5,casadi_s2,casadi_c5,1,(&w0),casadi_s3, iw, w);
  /* #2: @0 = input[3][0] */
  w0 = arg[3] ? arg[3][0] : 0;
  /* #3: @1 = (@1*@0) */
  w1 *= w0;
  /* #4: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

/* fwd1_jac_y_ref:(x,out_f[1x1,0nz],out_jac_f_x[1x1,0nz],fwd_x,fwd_out_f[1x1,0nz])->(fwd_jac_f_x) */
static int casadi_f5(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c4,casadi_s4,casadi_s5,casadi_s2,casadi_c6,1,(&w0),casadi_s3, iw, w);
  /* #2: @0 = input[3][0] */
  w0 = arg[3] ? arg[3][0] : 0;
  /* #3: @1 = (@1*@0) */
  w1 *= w0;
  /* #4: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

/* fwd1_jac_z_ref:(x,out_f[1x1,0nz],out_jac_f_x[1x1,0nz],fwd_x,fwd_out_f[1x1,0nz])->(fwd_jac_f_x) */
static int casadi_f6(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c4,casadi_s4,casadi_s5,casadi_s2,casadi_c7,1,(&w0),casadi_s3, iw, w);
  /* #2: @0 = input[3][0] */
  w0 = arg[3] ? arg[3][0] : 0;
  /* #3: @1 = (@1*@0) */
  w1 *= w0;
  /* #4: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

/* adj1_fwd1_jac_z_ref:(x,out_f[1x1,0nz],out_jac_f_x[1x1,0nz],fwd_x,fwd_out_f[1x1,0nz],out_fwd_jac_f_x[1x1,0nz],adj_fwd_jac_f_x)->(adj_x,adj_out_f[1x1,0nz],adj_out_jac_f_x[1x1,0nz],adj_fwd_x,adj_fwd_out_f[1x1,0nz]) */
static int casadi_f7(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, w2, w3;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c8,casadi_s6,casadi_s7,casadi_s2,casadi_c9,1,(&w0),casadi_s3, iw, w);
  /* #2: @2 = input[3][0] */
  w2 = arg[3] ? arg[3][0] : 0;
  /* #3: @3 = input[6][0] */
  w3 = arg[6] ? arg[6][0] : 0;
  /* #4: @2 = (@2*@3) */
  w2 *= w3;
  /* #5: @1 = (@1*@2) */
  w1 *= w2;
  /* #6: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  /* #7: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c4,casadi_s4,casadi_s5,casadi_s2,casadi_c7,1,(&w0),casadi_s3, iw, w);
  /* #8: @1 = (@1*@3) */
  w1 *= w3;
  /* #9: output[3][0] = @1 */
  if (res[3]) res[3][0] = w1;
  return 0;
}

/* adj1_fwd1_jac_y_ref:(x,out_f[1x1,0nz],out_jac_f_x[1x1,0nz],fwd_x,fwd_out_f[1x1,0nz],out_fwd_jac_f_x[1x1,0nz],adj_fwd_jac_f_x)->(adj_x,adj_out_f[1x1,0nz],adj_out_jac_f_x[1x1,0nz],adj_fwd_x,adj_fwd_out_f[1x1,0nz]) */
static int casadi_f8(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, w2, w3;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c8,casadi_s6,casadi_s7,casadi_s2,casadi_c10,1,(&w0),casadi_s3, iw, w);
  /* #2: @2 = input[3][0] */
  w2 = arg[3] ? arg[3][0] : 0;
  /* #3: @3 = input[6][0] */
  w3 = arg[6] ? arg[6][0] : 0;
  /* #4: @2 = (@2*@3) */
  w2 *= w3;
  /* #5: @1 = (@1*@2) */
  w1 *= w2;
  /* #6: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  /* #7: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c4,casadi_s4,casadi_s5,casadi_s2,casadi_c6,1,(&w0),casadi_s3, iw, w);
  /* #8: @1 = (@1*@3) */
  w1 *= w3;
  /* #9: output[3][0] = @1 */
  if (res[3]) res[3][0] = w1;
  return 0;
}

/* adj1_fwd1_jac_x_ref:(x,out_f[1x1,0nz],out_jac_f_x[1x1,0nz],fwd_x,fwd_out_f[1x1,0nz],out_fwd_jac_f_x[1x1,0nz],adj_fwd_jac_f_x)->(adj_x,adj_out_f[1x1,0nz],adj_out_jac_f_x[1x1,0nz],adj_fwd_x,adj_fwd_out_f[1x1,0nz]) */
static int casadi_f9(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, w2, w3;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c8,casadi_s6,casadi_s7,casadi_s2,casadi_c11,1,(&w0),casadi_s3, iw, w);
  /* #2: @2 = input[3][0] */
  w2 = arg[3] ? arg[3][0] : 0;
  /* #3: @3 = input[6][0] */
  w3 = arg[6] ? arg[6][0] : 0;
  /* #4: @2 = (@2*@3) */
  w2 *= w3;
  /* #5: @1 = (@1*@2) */
  w1 *= w2;
  /* #6: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  /* #7: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c4,casadi_s4,casadi_s5,casadi_s2,casadi_c5,1,(&w0),casadi_s3, iw, w);
  /* #8: @1 = (@1*@3) */
  w1 *= w3;
  /* #9: output[3][0] = @1 */
  if (res[3]) res[3][0] = w1;
  return 0;
}

/* fwd1_fwd1_jac_x_ref:(x,out_f[1x1,0nz],out_jac_f_x[1x1,0nz],fwd_x,fwd_out_f[1x1,0nz],out_fwd_jac_f_x[1x1,0nz],fwd2_x,fwd2_out_f[1x1,0nz],fwd2_out_jac_f_x[1x1,0nz],fwd2_fwd_x,fwd2_fwd_out_f[1x1,0nz])->(fwd2_fwd_jac_f_x) */
static int casadi_f10(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, w2, w3;
  /* #0: @0 = input[3][0] */
  w0 = arg[3] ? arg[3][0] : 0;
  /* #1: @1 = input[0][0] */
  w1 = arg[0] ? arg[0][0] : 0;
  /* #2: @2 = BSpline(@1) */
  casadi_clear((&w2), 1);
  CASADI_PREFIX(nd_boor_eval)((&w2),1,casadi_c8,casadi_s6,casadi_s7,casadi_s2,casadi_c11,1,(&w1),casadi_s3, iw, w);
  /* #3: @3 = input[6][0] */
  w3 = arg[6] ? arg[6][0] : 0;
  /* #4: @2 = (@2*@3) */
  w2 *= w3;
  /* #5: @0 = (@0*@2) */
  w0 *= w2;
  /* #6: @2 = BSpline(@1) */
  casadi_clear((&w2), 1);
  CASADI_PREFIX(nd_boor_eval)((&w2),1,casadi_c4,casadi_s4,casadi_s5,casadi_s2,casadi_c5,1,(&w1),casadi_s3, iw, w);
  /* #7: @1 = input[9][0] */
  w1 = arg[9] ? arg[9][0] : 0;
  /* #8: @2 = (@2*@1) */
  w2 *= w1;
  /* #9: @0 = (@0+@2) */
  w0 += w2;
  /* #10: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  return 0;
}

/* fwd1_fwd1_jac_y_ref:(x,out_f[1x1,0nz],out_jac_f_x[1x1,0nz],fwd_x,fwd_out_f[1x1,0nz],out_fwd_jac_f_x[1x1,0nz],fwd2_x,fwd2_out_f[1x1,0nz],fwd2_out_jac_f_x[1x1,0nz],fwd2_fwd_x,fwd2_fwd_out_f[1x1,0nz])->(fwd2_fwd_jac_f_x) */
static int casadi_f11(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, w2, w3;
  /* #0: @0 = input[3][0] */
  w0 = arg[3] ? arg[3][0] : 0;
  /* #1: @1 = input[0][0] */
  w1 = arg[0] ? arg[0][0] : 0;
  /* #2: @2 = BSpline(@1) */
  casadi_clear((&w2), 1);
  CASADI_PREFIX(nd_boor_eval)((&w2),1,casadi_c8,casadi_s6,casadi_s7,casadi_s2,casadi_c10,1,(&w1),casadi_s3, iw, w);
  /* #3: @3 = input[6][0] */
  w3 = arg[6] ? arg[6][0] : 0;
  /* #4: @2 = (@2*@3) */
  w2 *= w3;
  /* #5: @0 = (@0*@2) */
  w0 *= w2;
  /* #6: @2 = BSpline(@1) */
  casadi_clear((&w2), 1);
  CASADI_PREFIX(nd_boor_eval)((&w2),1,casadi_c4,casadi_s4,casadi_s5,casadi_s2,casadi_c6,1,(&w1),casadi_s3, iw, w);
  /* #7: @1 = input[9][0] */
  w1 = arg[9] ? arg[9][0] : 0;
  /* #8: @2 = (@2*@1) */
  w2 *= w1;
  /* #9: @0 = (@0+@2) */
  w0 += w2;
  /* #10: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  return 0;
}

/* fwd1_fwd1_jac_z_ref:(x,out_f[1x1,0nz],out_jac_f_x[1x1,0nz],fwd_x,fwd_out_f[1x1,0nz],out_fwd_jac_f_x[1x1,0nz],fwd2_x,fwd2_out_f[1x1,0nz],fwd2_out_jac_f_x[1x1,0nz],fwd2_fwd_x,fwd2_fwd_out_f[1x1,0nz])->(fwd2_fwd_jac_f_x) */
static int casadi_f12(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, w2, w3;
  /* #0: @0 = input[3][0] */
  w0 = arg[3] ? arg[3][0] : 0;
  /* #1: @1 = input[0][0] */
  w1 = arg[0] ? arg[0][0] : 0;
  /* #2: @2 = BSpline(@1) */
  casadi_clear((&w2), 1);
  CASADI_PREFIX(nd_boor_eval)((&w2),1,casadi_c8,casadi_s6,casadi_s7,casadi_s2,casadi_c9,1,(&w1),casadi_s3, iw, w);
  /* #3: @3 = input[6][0] */
  w3 = arg[6] ? arg[6][0] : 0;
  /* #4: @2 = (@2*@3) */
  w2 *= w3;
  /* #5: @0 = (@0*@2) */
  w0 *= w2;
  /* #6: @2 = BSpline(@1) */
  casadi_clear((&w2), 1);
  CASADI_PREFIX(nd_boor_eval)((&w2),1,casadi_c4,casadi_s4,casadi_s5,casadi_s2,casadi_c7,1,(&w1),casadi_s3, iw, w);
  /* #7: @1 = input[9][0] */
  w1 = arg[9] ? arg[9][0] : 0;
  /* #8: @2 = (@2*@1) */
  w2 *= w1;
  /* #9: @0 = (@0+@2) */
  w0 += w2;
  /* #10: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  return 0;
}

/* fwd1_adj1_fwd1_jac_z_ref:(x,out_f[1x1,0nz],out_jac_f_x[1x1,0nz],fwd_x,fwd_out_f[1x1,0nz],out_fwd_jac_f_x[1x1,0nz],adj_fwd_jac_f_x,out_adj_x[1x1,0nz],out_adj_out_f[1x1,0nz],out_adj_out_jac_f_x[1x1,0nz],out_adj_fwd_x[1x1,0nz],out_adj_fwd_out_f[1x1,0nz],fwd2_x,fwd2_out_f[1x1,0nz],fwd2_out_jac_f_x[1x1,0nz],fwd2_fwd_x,fwd2_fwd_out_f[1x1,0nz],fwd2_out_fwd_jac_f_x[1x1,0nz],fwd2_adj_fwd_jac_f_x)->(fwd2_adj_x,fwd2_adj_out_f[1x1,0nz],fwd2_adj_out_jac_f_x[1x1,0nz],fwd2_adj_fwd_x,fwd2_adj_fwd_out_f[1x1,0nz]) */
static int casadi_f13(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, w2, w3, w4, w5, w6, w7;
  /* #0: @0 = input[3][0] */
  w0 = arg[3] ? arg[3][0] : 0;
  /* #1: @1 = input[6][0] */
  w1 = arg[6] ? arg[6][0] : 0;
  /* #2: @2 = (@0*@1) */
  w2  = (w0*w1);
  /* #3: @3 = input[0][0] */
  w3 = arg[0] ? arg[0][0] : 0;
  /* #4: @4 = BSpline(@3) */
  casadi_clear((&w4), 1);
  CASADI_PREFIX(nd_boor_eval)((&w4),1,casadi_c12,casadi_s8,casadi_s2,casadi_s2,casadi_c13,1,(&w3),casadi_s3, iw, w);
  /* #5: @5 = input[12][0] */
  w5 = arg[12] ? arg[12][0] : 0;
  /* #6: @4 = (@4*@5) */
  w4 *= w5;
  /* #7: @2 = (@2*@4) */
  w2 *= w4;
  /* #8: @4 = BSpline(@3) */
  casadi_clear((&w4), 1);
  CASADI_PREFIX(nd_boor_eval)((&w4),1,casadi_c8,casadi_s6,casadi_s7,casadi_s2,casadi_c9,1,(&w3),casadi_s3, iw, w);
  /* #9: @6 = input[15][0] */
  w6 = arg[15] ? arg[15][0] : 0;
  /* #10: @6 = (@1*@6) */
  w6  = (w1*w6);
  /* #11: @7 = input[18][0] */
  w7 = arg[18] ? arg[18][0] : 0;
  /* #12: @0 = (@0*@7) */
  w0 *= w7;
  /* #13: @6 = (@6+@0) */
  w6 += w0;
  /* #14: @6 = (@4*@6) */
  w6  = (w4*w6);
  /* #15: @2 = (@2+@6) */
  w2 += w6;
  /* #16: output[0][0] = @2 */
  if (res[0]) res[0][0] = w2;
  /* #17: @4 = (@4*@5) */
  w4 *= w5;
  /* #18: @1 = (@1*@4) */
  w1 *= w4;
  /* #19: @4 = BSpline(@3) */
  casadi_clear((&w4), 1);
  CASADI_PREFIX(nd_boor_eval)((&w4),1,casadi_c4,casadi_s4,casadi_s5,casadi_s2,casadi_c7,1,(&w3),casadi_s3, iw, w);
  /* #20: @4 = (@4*@7) */
  w4 *= w7;
  /* #21: @1 = (@1+@4) */
  w1 += w4;
  /* #22: output[3][0] = @1 */
  if (res[3]) res[3][0] = w1;
  return 0;
}

/* fwd1_adj1_fwd1_jac_y_ref:(x,out_f[1x1,0nz],out_jac_f_x[1x1,0nz],fwd_x,fwd_out_f[1x1,0nz],out_fwd_jac_f_x[1x1,0nz],adj_fwd_jac_f_x,out_adj_x[1x1,0nz],out_adj_out_f[1x1,0nz],out_adj_out_jac_f_x[1x1,0nz],out_adj_fwd_x[1x1,0nz],out_adj_fwd_out_f[1x1,0nz],fwd2_x,fwd2_out_f[1x1,0nz],fwd2_out_jac_f_x[1x1,0nz],fwd2_fwd_x,fwd2_fwd_out_f[1x1,0nz],fwd2_out_fwd_jac_f_x[1x1,0nz],fwd2_adj_fwd_jac_f_x)->(fwd2_adj_x,fwd2_adj_out_f[1x1,0nz],fwd2_adj_out_jac_f_x[1x1,0nz],fwd2_adj_fwd_x,fwd2_adj_fwd_out_f[1x1,0nz]) */
static int casadi_f14(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, w2, w3, w4, w5, w6, w7;
  /* #0: @0 = input[3][0] */
  w0 = arg[3] ? arg[3][0] : 0;
  /* #1: @1 = input[6][0] */
  w1 = arg[6] ? arg[6][0] : 0;
  /* #2: @2 = (@0*@1) */
  w2  = (w0*w1);
  /* #3: @3 = input[0][0] */
  w3 = arg[0] ? arg[0][0] : 0;
  /* #4: @4 = BSpline(@3) */
  casadi_clear((&w4), 1);
  CASADI_PREFIX(nd_boor_eval)((&w4),1,casadi_c12,casadi_s8,casadi_s2,casadi_s2,casadi_c14,1,(&w3),casadi_s3, iw, w);
  /* #5: @5 = input[12][0] */
  w5 = arg[12] ? arg[12][0] : 0;
  /* #6: @4 = (@4*@5) */
  w4 *= w5;
  /* #7: @2 = (@2*@4) */
  w2 *= w4;
  /* #8: @4 = BSpline(@3) */
  casadi_clear((&w4), 1);
  CASADI_PREFIX(nd_boor_eval)((&w4),1,casadi_c8,casadi_s6,casadi_s7,casadi_s2,casadi_c10,1,(&w3),casadi_s3, iw, w);
  /* #9: @6 = input[15][0] */
  w6 = arg[15] ? arg[15][0] : 0;
  /* #10: @6 = (@1*@6) */
  w6  = (w1*w6);
  /* #11: @7 = input[18][0] */
  w7 = arg[18] ? arg[18][0] : 0;
  /* #12: @0 = (@0*@7) */
  w0 *= w7;
  /* #13: @6 = (@6+@0) */
  w6 += w0;
  /* #14: @6 = (@4*@6) */
  w6  = (w4*w6);
  /* #15: @2 = (@2+@6) */
  w2 += w6;
  /* #16: output[0][0] = @2 */
  if (res[0]) res[0][0] = w2;
  /* #17: @4 = (@4*@5) */
  w4 *= w5;
  /* #18: @1 = (@1*@4) */
  w1 *= w4;
  /* #19: @4 = BSpline(@3) */
  casadi_clear((&w4), 1);
  CASADI_PREFIX(nd_boor_eval)((&w4),1,casadi_c4,casadi_s4,casadi_s5,casadi_s2,casadi_c6,1,(&w3),casadi_s3, iw, w);
  /* #20: @4 = (@4*@7) */
  w4 *= w7;
  /* #21: @1 = (@1+@4) */
  w1 += w4;
  /* #22: output[3][0] = @1 */
  if (res[3]) res[3][0] = w1;
  return 0;
}

/* fwd1_adj1_fwd1_jac_x_ref:(x,out_f[1x1,0nz],out_jac_f_x[1x1,0nz],fwd_x,fwd_out_f[1x1,0nz],out_fwd_jac_f_x[1x1,0nz],adj_fwd_jac_f_x,out_adj_x[1x1,0nz],out_adj_out_f[1x1,0nz],out_adj_out_jac_f_x[1x1,0nz],out_adj_fwd_x[1x1,0nz],out_adj_fwd_out_f[1x1,0nz],fwd2_x,fwd2_out_f[1x1,0nz],fwd2_out_jac_f_x[1x1,0nz],fwd2_fwd_x,fwd2_fwd_out_f[1x1,0nz],fwd2_out_fwd_jac_f_x[1x1,0nz],fwd2_adj_fwd_jac_f_x)->(fwd2_adj_x,fwd2_adj_out_f[1x1,0nz],fwd2_adj_out_jac_f_x[1x1,0nz],fwd2_adj_fwd_x,fwd2_adj_fwd_out_f[1x1,0nz]) */
static int casadi_f15(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, w2, w3, w4, w5, w6, w7;
  /* #0: @0 = input[3][0] */
  w0 = arg[3] ? arg[3][0] : 0;
  /* #1: @1 = input[6][0] */
  w1 = arg[6] ? arg[6][0] : 0;
  /* #2: @2 = (@0*@1) */
  w2  = (w0*w1);
  /* #3: @3 = input[0][0] */
  w3 = arg[0] ? arg[0][0] : 0;
  /* #4: @4 = BSpline(@3) */
  casadi_clear((&w4), 1);
  CASADI_PREFIX(nd_boor_eval)((&w4),1,casadi_c12,casadi_s8,casadi_s2,casadi_s2,casadi_c15,1,(&w3),casadi_s3, iw, w);
  /* #5: @5 = input[12][0] */
  w5 = arg[12] ? arg[12][0] : 0;
  /* #6: @4 = (@4*@5) */
  w4 *= w5;
  /* #7: @2 = (@2*@4) */
  w2 *= w4;
  /* #8: @4 = BSpline(@3) */
  casadi_clear((&w4), 1);
  CASADI_PREFIX(nd_boor_eval)((&w4),1,casadi_c8,casadi_s6,casadi_s7,casadi_s2,casadi_c11,1,(&w3),casadi_s3, iw, w);
  /* #9: @6 = input[15][0] */
  w6 = arg[15] ? arg[15][0] : 0;
  /* #10: @6 = (@1*@6) */
  w6  = (w1*w6);
  /* #11: @7 = input[18][0] */
  w7 = arg[18] ? arg[18][0] : 0;
  /* #12: @0 = (@0*@7) */
  w0 *= w7;
  /* #13: @6 = (@6+@0) */
  w6 += w0;
  /* #14: @6 = (@4*@6) */
  w6  = (w4*w6);
  /* #15: @2 = (@2+@6) */
  w2 += w6;
  /* #16: output[0][0] = @2 */
  if (res[0]) res[0][0] = w2;
  /* #17: @4 = (@4*@5) */
  w4 *= w5;
  /* #18: @1 = (@1*@4) */
  w1 *= w4;
  /* #19: @4 = BSpline(@3) */
  casadi_clear((&w4), 1);
  CASADI_PREFIX(nd_boor_eval)((&w4),1,casadi_c4,casadi_s4,casadi_s5,casadi_s2,casadi_c5,1,(&w3),casadi_s3, iw, w);
  /* #20: @4 = (@4*@7) */
  w4 *= w7;
  /* #21: @1 = (@1+@4) */
  w1 += w4;
  /* #22: output[3][0] = @1 */
  if (res[3]) res[3][0] = w1;
  return 0;
}

/* quadrotor_expl_ode_fun:(i0[20],i1[4],i2[])->(o0[20]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real **res1=res+1, *rr, *ss, *tt;
  const casadi_real **arg1=arg+3, *cr, *cs;
  casadi_real w0, w1, w3, w5, w7, *w8=w+22, *w9=w+25, w10, w11, w12, *w13=w+31, w17, w19, w21, w23, *w24=w+38, *w25=w+41, w27, w28, w30, w31, w32, w34, w35, w36, w37, w38, w39, w40, w41, *w42=w+57, *w43=w+60, w44, w45, w46, w47, *w48=w+67, *w49=w+70, w50, w51, w52, w53, *w54=w+77, *w55=w+80, *w56=w+83, *w57=w+86, *w58=w+95, w63, w70, w72, w73;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: @1 = input[0][0] */
  w1 = arg[0] ? arg[0][0] : 0;
  /* #2: @2 = 00 */
  /* #3: @3 = jac_x_ref(@1, @2) */
  arg1[0]=(&w1);
  arg1[1]=0;
  res1[0]=(&w3);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #4: @4 = 00 */
  /* #5: @5 = jac_y_ref(@1, @4) */
  arg1[0]=(&w1);
  arg1[1]=0;
  res1[0]=(&w5);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #6: @6 = 00 */
  /* #7: @7 = jac_z_ref(@1, @6) */
  arg1[0]=(&w1);
  arg1[1]=0;
  res1[0]=(&w7);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #8: @8 = vertcat(@3, @5, @7) */
  rr=w8;
  *rr++ = w3;
  *rr++ = w5;
  *rr++ = w7;
  /* #9: @9 = @8' */
  casadi_copy(w8, 3, w9);
  /* #10: @10 = input[0][13] */
  w10 = arg[0] ? arg[0][13] : 0;
  /* #11: @11 = input[0][14] */
  w11 = arg[0] ? arg[0][14] : 0;
  /* #12: @12 = input[0][15] */
  w12 = arg[0] ? arg[0][15] : 0;
  /* #13: @13 = vertcat(@10, @11, @12) */
  rr=w13;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  /* #14: @0 = mac(@9,@13,@0) */
  for (i=0, rr=(&w0); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w9+j, tt=w13+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #15: @10 = 1 */
  w10 = 1.;
  /* #16: @14 = 00 */
  /* #17: @11 = 1 */
  w11 = 1.;
  /* #18: @15 = 00 */
  /* #19: @12 = fwd1_jac_x_ref(@1, @2, @14, @11, @15) */
  arg1[0]=(&w1);
  arg1[1]=0;
  arg1[2]=0;
  arg1[3]=(&w11);
  arg1[4]=0;
  res1[0]=(&w12);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #20: @16 = 00 */
  /* #21: @17 = 1 */
  w17 = 1.;
  /* #22: @18 = 00 */
  /* #23: @19 = fwd1_jac_y_ref(@1, @4, @16, @17, @18) */
  arg1[0]=(&w1);
  arg1[1]=0;
  arg1[2]=0;
  arg1[3]=(&w17);
  arg1[4]=0;
  res1[0]=(&w19);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #24: @20 = 00 */
  /* #25: @21 = 1 */
  w21 = 1.;
  /* #26: @22 = 00 */
  /* #27: @23 = fwd1_jac_z_ref(@1, @6, @20, @21, @22) */
  arg1[0]=(&w1);
  arg1[1]=0;
  arg1[2]=0;
  arg1[3]=(&w21);
  arg1[4]=0;
  res1[0]=(&w23);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #28: @9 = vertcat(@12, @19, @23) */
  rr=w9;
  *rr++ = w12;
  *rr++ = w19;
  *rr++ = w23;
  /* #29: @12 = ||@9||_F */
  w12 = sqrt(casadi_dot(3, w9, w9));
  /* #30: @19 = input[0][1] */
  w19 = arg[0] ? arg[0][1] : 0;
  /* #31: @23 = (@12*@19) */
  w23  = (w12*w19);
  /* #32: @10 = (@10-@23) */
  w10 -= w23;
  /* #33: @0 = (@0/@10) */
  w0 /= w10;
  /* #34: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #35: @10 = 0 */
  w10 = 0.;
  /* #36: @24 = (@9/@12) */
  for (i=0, rr=w24, cr=w9; i<3; ++i) (*rr++)  = ((*cr++)/w12);
  /* #37: @25 = @24' */
  casadi_copy(w24, 3, w25);
  /* #38: @10 = mac(@25,@13,@10) */
  for (i=0, rr=(&w10); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w25+j, tt=w13+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #39: @26 = 00 */
  /* #40: @23 = 1 */
  w23 = 1.;
  /* #41: {@27, NULL, NULL, NULL, NULL} = adj1_fwd1_jac_z_ref(@1, @6, @20, @21, @22, @26, @23) */
  arg1[0]=(&w1);
  arg1[1]=0;
  arg1[2]=0;
  arg1[3]=(&w21);
  arg1[4]=0;
  arg1[5]=0;
  arg1[6]=(&w23);
  res1[0]=(&w27);
  res1[1]=0;
  res1[2]=0;
  res1[3]=0;
  res1[4]=0;
  if (casadi_f7(arg1, res1, iw, w, 0)) return 1;
  /* #42: @28 = (@5*@27) */
  w28  = (w5*w27);
  /* #43: @29 = 00 */
  /* #44: @30 = 1 */
  w30 = 1.;
  /* #45: {@31, NULL, NULL, NULL, NULL} = adj1_fwd1_jac_y_ref(@1, @4, @16, @17, @18, @29, @30) */
  arg1[0]=(&w1);
  arg1[1]=0;
  arg1[2]=0;
  arg1[3]=(&w17);
  arg1[4]=0;
  arg1[5]=0;
  arg1[6]=(&w30);
  res1[0]=(&w31);
  res1[1]=0;
  res1[2]=0;
  res1[3]=0;
  res1[4]=0;
  if (casadi_f8(arg1, res1, iw, w, 0)) return 1;
  /* #46: @32 = (@7*@31) */
  w32  = (w7*w31);
  /* #47: @28 = (@28-@32) */
  w28 -= w32;
  /* #48: @33 = 00 */
  /* #49: @32 = 1 */
  w32 = 1.;
  /* #50: {@34, NULL, NULL, NULL, NULL} = adj1_fwd1_jac_x_ref(@1, @2, @14, @11, @15, @33, @32) */
  arg1[0]=(&w1);
  arg1[1]=0;
  arg1[2]=0;
  arg1[3]=(&w11);
  arg1[4]=0;
  arg1[5]=0;
  arg1[6]=(&w32);
  res1[0]=(&w34);
  res1[1]=0;
  res1[2]=0;
  res1[3]=0;
  res1[4]=0;
  if (casadi_f9(arg1, res1, iw, w, 0)) return 1;
  /* #51: @35 = (@7*@34) */
  w35  = (w7*w34);
  /* #52: @36 = (@3*@27) */
  w36  = (w3*w27);
  /* #53: @35 = (@35-@36) */
  w35 -= w36;
  /* #54: @36 = (@3*@31) */
  w36  = (w3*w31);
  /* #55: @37 = (@5*@34) */
  w37  = (w5*w34);
  /* #56: @36 = (@36-@37) */
  w36 -= w37;
  /* #57: @25 = vertcat(@28, @35, @36) */
  rr=w25;
  *rr++ = w28;
  *rr++ = w35;
  *rr++ = w36;
  /* #58: @25 = (@25/@12) */
  for (i=0, rr=w25; i<3; ++i) (*rr++) /= w12;
  /* #59: @28 = dot(@24, @25) */
  w28 = casadi_dot(3, w24, w25);
  /* #60: @35 = (@28*@0) */
  w35  = (w28*w0);
  /* #61: @36 = input[0][2] */
  w36 = arg[0] ? arg[0][2] : 0;
  /* #62: @35 = (@35*@36) */
  w35 *= w36;
  /* #63: @10 = (@10+@35) */
  w10 += w35;
  /* #64: output[0][1] = @10 */
  if (res[0]) res[0][1] = w10;
  /* #65: @35 = 0 */
  w35 = 0.;
  /* #66: @37 = @24[2] */
  for (rr=(&w37), ss=w24+2; ss!=w24+3; ss+=1) *rr++ = *ss;
  /* #67: @38 = (@5*@37) */
  w38  = (w5*w37);
  /* #68: @39 = @24[1] */
  for (rr=(&w39), ss=w24+1; ss!=w24+2; ss+=1) *rr++ = *ss;
  /* #69: @40 = (@7*@39) */
  w40  = (w7*w39);
  /* #70: @38 = (@38-@40) */
  w38 -= w40;
  /* #71: @40 = @24[0] */
  for (rr=(&w40), ss=w24+0; ss!=w24+1; ss+=1) *rr++ = *ss;
  /* #72: @41 = (@7*@40) */
  w41  = (w7*w40);
  /* #73: @37 = (@3*@37) */
  w37  = (w3*w37);
  /* #74: @41 = (@41-@37) */
  w41 -= w37;
  /* #75: @39 = (@3*@39) */
  w39  = (w3*w39);
  /* #76: @40 = (@5*@40) */
  w40  = (w5*w40);
  /* #77: @39 = (@39-@40) */
  w39 -= w40;
  /* #78: @42 = vertcat(@38, @41, @39) */
  rr=w42;
  *rr++ = w38;
  *rr++ = w41;
  *rr++ = w39;
  /* #79: @43 = @42' */
  casadi_copy(w42, 3, w43);
  /* #80: @35 = mac(@43,@13,@35) */
  for (i=0, rr=(&w35); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w43+j, tt=w13+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #81: @38 = (@28*@0) */
  w38  = (w28*w0);
  /* #82: @38 = (@38*@19) */
  w38 *= w19;
  /* #83: @35 = (@35-@38) */
  w35 -= w38;
  /* #84: output[0][2] = @35 */
  if (res[0]) res[0][2] = w35;
  /* #85: @38 = input[0][4] */
  w38 = arg[0] ? arg[0][4] : 0;
  /* #86: @41 = input[0][10] */
  w41 = arg[0] ? arg[0][10] : 0;
  /* #87: @39 = (@38*@41) */
  w39  = (w38*w41);
  /* #88: @39 = (-@39) */
  w39 = (- w39 );
  /* #89: @40 = input[0][5] */
  w40 = arg[0] ? arg[0][5] : 0;
  /* #90: @37 = input[0][11] */
  w37 = arg[0] ? arg[0][11] : 0;
  /* #91: @44 = (@40*@37) */
  w44  = (w40*w37);
  /* #92: @39 = (@39-@44) */
  w39 -= w44;
  /* #93: @44 = input[0][6] */
  w44 = arg[0] ? arg[0][6] : 0;
  /* #94: @45 = input[0][12] */
  w45 = arg[0] ? arg[0][12] : 0;
  /* #95: @46 = (@44*@45) */
  w46  = (w44*w45);
  /* #96: @39 = (@39-@46) */
  w39 -= w46;
  /* #97: @46 = 2 */
  w46 = 2.;
  /* #98: @39 = (@39/@46) */
  w39 /= w46;
  /* #99: output[0][3] = @39 */
  if (res[0]) res[0][3] = w39;
  /* #100: @39 = input[0][3] */
  w39 = arg[0] ? arg[0][3] : 0;
  /* #101: @46 = (@39*@41) */
  w46  = (w39*w41);
  /* #102: @47 = (@44*@37) */
  w47  = (w44*w37);
  /* #103: @46 = (@46-@47) */
  w46 -= w47;
  /* #104: @47 = (@40*@45) */
  w47  = (w40*w45);
  /* #105: @46 = (@46+@47) */
  w46 += w47;
  /* #106: @47 = 2 */
  w47 = 2.;
  /* #107: @46 = (@46/@47) */
  w46 /= w47;
  /* #108: output[0][4] = @46 */
  if (res[0]) res[0][4] = w46;
  /* #109: @46 = (@44*@41) */
  w46  = (w44*w41);
  /* #110: @47 = (@39*@37) */
  w47  = (w39*w37);
  /* #111: @46 = (@46+@47) */
  w46 += w47;
  /* #112: @47 = (@38*@45) */
  w47  = (w38*w45);
  /* #113: @46 = (@46-@47) */
  w46 -= w47;
  /* #114: @47 = 2 */
  w47 = 2.;
  /* #115: @46 = (@46/@47) */
  w46 /= w47;
  /* #116: output[0][5] = @46 */
  if (res[0]) res[0][5] = w46;
  /* #117: @46 = (@38*@37) */
  w46  = (w38*w37);
  /* #118: @47 = (@40*@41) */
  w47  = (w40*w41);
  /* #119: @46 = (@46-@47) */
  w46 -= w47;
  /* #120: @47 = (@39*@45) */
  w47  = (w39*w45);
  /* #121: @46 = (@46+@47) */
  w46 += w47;
  /* #122: @47 = 2 */
  w47 = 2.;
  /* #123: @46 = (@46/@47) */
  w46 /= w47;
  /* #124: output[0][6] = @46 */
  if (res[0]) res[0][6] = w46;
  /* #125: @46 = 0 */
  w46 = 0.;
  /* #126: @43 = @8' */
  casadi_copy(w8, 3, w43);
  /* #127: @48 = [-0, -0, -9.80665] */
  casadi_copy(casadi_c16, 3, w48);
  /* #128: @49 = zeros(3x1) */
  casadi_clear(w49, 3);
  /* #129: @47 = 32.2581 */
  w47 = 3.2258064516129032e+01;
  /* #130: @50 = sq(@39) */
  w50 = casadi_sq( w39 );
  /* #131: @51 = sq(@38) */
  w51 = casadi_sq( w38 );
  /* #132: @50 = (@50+@51) */
  w50 += w51;
  /* #133: @50 = (2.*@50) */
  w50 = (2.* w50 );
  /* #134: @51 = 1 */
  w51 = 1.;
  /* #135: @50 = (@50-@51) */
  w50 -= w51;
  /* #136: @51 = -2 */
  w51 = -2.;
  /* #137: @52 = (@39*@44) */
  w52  = (w39*w44);
  /* #138: @53 = (@38*@40) */
  w53  = (w38*w40);
  /* #139: @52 = (@52-@53) */
  w52 -= w53;
  /* #140: @51 = (@51*@52) */
  w51 *= w52;
  /* #141: @52 = (@39*@40) */
  w52  = (w39*w40);
  /* #142: @53 = (@38*@44) */
  w53  = (w38*w44);
  /* #143: @52 = (@52+@53) */
  w52 += w53;
  /* #144: @52 = (2.*@52) */
  w52 = (2.* w52 );
  /* #145: @54 = horzcat(@50, @51, @52) */
  rr=w54;
  *rr++ = w50;
  *rr++ = w51;
  *rr++ = w52;
  /* #146: @54 = @54' */
  /* #147: @50 = (@39*@44) */
  w50  = (w39*w44);
  /* #148: @51 = (@38*@40) */
  w51  = (w38*w40);
  /* #149: @50 = (@50+@51) */
  w50 += w51;
  /* #150: @50 = (2.*@50) */
  w50 = (2.* w50 );
  /* #151: @51 = sq(@39) */
  w51 = casadi_sq( w39 );
  /* #152: @52 = sq(@40) */
  w52 = casadi_sq( w40 );
  /* #153: @51 = (@51+@52) */
  w51 += w52;
  /* #154: @51 = (2.*@51) */
  w51 = (2.* w51 );
  /* #155: @52 = 1 */
  w52 = 1.;
  /* #156: @51 = (@51-@52) */
  w51 -= w52;
  /* #157: @52 = (@39*@38) */
  w52  = (w39*w38);
  /* #158: @53 = (@40*@44) */
  w53  = (w40*w44);
  /* #159: @52 = (@52-@53) */
  w52 -= w53;
  /* #160: @52 = (2.*@52) */
  w52 = (2.* w52 );
  /* #161: @55 = horzcat(@50, @51, @52) */
  rr=w55;
  *rr++ = w50;
  *rr++ = w51;
  *rr++ = w52;
  /* #162: @55 = @55' */
  /* #163: @50 = (@39*@40) */
  w50  = (w39*w40);
  /* #164: @51 = (@38*@44) */
  w51  = (w38*w44);
  /* #165: @50 = (@50-@51) */
  w50 -= w51;
  /* #166: @50 = (2.*@50) */
  w50 = (2.* w50 );
  /* #167: @38 = (@39*@38) */
  w38  = (w39*w38);
  /* #168: @40 = (@40*@44) */
  w40 *= w44;
  /* #169: @38 = (@38+@40) */
  w38 += w40;
  /* #170: @38 = (2.*@38) */
  w38 = (2.* w38 );
  /* #171: @39 = sq(@39) */
  w39 = casadi_sq( w39 );
  /* #172: @44 = sq(@44) */
  w44 = casadi_sq( w44 );
  /* #173: @39 = (@39+@44) */
  w39 += w44;
  /* #174: @39 = (2.*@39) */
  w39 = (2.* w39 );
  /* #175: @44 = 1 */
  w44 = 1.;
  /* #176: @39 = (@39-@44) */
  w39 -= w44;
  /* #177: @56 = horzcat(@50, @38, @39) */
  rr=w56;
  *rr++ = w50;
  *rr++ = w38;
  *rr++ = w39;
  /* #178: @56 = @56' */
  /* #179: @57 = horzcat(@54, @55, @56) */
  rr=w57;
  for (i=0, cs=w54; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w55; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w56; i<3; ++i) *rr++ = *cs++;
  /* #180: @58 = @57' */
  for (i=0, rr=w58, cs=w57; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #181: @58 = (@47*@58) */
  for (i=0, rr=w58, cs=w58; i<9; ++i) (*rr++)  = (w47*(*cs++));
  /* #182: @47 = 0.000325 */
  w47 = 3.2499999999999999e-04;
  /* #183: @50 = 0 */
  w50 = 0.;
  /* #184: @38 = 0 */
  w38 = 0.;
  /* #185: @39 = input[0][16] */
  w39 = arg[0] ? arg[0][16] : 0;
  /* #186: @44 = sq(@39) */
  w44 = casadi_sq( w39 );
  /* #187: @40 = input[0][17] */
  w40 = arg[0] ? arg[0][17] : 0;
  /* #188: @51 = sq(@40) */
  w51 = casadi_sq( w40 );
  /* #189: @44 = (@44+@51) */
  w44 += w51;
  /* #190: @51 = input[0][18] */
  w51 = arg[0] ? arg[0][18] : 0;
  /* #191: @52 = sq(@51) */
  w52 = casadi_sq( w51 );
  /* #192: @44 = (@44+@52) */
  w44 += w52;
  /* #193: @52 = input[0][19] */
  w52 = arg[0] ? arg[0][19] : 0;
  /* #194: @53 = sq(@52) */
  w53 = casadi_sq( w52 );
  /* #195: @44 = (@44+@53) */
  w44 += w53;
  /* #196: @54 = vertcat(@50, @38, @44) */
  rr=w54;
  *rr++ = w50;
  *rr++ = w38;
  *rr++ = w44;
  /* #197: @54 = (@47*@54) */
  for (i=0, rr=w54, cs=w54; i<3; ++i) (*rr++)  = (w47*(*cs++));
  /* #198: @49 = mac(@58,@54,@49) */
  for (i=0, rr=w49; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w58+j, tt=w54+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #199: @48 = (@48+@49) */
  for (i=0, rr=w48, cs=w49; i<3; ++i) (*rr++) += (*cs++);
  /* #200: @46 = mac(@43,@48,@46) */
  for (i=0, rr=(&w46); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w43+j, tt=w48+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #201: @47 = 0 */
  w47 = 0.;
  /* #202: @43 = (@9*@0) */
  for (i=0, rr=w43, cr=w9; i<3; ++i) (*rr++)  = ((*cr++)*w0);
  /* #203: @43 = @43' */
  /* #204: @47 = mac(@43,@13,@47) */
  for (i=0, rr=(&w47); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w43+j, tt=w13+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #205: @46 = (@46+@47) */
  w46 += w47;
  /* #206: @47 = 1 */
  w47 = 1.;
  /* #207: @50 = (@12*@19) */
  w50  = (w12*w19);
  /* #208: @47 = (@47-@50) */
  w47 -= w50;
  /* #209: @46 = (@46/@47) */
  w46 /= w47;
  /* #210: @47 = 0 */
  w47 = 0.;
  /* #211: @8 = @8' */
  /* #212: @47 = mac(@8,@13,@47) */
  for (i=0, rr=(&w47); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w8+j, tt=w13+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #213: @59 = 00 */
  /* #214: @50 = 1 */
  w50 = 1.;
  /* #215: @60 = 00 */
  /* #216: @61 = 00 */
  /* #217: @38 = 0 */
  w38 = 0.;
  /* #218: @62 = 00 */
  /* #219: @44 = fwd1_fwd1_jac_x_ref(@1, @2, @14, @11, @15, @59, @50, @60, @61, @38, @62) */
  arg1[0]=(&w1);
  arg1[1]=0;
  arg1[2]=0;
  arg1[3]=(&w11);
  arg1[4]=0;
  arg1[5]=0;
  arg1[6]=(&w50);
  arg1[7]=0;
  arg1[8]=0;
  arg1[9]=(&w38);
  arg1[10]=0;
  res1[0]=(&w44);
  if (casadi_f10(arg1, res1, iw, w, 0)) return 1;
  /* #220: @59 = 00 */
  /* #221: @60 = 00 */
  /* #222: @61 = 00 */
  /* #223: @38 = 0 */
  w38 = 0.;
  /* #224: @62 = 00 */
  /* #225: @53 = fwd1_fwd1_jac_y_ref(@1, @4, @16, @17, @18, @59, @50, @60, @61, @38, @62) */
  arg1[0]=(&w1);
  arg1[1]=0;
  arg1[2]=0;
  arg1[3]=(&w17);
  arg1[4]=0;
  arg1[5]=0;
  arg1[6]=(&w50);
  arg1[7]=0;
  arg1[8]=0;
  arg1[9]=(&w38);
  arg1[10]=0;
  res1[0]=(&w53);
  if (casadi_f11(arg1, res1, iw, w, 0)) return 1;
  /* #226: @59 = 00 */
  /* #227: @60 = 00 */
  /* #228: @61 = 00 */
  /* #229: @38 = 0 */
  w38 = 0.;
  /* #230: @62 = 00 */
  /* #231: @63 = fwd1_fwd1_jac_z_ref(@1, @6, @20, @21, @22, @59, @50, @60, @61, @38, @62) */
  arg1[0]=(&w1);
  arg1[1]=0;
  arg1[2]=0;
  arg1[3]=(&w21);
  arg1[4]=0;
  arg1[5]=0;
  arg1[6]=(&w50);
  arg1[7]=0;
  arg1[8]=0;
  arg1[9]=(&w38);
  arg1[10]=0;
  res1[0]=(&w63);
  if (casadi_f12(arg1, res1, iw, w, 0)) return 1;
  /* #232: @8 = vertcat(@44, @53, @63) */
  rr=w8;
  *rr++ = w44;
  *rr++ = w53;
  *rr++ = w63;
  /* #233: @44 = dot(@9, @8) */
  w44 = casadi_dot(3, w9, w8);
  /* #234: @44 = (@44/@12) */
  w44 /= w12;
  /* #235: @44 = (@44*@0) */
  w44 *= w0;
  /* #236: @44 = (@19*@44) */
  w44  = (w19*w44);
  /* #237: @53 = (@10*@12) */
  w53  = (w10*w12);
  /* #238: @44 = (@44+@53) */
  w44 += w53;
  /* #239: @53 = 1 */
  w53 = 1.;
  /* #240: @63 = (@12*@19) */
  w63  = (w12*w19);
  /* #241: @53 = (@53-@63) */
  w53 -= w63;
  /* #242: @53 = sq(@53) */
  w53 = casadi_sq( w53 );
  /* #243: @44 = (@44/@53) */
  w44 /= w53;
  /* #244: @47 = (@47*@44) */
  w47 *= w44;
  /* #245: @46 = (@46+@47) */
  w46 += w47;
  /* #246: output[0][7] = @46 */
  if (res[0]) res[0][7] = w46;
  /* #247: @47 = 0 */
  w47 = 0.;
  /* #248: @8 = @24' */
  casadi_copy(w24, 3, w8);
  /* #249: @47 = mac(@8,@48,@47) */
  for (i=0, rr=(&w47); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w8+j, tt=w48+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #250: @44 = 0 */
  w44 = 0.;
  /* #251: @53 = sq(@12) */
  w53 = casadi_sq( w12 );
  /* #252: @8 = vertcat(@34, @31, @27) */
  rr=w8;
  *rr++ = w34;
  *rr++ = w31;
  *rr++ = w27;
  /* #253: @43 = (@53*@8) */
  for (i=0, rr=w43, cs=w8; i<3; ++i) (*rr++)  = (w53*(*cs++));
  /* #254: @49 = zeros(3x1) */
  casadi_clear(w49, 3);
  /* #255: @58 = zeros(3x3) */
  casadi_clear(w58, 9);
  /* #256: @8 = @8' */
  /* #257: @58 = mac(@9,@8,@58) */
  for (i=0, rr=w58; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w9+j, tt=w8+i*1; k<1; ++k) *rr += ss[k*3]**tt++;
  /* #258: @49 = mac(@58,@9,@49) */
  for (i=0, rr=w49; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w58+j, tt=w9+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #259: @43 = (@43-@49) */
  for (i=0, rr=w43, cs=w49; i<3; ++i) (*rr++) -= (*cs++);
  /* #260: @53 = 3 */
  w53 = 3.;
  /* #261: @53 = pow(@12,@53) */
  w53  = pow(w12,w53);
  /* #262: @43 = (@43/@53) */
  for (i=0, rr=w43; i<3; ++i) (*rr++) /= w53;
  /* #263: @43 = (@43*@0) */
  for (i=0, rr=w43; i<3; ++i) (*rr++) *= w0;
  /* #264: @43 = @43' */
  /* #265: @44 = mac(@43,@13,@44) */
  for (i=0, rr=(&w44); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w43+j, tt=w13+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #266: @47 = (@47+@44) */
  w47 += w44;
  /* #267: @59 = 00 */
  /* #268: @44 = 1 */
  w44 = 1.;
  /* #269: @60 = 00 */
  /* #270: @53 = fwd1_jac_y_ref(@1, @4, @59, @44, @60) */
  arg1[0]=(&w1);
  arg1[1]=0;
  arg1[2]=0;
  arg1[3]=(&w44);
  arg1[4]=0;
  res1[0]=(&w53);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #271: @63 = (@27*@53) */
  w63  = (w27*w53);
  /* #272: @59 = 00 */
  /* #273: @61 = 00 */
  /* #274: @62 = 00 */
  /* #275: @64 = 00 */
  /* #276: @65 = 00 */
  /* #277: @66 = 00 */
  /* #278: @67 = 00 */
  /* #279: @50 = 0 */
  w50 = 0.;
  /* #280: @68 = 00 */
  /* #281: @69 = 00 */
  /* #282: @38 = 0 */
  w38 = 0.;
  /* #283: {@70, NULL, NULL, NULL, NULL} = fwd1_adj1_fwd1_jac_z_ref(@1, @6, @20, @21, @22, @26, @23, @59, @61, @62, @64, @65, @44, @66, @67, @50, @68, @69, @38) */
  arg1[0]=(&w1);
  arg1[1]=0;
  arg1[2]=0;
  arg1[3]=(&w21);
  arg1[4]=0;
  arg1[5]=0;
  arg1[6]=(&w23);
  arg1[7]=0;
  arg1[8]=0;
  arg1[9]=0;
  arg1[10]=0;
  arg1[11]=0;
  arg1[12]=(&w44);
  arg1[13]=0;
  arg1[14]=0;
  arg1[15]=(&w50);
  arg1[16]=0;
  arg1[17]=0;
  arg1[18]=(&w38);
  res1[0]=(&w70);
  res1[1]=0;
  res1[2]=0;
  res1[3]=0;
  res1[4]=0;
  if (casadi_f13(arg1, res1, iw, w, 0)) return 1;
  /* #284: @23 = (@5*@70) */
  w23  = (w5*w70);
  /* #285: @63 = (@63+@23) */
  w63 += w23;
  /* #286: @26 = 00 */
  /* #287: @23 = fwd1_jac_z_ref(@1, @6, @26, @44, @66) */
  arg1[0]=(&w1);
  arg1[1]=0;
  arg1[2]=0;
  arg1[3]=(&w44);
  arg1[4]=0;
  res1[0]=(&w23);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #288: @50 = (@31*@23) */
  w50  = (w31*w23);
  /* #289: @26 = 00 */
  /* #290: @59 = 00 */
  /* #291: @61 = 00 */
  /* #292: @62 = 00 */
  /* #293: @64 = 00 */
  /* #294: @65 = 00 */
  /* #295: @38 = 0 */
  w38 = 0.;
  /* #296: @69 = 00 */
  /* #297: @71 = 00 */
  /* #298: @72 = 0 */
  w72 = 0.;
  /* #299: {@73, NULL, NULL, NULL, NULL} = fwd1_adj1_fwd1_jac_y_ref(@1, @4, @16, @17, @18, @29, @30, @26, @59, @61, @62, @64, @44, @60, @65, @38, @69, @71, @72) */
  arg1[0]=(&w1);
  arg1[1]=0;
  arg1[2]=0;
  arg1[3]=(&w17);
  arg1[4]=0;
  arg1[5]=0;
  arg1[6]=(&w30);
  arg1[7]=0;
  arg1[8]=0;
  arg1[9]=0;
  arg1[10]=0;
  arg1[11]=0;
  arg1[12]=(&w44);
  arg1[13]=0;
  arg1[14]=0;
  arg1[15]=(&w38);
  arg1[16]=0;
  arg1[17]=0;
  arg1[18]=(&w72);
  res1[0]=(&w73);
  res1[1]=0;
  res1[2]=0;
  res1[3]=0;
  res1[4]=0;
  if (casadi_f14(arg1, res1, iw, w, 0)) return 1;
  /* #300: @30 = (@7*@73) */
  w30  = (w7*w73);
  /* #301: @50 = (@50+@30) */
  w50 += w30;
  /* #302: @63 = (@63-@50) */
  w63 -= w50;
  /* #303: @23 = (@34*@23) */
  w23  = (w34*w23);
  /* #304: @29 = 00 */
  /* #305: @26 = 00 */
  /* #306: @59 = 00 */
  /* #307: @61 = 00 */
  /* #308: @62 = 00 */
  /* #309: @64 = 00 */
  /* #310: @71 = 00 */
  /* #311: @50 = 0 */
  w50 = 0.;
  /* #312: @74 = 00 */
  /* #313: @75 = 00 */
  /* #314: @30 = 0 */
  w30 = 0.;
  /* #315: {@38, NULL, NULL, NULL, NULL} = fwd1_adj1_fwd1_jac_x_ref(@1, @2, @14, @11, @15, @33, @32, @29, @26, @59, @61, @62, @44, @64, @71, @50, @74, @75, @30) */
  arg1[0]=(&w1);
  arg1[1]=0;
  arg1[2]=0;
  arg1[3]=(&w11);
  arg1[4]=0;
  arg1[5]=0;
  arg1[6]=(&w32);
  arg1[7]=0;
  arg1[8]=0;
  arg1[9]=0;
  arg1[10]=0;
  arg1[11]=0;
  arg1[12]=(&w44);
  arg1[13]=0;
  arg1[14]=0;
  arg1[15]=(&w50);
  arg1[16]=0;
  arg1[17]=0;
  arg1[18]=(&w30);
  res1[0]=(&w38);
  res1[1]=0;
  res1[2]=0;
  res1[3]=0;
  res1[4]=0;
  if (casadi_f15(arg1, res1, iw, w, 0)) return 1;
  /* #316: @7 = (@7*@38) */
  w7 *= w38;
  /* #317: @23 = (@23+@7) */
  w23 += w7;
  /* #318: @33 = 00 */
  /* #319: @7 = fwd1_jac_x_ref(@1, @2, @33, @44, @64) */
  arg1[0]=(&w1);
  arg1[1]=0;
  arg1[2]=0;
  arg1[3]=(&w44);
  arg1[4]=0;
  res1[0]=(&w7);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #320: @27 = (@27*@7) */
  w27 *= w7;
  /* #321: @70 = (@3*@70) */
  w70  = (w3*w70);
  /* #322: @27 = (@27+@70) */
  w27 += w70;
  /* #323: @23 = (@23-@27) */
  w23 -= w27;
  /* #324: @31 = (@31*@7) */
  w31 *= w7;
  /* #325: @3 = (@3*@73) */
  w3 *= w73;
  /* #326: @31 = (@31+@3) */
  w31 += w3;
  /* #327: @34 = (@34*@53) */
  w34 *= w53;
  /* #328: @5 = (@5*@38) */
  w5 *= w38;
  /* #329: @34 = (@34+@5) */
  w34 += w5;
  /* #330: @31 = (@31-@34) */
  w31 -= w34;
  /* #331: @43 = vertcat(@63, @23, @31) */
  rr=w43;
  *rr++ = w63;
  *rr++ = w23;
  *rr++ = w31;
  /* #332: @43 = (@43/@12) */
  for (i=0, rr=w43; i<3; ++i) (*rr++) /= w12;
  /* #333: @49 = (@25/@12) */
  for (i=0, rr=w49, cr=w25; i<3; ++i) (*rr++)  = ((*cr++)/w12);
  /* #334: @33 = 00 */
  /* #335: @63 = 0 */
  w63 = 0.;
  /* #336: @23 = fwd1_fwd1_jac_x_ref(@1, @2, @14, @11, @15, @33, @44, @64, @71, @63, @74) */
  arg1[0]=(&w1);
  arg1[1]=0;
  arg1[2]=0;
  arg1[3]=(&w11);
  arg1[4]=0;
  arg1[5]=0;
  arg1[6]=(&w44);
  arg1[7]=0;
  arg1[8]=0;
  arg1[9]=(&w63);
  arg1[10]=0;
  res1[0]=(&w23);
  if (casadi_f10(arg1, res1, iw, w, 0)) return 1;
  /* #337: @2 = 00 */
  /* #338: @11 = 0 */
  w11 = 0.;
  /* #339: @63 = fwd1_fwd1_jac_y_ref(@1, @4, @16, @17, @18, @2, @44, @60, @65, @11, @69) */
  arg1[0]=(&w1);
  arg1[1]=0;
  arg1[2]=0;
  arg1[3]=(&w17);
  arg1[4]=0;
  arg1[5]=0;
  arg1[6]=(&w44);
  arg1[7]=0;
  arg1[8]=0;
  arg1[9]=(&w11);
  arg1[10]=0;
  res1[0]=(&w63);
  if (casadi_f11(arg1, res1, iw, w, 0)) return 1;
  /* #340: @4 = 00 */
  /* #341: @17 = 0 */
  w17 = 0.;
  /* #342: @11 = fwd1_fwd1_jac_z_ref(@1, @6, @20, @21, @22, @4, @44, @66, @67, @17, @68) */
  arg1[0]=(&w1);
  arg1[1]=0;
  arg1[2]=0;
  arg1[3]=(&w21);
  arg1[4]=0;
  arg1[5]=0;
  arg1[6]=(&w44);
  arg1[7]=0;
  arg1[8]=0;
  arg1[9]=(&w17);
  arg1[10]=0;
  res1[0]=(&w11);
  if (casadi_f12(arg1, res1, iw, w, 0)) return 1;
  /* #343: @8 = vertcat(@23, @63, @11) */
  rr=w8;
  *rr++ = w23;
  *rr++ = w63;
  *rr++ = w11;
  /* #344: @23 = dot(@9, @8) */
  w23 = casadi_dot(3, w9, w8);
  /* #345: @23 = (@23/@12) */
  w23 /= w12;
  /* #346: @49 = (@49*@23) */
  for (i=0, rr=w49; i<3; ++i) (*rr++) *= w23;
  /* #347: @43 = (@43-@49) */
  for (i=0, rr=w43, cs=w49; i<3; ++i) (*rr++) -= (*cs++);
  /* #348: @63 = dot(@24, @43) */
  w63 = casadi_dot(3, w24, w43);
  /* #349: @8 = (@8/@12) */
  for (i=0, rr=w8; i<3; ++i) (*rr++) /= w12;
  /* #350: @24 = (@24/@12) */
  for (i=0, rr=w24; i<3; ++i) (*rr++) /= w12;
  /* #351: @24 = (@24*@23) */
  for (i=0, rr=w24; i<3; ++i) (*rr++) *= w23;
  /* #352: @8 = (@8-@24) */
  for (i=0, rr=w8, cs=w24; i<3; ++i) (*rr++) -= (*cs++);
  /* #353: @23 = dot(@8, @25) */
  w23 = casadi_dot(3, w8, w25);
  /* #354: @63 = (@63+@23) */
  w63 += w23;
  /* #355: @63 = (@63*@0) */
  w63 *= w0;
  /* #356: @23 = (@63*@0) */
  w23  = (w63*w0);
  /* #357: @23 = (@23*@36) */
  w23 *= w36;
  /* #358: @47 = (@47+@23) */
  w47 += w23;
  /* #359: @23 = (@28*@46) */
  w23  = (w28*w46);
  /* #360: @23 = (@23*@36) */
  w23 *= w36;
  /* #361: @47 = (@47+@23) */
  w47 += w23;
  /* #362: @23 = (@28*@0) */
  w23  = (w28*w0);
  /* #363: @23 = (@23*@35) */
  w23 *= w35;
  /* #364: @47 = (@47+@23) */
  w47 += w23;
  /* #365: output[0][8] = @47 */
  if (res[0]) res[0][8] = w47;
  /* #366: @47 = 0 */
  w47 = 0.;
  /* #367: @42 = @42' */
  /* #368: @47 = mac(@42,@48,@47) */
  for (i=0, rr=(&w47); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w42+j, tt=w48+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #369: @23 = 0 */
  w23 = 0.;
  /* #370: @25 = (@25*@0) */
  for (i=0, rr=w25; i<3; ++i) (*rr++) *= w0;
  /* #371: @25 = @25' */
  /* #372: @23 = mac(@25,@13,@23) */
  for (i=0, rr=(&w23); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w25+j, tt=w13+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #373: @47 = (@47+@23) */
  w47 += w23;
  /* #374: @63 = (@63*@0) */
  w63 *= w0;
  /* #375: @63 = (@63*@19) */
  w63 *= w19;
  /* #376: @47 = (@47-@63) */
  w47 -= w63;
  /* #377: @46 = (@28*@46) */
  w46  = (w28*w46);
  /* #378: @46 = (@46*@19) */
  w46 *= w19;
  /* #379: @47 = (@47-@46) */
  w47 -= w46;
  /* #380: @28 = (@28*@0) */
  w28 *= w0;
  /* #381: @28 = (@28*@10) */
  w28 *= w10;
  /* #382: @47 = (@47-@28) */
  w47 -= w28;
  /* #383: output[0][9] = @47 */
  if (res[0]) res[0][9] = w47;
  /* #384: @25 = 
  [[71684.6, 00, 00], 
   [00, 71684.6, 00], 
   [00, 00, 46019.3]] */
  casadi_copy(casadi_c17, 3, w25);
  /* #385: @25 = nonzeros(@25) */
  /* #386: @47 = 1.495e-05 */
  w47 = 1.4949999999999999e-05;
  /* #387: @28 = sq(@39) */
  w28 = casadi_sq( w39 );
  /* #388: @10 = sq(@40) */
  w10 = casadi_sq( w40 );
  /* #389: @28 = (@28+@10) */
  w28 += w10;
  /* #390: @10 = sq(@51) */
  w10 = casadi_sq( w51 );
  /* #391: @28 = (@28-@10) */
  w28 -= w10;
  /* #392: @10 = sq(@52) */
  w10 = casadi_sq( w52 );
  /* #393: @28 = (@28-@10) */
  w28 -= w10;
  /* #394: @47 = (@47*@28) */
  w47 *= w28;
  /* #395: @28 = 1.495e-05 */
  w28 = 1.4949999999999999e-05;
  /* #396: @10 = sq(@39) */
  w10 = casadi_sq( w39 );
  /* #397: @0 = sq(@40) */
  w0 = casadi_sq( w40 );
  /* #398: @10 = (@10-@0) */
  w10 -= w0;
  /* #399: @0 = sq(@51) */
  w0 = casadi_sq( w51 );
  /* #400: @10 = (@10-@0) */
  w10 -= w0;
  /* #401: @0 = sq(@52) */
  w0 = casadi_sq( w52 );
  /* #402: @10 = (@10+@0) */
  w10 += w0;
  /* #403: @28 = (@28*@10) */
  w28 *= w10;
  /* #404: @10 = 7.9379e-06 */
  w10 = 7.9379000000000007e-06;
  /* #405: @39 = sq(@39) */
  w39 = casadi_sq( w39 );
  /* #406: @40 = sq(@40) */
  w40 = casadi_sq( w40 );
  /* #407: @39 = (@39-@40) */
  w39 -= w40;
  /* #408: @51 = sq(@51) */
  w51 = casadi_sq( w51 );
  /* #409: @39 = (@39+@51) */
  w39 += w51;
  /* #410: @52 = sq(@52) */
  w52 = casadi_sq( w52 );
  /* #411: @39 = (@39-@52) */
  w39 -= w52;
  /* #412: @10 = (@10*@39) */
  w10 *= w39;
  /* #413: @13 = vertcat(@47, @28, @10) */
  rr=w13;
  *rr++ = w47;
  *rr++ = w28;
  *rr++ = w10;
  /* #414: @42 = zeros(3x1) */
  casadi_clear(w42, 3);
  /* #415: @58 = 
  [[1.395e-05, 0, 0], 
   [0, 1.395e-05, 0], 
   [0, 0, 2.173e-05]] */
  casadi_copy(casadi_c18, 9, w58);
  /* #416: @8 = vertcat(@41, @37, @45) */
  rr=w8;
  *rr++ = w41;
  *rr++ = w37;
  *rr++ = w45;
  /* #417: @42 = mac(@58,@8,@42) */
  for (i=0, rr=w42; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w58+j, tt=w8+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #418: @47 = @42[2] */
  for (rr=(&w47), ss=w42+2; ss!=w42+3; ss+=1) *rr++ = *ss;
  /* #419: @28 = (@37*@47) */
  w28  = (w37*w47);
  /* #420: @10 = @42[1] */
  for (rr=(&w10), ss=w42+1; ss!=w42+2; ss+=1) *rr++ = *ss;
  /* #421: @39 = (@45*@10) */
  w39  = (w45*w10);
  /* #422: @28 = (@28-@39) */
  w28 -= w39;
  /* #423: @39 = @42[0] */
  for (rr=(&w39), ss=w42+0; ss!=w42+1; ss+=1) *rr++ = *ss;
  /* #424: @45 = (@45*@39) */
  w45 *= w39;
  /* #425: @47 = (@41*@47) */
  w47  = (w41*w47);
  /* #426: @45 = (@45-@47) */
  w45 -= w47;
  /* #427: @41 = (@41*@10) */
  w41 *= w10;
  /* #428: @37 = (@37*@39) */
  w37 *= w39;
  /* #429: @41 = (@41-@37) */
  w41 -= w37;
  /* #430: @42 = vertcat(@28, @45, @41) */
  rr=w42;
  *rr++ = w28;
  *rr++ = w45;
  *rr++ = w41;
  /* #431: @13 = (@13-@42) */
  for (i=0, rr=w13, cs=w42; i<3; ++i) (*rr++) -= (*cs++);
  /* #432: @25 = (@25*@13) */
  for (i=0, rr=w25, cs=w13; i<3; ++i) (*rr++) *= (*cs++);
  /* #433: @28 = @25[0] */
  for (rr=(&w28), ss=w25+0; ss!=w25+1; ss+=1) *rr++ = *ss;
  /* #434: output[0][10] = @28 */
  if (res[0]) res[0][10] = w28;
  /* #435: @28 = @25[1] */
  for (rr=(&w28), ss=w25+1; ss!=w25+2; ss+=1) *rr++ = *ss;
  /* #436: output[0][11] = @28 */
  if (res[0]) res[0][11] = w28;
  /* #437: @28 = @25[2] */
  for (rr=(&w28), ss=w25+2; ss!=w25+3; ss+=1) *rr++ = *ss;
  /* #438: output[0][12] = @28 */
  if (res[0]) res[0][12] = w28;
  /* #439: @28 = @48[0] */
  for (rr=(&w28), ss=w48+0; ss!=w48+1; ss+=1) *rr++ = *ss;
  /* #440: output[0][13] = @28 */
  if (res[0]) res[0][13] = w28;
  /* #441: @28 = @48[1] */
  for (rr=(&w28), ss=w48+1; ss!=w48+2; ss+=1) *rr++ = *ss;
  /* #442: output[0][14] = @28 */
  if (res[0]) res[0][14] = w28;
  /* #443: @28 = @48[2] */
  for (rr=(&w28), ss=w48+2; ss!=w48+3; ss+=1) *rr++ = *ss;
  /* #444: output[0][15] = @28 */
  if (res[0]) res[0][15] = w28;
  /* #445: @28 = input[1][0] */
  w28 = arg[1] ? arg[1][0] : 0;
  /* #446: output[0][16] = @28 */
  if (res[0]) res[0][16] = w28;
  /* #447: @28 = input[1][1] */
  w28 = arg[1] ? arg[1][1] : 0;
  /* #448: output[0][17] = @28 */
  if (res[0]) res[0][17] = w28;
  /* #449: @28 = input[1][2] */
  w28 = arg[1] ? arg[1][2] : 0;
  /* #450: output[0][18] = @28 */
  if (res[0]) res[0][18] = w28;
  /* #451: @28 = input[1][3] */
  w28 = arg[1] ? arg[1][3] : 0;
  /* #452: output[0][19] = @28 */
  if (res[0]) res[0][19] = w28;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s9;
    case 1: return casadi_s10;
    case 2: return casadi_s11;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s9;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 24;
  if (sz_res) *sz_res = 7;
  if (sz_iw) *sz_iw = 6;
  if (sz_w) *sz_w = 108;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_expl_ode_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 24*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 7*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 6*sizeof(casadi_int);
  if (sz_w) *sz_w = 108*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
