
# flight mission
LEARNING_FROM_DEMO: false  # demonstration from the minimum snap
MANUAL_SET_POSE_TEST: true  # only works for ROS nodes
FIX_GATE_PITCH_TEST: true  # for success rate test and python sim
mission_period: 5.0 #s
ctl_mode: 0
# 0 collective thrust & body rate. 
# 1 single rotor thrust control. 
# 2 force and torque control. 
# 3.force difference control ALL types the command to the mavros is CTBR
manual_init_guess: false
drone:
  wing_len: 0.3
  height: 0.2
  ## in the training, the drone size should be the same as with the gate size
  wing_len_train: 0.7
  height_train: 0.4
  mass: 0.248
  inertia: [0.000392,0.000405,0.000639] # [Ixx, Iyy, Izz] kg.m^2
  diagonal_axis_dist: 0.165 #m
  moment_constant: 8.8e-3
# gate parameters  
gate:
  length: 0.6 #1.2
  width: 0.3 # 0.5
  thickness: 2 # along quadrotor forward direction
  init_std_dev: 0.087 #pi/36=
  final_std_dev: 0.2618 #pi/12
  linear_vel: [0.0, 0.0, 0.0]
  # angular_vel: 0.0 
  # linear_vel: [0.1,-0.1,0.0]  #[0.5,-0.3,0.0]
  angular_vel: 0.0 #0.2 rad/s = 11.46 degree/s
traj_server:
  takeoff_height: 1.2
  drone_yaw: 0.0 # take-off yaw
mission:
  #################################################
  ######--------- for test --------#########
  #################################################
  ##------ MPC initial pose ----##
  # ##initial pose only works for python sim
  initial_position: [0.0, 1.8, 1.2]
  initial_ori_euler: [0.0, 0.0, 0.0] # YPR, only yaw is active

  ##------ gate pose ----##
  # only feasible for MANUAL_SET_POSE_TEST
  gate_position: [-0.0, -0.0, 1.8]
  # gate_ori_RP: [-0.0, -1.055, 0.0]
  gate_ori_euler: [0.0, 1.0,-0.0] # zyx 1.0 radian is 57.2958 degree,1.3 radian is 1.5 radian is 85.9437 degree 
  
  ##------ goal pose ----##
  goal_position: [0.0, -1.8, 1.5]
  goal_ori_euler: [0.0, 0.0, 0.0] # YPR, only yaw is active

  #################################################
  ######-----end of for testing --------------#####
  #################################################
  #################################################
  ######------------- Training -----------#########
  #################################################
  ##------ MPC initial pose ----##
  ##initial pose only works for python sim
  # initial_position: [0.0, -6, 0]
  # initial_ori_euler: [0.0, 0.0, 0] # RPY, only yaw is active

  # ##------ gate pose ----##
  # # only feasible for MANUAL_SET_POSE_TEST
  # gate_position: [0.0, -0.0, 1.5]
  # gate_ori_RP: [-0.0, -0.99, -0.0]  # 1 for 90 degree
  # gate_ori_euler: [0.0, -1.5,0.0] # RPY # 135 degree is radian is 2.35619

  # ##------ goal pose ----##
  # goal_position: [0.0, 3, 1.5]
  # goal_ori_euler: [0.0, 0.0, 0.0] # RPY, only yaw is active

  
# MPC parameters
learning_agile:
  ##-----parameters for training ------## 
  # #### for a stabler training,######## 
  wrt: [100,100,100]    #be the learnable variable
  wqt: 10.0   #be the learnable variable
  # wvt: 1.0   #be the learnable variable
  wthrust: 1
  wdthrust: 0.1
  w_tra_throttle: 5
  wwt: 5
  wwt_z: 15
  wm: 50
  # path cost
  wrp: [10,30,30]        ## too small, large deviation to the goal 30 sqp, 
  wvp: 10
  wqp: 0.01

  # terminal cost
  wrf: 500 #1200.0     #2 X 20(N) X wrp
  wvf: 500 #400.0
  wqf: 100
  ##------ traversing parameters ---##
  max_tra_w: 250 #100 be the learnable variable
  traverse_weight_span: 55 
  traverse_time: 0.5 # only for MANUAL_SET_POSE_TEST


  ## Safe PDP
  barrier_gamma: 0.1

  ##------ safety parameters  ------##
  no_solution_flag_t_thresh: 0.1
  
  ##------ MPC problem parameters---## 
  ## ---- hard coded in the solver ----##
  ## modify this required recompilation of the solver
  horizon: 20
  dt: 0.1
  varying_horizon: false
  # horizon: 80
  # dt: 0.025
    
  ##------ model parameters --------##
  ## ---- hard coded in the solver ----##
  ## modify this required recompilation of the solver
  single_motor_max_thrust: 2.0 #2.1334185 #N
  # 1.7268 N is based on the hover throttle: 0.29
  # drone mass: 0.248kg, g: 9.81m/s^2 weight: 0.248*9.81 = 2.43368N
  # hover throttle: 0.29, thrust: 0.29*max_thrust =2.43368N
  # max_thrust = 2.43368/0.29 = 8.4N
  # single_motor_max_thrust = 8.4/4 = 2.1N

  
  ##------ constraints parameters --##
  ## ---- hard coded in the solver ----##
  ## modify this required recompilation of the solver

  # throttle constraints
  throttle_upper_bound: 0.8
  throttle_lower_bound: 0.15


  # position constraints
  pos_bound: 15 #m (-b,b)
  pos_lb_z: 0.45 #m
  pos_ub_z: 2.45 #m

  # velocity constraints
  linear_vel_bound: 15 #m/s

  # angular velocity constraints
  angular_vel_bound_xy: 15.57 #rad/s
  angular_vel_bound_z: 15.57 #rad/s


  ## ----- miscellaneous parameters  ----##
  pred_traj_vis: true


  ##------  training parameters  ------##
pretrain_param:
  desired_average_vel: 2
  desired_average_vel_after_gate: 2
  desired_tra_vel: 3

## ------NN configuration ----##

# NN_model_name: 'training_results/new_format/2025-01-16/09-59-31/trained_model/NN_close_3200.pth' #**# 75% success rate
# NN_model_name: 'training_results/new_format/2025-01-31/11-40-49/trained_model/NN_close_1900.pth' # 80% success rate
# NN_model_name: 'training_results/new_format/2025-02-13/15-25-09/trained_model/NN_close_200.pth' # BPTT effect comparison
# NN_model_name: 'training_results/new_format/2025-02-13/15-48-00/trained_model/NN_close_100.pth'
# NN_model_name: 'training_results/new_format/2025-02-24/16-45-20/trained_model/NN_close_100.pth' #**#
# NN_model_name: 'training_results/new_format/2025-03-11/09-58-34/trained_model/NN_close_200.pth' #**# without BPTT
NN_model_name: 'training_results/new_format/2025-05-08/15-43-00/trained_model/NN_close_100.pth' 
# NN_model_name: 'training_results/new_format/2025-01-22/10-26-33/trained_model/NN_close_120.pth' # train for the moving gate

NN_deploy_model_name: 'deployed_model/2025-01-16/09-59-31/trained_model/NN_close_3200.pth' # used in the sitl
NN_freq: 100

penalty:
  QUADRATIC_LOSS: false #or Linear loss
  vel_w: -3
  goal_x_axis_w: 2
  goal_yz_axis_w: 2 #12.0 for last 5 nodes, 240 for last 3 nodes (yz axis)
  scaling_w: 100 #100 for quadratic loss
  det_reg_w: 0.0
  control_reg_w: 0

LBFGS: false
POSITION_ENCODING: false