training:
  TRAIN_FROM_CHECKPOINT: false
  PDP_GRADIENT: true
  USE_PREV_SOLVER: false
  num_epochs: 5000
  # steps_per_epoch: 20
  close_loop_horizon: 20
  learning_rate: 0.0002
  eta_min: 0.00002 #for cosine decay 1% of learning rate
  dyn_decay: 0.90 ## the BPTT decay
  batch_size: 1
