training:
  TRAIN_FROM_CHECKPOINT: false
  PDP_GRADIENT: true
  USE_PREV_SOLVER: false
  num_epochs: 40000
  # steps_per_epoch: 20
  close_loop_horizon: 50
  learning_rate: 0.0006
  eta_min: 0.00002 #for cosine decay 1% of learning rate
  dyn_decay: 0.75 ## the BPTT decay
  batch_size: 32
  lr_gamma: 0.98
  lr_decay_num_epochs: 200

model:
  seed: 1
  input_size: 25 # current drone state (10), goal position (3),gate points (8x3), ## last gate points (8x3)     
  hidden_size: 256
  output_size: 20 # tra_pos(3), tra_9D_orientation(9), [wrpx, wrpy, wrpz], [wrtx, wrty, wrtz], wqt, gamma#
  weights_vector_length: 8
  activation: "silu"
  # activation: "relu"
  
