GPU: 0
body_frame: false
body_rate_test: false
calculate_depth: true
cmdp_lambda_init: 0.0
cmdp_lambda_lr: 0.05
cmdp_softmax_beta: 50.0
cmdp_thresh_ori: 0.001
cmdp_thresh_pos_sq: 0.0005
cmdp_thresh_vel_sq: 0.001
cmdp_use_softmax: true
cruise_speed_cap: 0.0
cruise_speed_cap_weight: 1.0
delta_time: 0.02
discount: 1
domain_randomize_dynamics: true
dr_curriculum_frac: 0.0
dr_factor_max: 1.4
dr_factor_min: 0.6
dr_max_dist_from_gate: 2.0
dr_pos_noise_std: 0.3
dr_ratio: 0.5
dr_sim_steps: 50
dr_vel_noise_std: 0.0
drag_coeff_expand_step: 5.0e-06
drag_coeff_max: 2.019284e-05
drag_coeff_max_final: 2.019284e-05
drag_coeff_min: 2.019284e-05
drag_curriculum_loss_threshold: 0.01
drag_curriculum_patience: 20
enable_domain_randomization: false
end_goal:
- 4.0
- 0
- 2.0
entropy_alpha: 0.01
epochs: 10000
grid_test: false
gru_include_prev_action: false
height: 64
hindsight_window_steps: 10
hindsight_window_weight: 5.0
horizontal_fov_deg: 120
include_gate_orientation_in_obs: false
inject_obs_noise: false
learn_alpha: false
learning_rate: 5.0e-05
loss_aggregator: mean
loss_aggregator_beta: 10.0
max_angular_rates: 3.0
max_range: 20.0
motor_delay: 0.0
motor_tau: 0.0125
nominal_drag: 2.019284e-05
nominal_inertia:
- 0.000296
- 0.000307
- 0.000427
nominal_mass: 0.258
num_obstacles: 0
obs_dim: 2
obs_size: 1
obs_type: 1
policy_file: 20260521-090040
pos_noise_std: 0.05
position_control: true
post_gate_omega_loss_w: 1.0
post_gate_vel_loss_w: 5.0
post_gate_window_steps: 0
rate_controller_gain_jitter: 0.3
rate_controller_p_gains:
- 0.03
- 0.03
- 0.07
recovery_learning_rate: 0.0001
recovery_loss_w_att: 0.5
recovery_loss_w_omega: 0.05
recovery_loss_w_pos: 1.0
recovery_loss_w_vel: 1.0
recovery_policy_file: 20260504-122055
recovery_save_folder: logs/recovery/
rendering: false
residual_dynamics_file: 20260507-191600
residual_dynamics_folder: residual_dynamics
residual_omega: false
residual_torque: false
return_pointcloud: false
room_size: 5.0
sampling_frequency: 200
save_folder: logs/vel_tracking/
segmentation_camera: false
sensitivity_test: false
sim_steps: 200
single_motor_max_thrust: 2.149
target_traversal_speed: 2.0
to_randomize_obs_location: false
train: true
train_recovery_policy: false
truncate_bptt_every: 0
turn_on_scheduler: true
use_cmdp: false
use_full_backward: false
use_gru: true
use_high_fidelity: false
use_hindsight_window: true
use_pre_trained: false
use_px4_allocation: false
use_residual_dynamics: false
use_rma: false
use_rpm_limited_surrogate: false
use_sparse_reward: true
use_stochastic_policy: false
vel_noise_std: 0.05
warp_frame: 1.0
width: 64
window_location:
- 1.5
- 0
- 2.0
window_orientation: 70
window_orientation_range: 0
policy_global: true
